// Interface acceptance closes the unchanged I2 criteria, not the mathematical
// claims carried by the observed arithmetic, gauge or Navier–Stokes object.
export const INTERFACE_CHECKLIST = [
  {id:'I2-01',status:'PASS',implementedScope:'좌표와 색의 단위·원본 필드·scale·변환·데이터/물리 차원을 표시합니다. 차수·categorical 배치·p-adic valuation·공간·Euclidean x4·spectral time·Monte Carlo lag를 서로 다른 타입으로 유지합니다.',testStatus:'전체 관측의 축 계약·원본 경로 검사 및 실제 브라우저 4D/복합체 확인 통과.'},
  {id:'I2-02',status:'PASS',implementedScope:'동일한 실제 4D 장에서 단면, 유한 구간 scalar 적분, 정규화된 조건부 평균, 열린 Wilson line과 닫힌 loop를 각각 계산합니다. 적분 영역·정규화·endpoint·gauge convention·손실 정보를 보존하고, 비단사 관측의 역변환을 허용하지 않습니다.',testStatus:'Simpson 적분/조건부 평균 관계, 실제 경로와 endpoint, scalar/connection 분리, 브라우저 5종 실행 통과.'},
  {id:'I2-03',status:'PASS',implementedScope:'ASSUMED_BOUND·UNITS·EFFECTIVE_MODEL·ENSEMBLE_ESTIMATE 네 모드를 실행합니다. 두 상태의 카메라·색 범위를 공유하고 model/sample/observation hash를 구분합니다. 명시한 유한 spectral 모형 또는 실제 Gibbs chain의 correlator 의존식을 독립 검사하며, 가정 모드에서 원본 장이 유지되는 이유를 표시합니다.',testStatus:'네 모드의 원본/표본 hash·correlator 항등식·변조 대조, 같은 카메라와 공통 색 범위의 실제 브라우저 검사 통과.'},
  {id:'I2-04',status:'PASS',implementedScope:'실제 chain group·미분·kernel/image 생성자와 완전성·Frobenius·Hodge inclusion·비교 사상을 연결합니다. 정수 unimodular 기저의 역순/shear 교체에서 D, F, i, r, h와 filtration을 함께 옮기고 cohomology와 그 Frobenius가 일치함을 검사합니다. 0차원 사상도 정확한 0 사상으로 표시합니다.',testStatus:'정수 chain/retract 항등식과 기저 교체 불변량·선택 성분·행렬 원본 경로·0차원 패널 브라우저 검사 통과.'},
  {id:'I2-05',status:'PASS',implementedScope:'M1 prime atlas의 전체 소수 정의를 유지하며 서로 겹치지 않는 segmented tile을 확대·이동·재계산합니다. 완료 tile과 미계산 구간을 명시하고, 미계산을 빈 소수집합으로 표시하지 않습니다.',testStatus:'타일 경계의 정확한 집합/누락/중복·미계산 대조와 실제 브라우저 구간 이동·재계산 검사 통과.'},
  {id:'I2-06',status:'PASS',implementedScope:'같은 실제 유한 profile의 같은 τ에서 물리/유사 좌표를 나란히 계산합니다. 전체 프레임 고정 물리 시야, 공통 고정/자동 색, 저장된 radial/axial 확대율을 제공합니다. τ=0과 정밀도 부족에서는 양쪽 데이터를 지우고 상태를 표시합니다. 선택한 유한 후보의 기존 PARTIAL 범위를 유지합니다.',testStatus:'좌표 지수·동일 profile·core 수축·고정 시야·색 범위·극소 τ 및 τ=0 검사와 브라우저 양쪽 상태 확인 통과.'},
  {id:'I2-07',status:'PASS',implementedScope:'카메라는 표시 revision만 바꿉니다. 모델/가정 입력 변경은 현재 관측을 닫고, 비동기 완료가 새 편집·선택을 덮어쓰지 않습니다. 실행 기록 선택은 그 실행의 입력을 함께 복원하고, 저장은 실제 소유 receipt와 원래 세션 revision을 검사합니다.',testStatus:'경쟁 실행·입력 변경·과거 입력 복원·소유/세션 저장 gate·동일 소스 재현 MATCH의 로컬 및 브라우저 검사 통과.'},
  {id:'I2-08',status:'PASS',implementedScope:'키보드·정확한 HTML 표·색 이외 표식·카메라 초기화·결정적 LOD와 실제 WebGL 점 렌더러/CPU fallback을 제공합니다. 두 경로는 동일 관측·선택 원본을 읽습니다. 이 클라우드 브라우저는 WebGL context를 만들 수 없어 CPU fallback으로 검증했고, 실제 GLSL/버퍼/raster는 별도 offscreen OpenGL ES software Mesa에서 검사했습니다.',testStatus:'브라우저 CPU 조작/그리기 p95 <100ms; 동일 exact 선택값과 경로 동등성, context-loss 대조, 실제 GLSL 6,000점 p95≈5.2ms·raster 색 오차≤1/255·Float32 좌표 오차<0.001px 통과. 물리 GPU나 이 브라우저의 WebGL 실행을 인증하지 않습니다.'}
].map(c=>({...c,formalComplete:false,acceptanceScope:'원문 I2의 관측·표시 계약 범위. 관측한 수학적 대상의 기존 증거 등급과 미완료 조건은 변경하지 않습니다.',evidencePaths:['evidence/observatory-audit.json','evidence/browser-i2-v58-audit.json','evidence/gpu-shader-raster-audit.json','visualization/evidence/adapted-inventory.json'],remainingObligations:[]}));
