import {requireCondition,groupDescriptor} from './groups.mjs';
import {createField,normalizeFieldSpec} from './fields.mjs';
function positive(x,name){requireCondition(Number.isFinite(x)&&x>0&&x>=1e-4&&x<=1e4,'DELTA_OR_SCALE_BOUNDS',`${name} must lie in [1e-4,1e4].`,name);}
export function canonical(value){if(value===null||typeof value!=='object'){if(typeof value==='number'&&!Number.isFinite(value))throw new Error('NONFINITE_HASH_INPUT');return JSON.stringify(value);}if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';}
export async function sha256(value){const data=typeof value==='string'?value:canonical(value),digest=await globalThis.crypto.subtle.digest('SHA-256',new TextEncoder().encode(data));return Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('');}
export function normalizeFamily(s){
 requireCondition(s&&typeof s==='object','STATE_FAMILY_REQUIRED','A state family needs a declared Delta role and reference scale.','input.family');
 requireCondition(['ASSUMED_BOUND','UNITS','CLASSICAL_SCALE','EFFECTIVE_MODEL'].includes(s.mode),'DELTA_ROLE_NOT_IMPLEMENTED','Choose ASSUMED_BOUND, UNITS, CLASSICAL_SCALE or EFFECTIVE_MODEL. Ensemble estimates are not constructed in M1.','input.family.mode');
 positive(s.delta,'family.delta');positive(s.referenceDelta,'family.referenceDelta');requireCondition(typeof s.energyUnits==='string'&&s.energyUnits.length>0,'ENERGY_UNITS_REQUIRED','Delta energy units are required.');
 if(s.mode==='EFFECTIVE_MODEL'){positive(s.rhoOverEll,'family.rhoOverEll');requireCondition(typeof s.assumptionId==='string'&&s.assumptionId.length>0,'EFFECTIVE_MODEL_ASSUMPTION_REQUIRED','The effective relation ell=hbarC/Delta must name its explicit model assumption.');}
 return {mode:s.mode,delta:s.delta,referenceDelta:s.referenceDelta,energyUnits:s.energyUnits,assumptionId:s.assumptionId??'declared-gap-lower-bound',...(s.mode==='EFFECTIVE_MODEL'?{rhoOverEll:s.rhoOverEll}:{}),quantumExistenceClaim:false};
}
function physicalSource(spec){const p=spec.perturbation;return {kind:spec.kind,embedding:spec.embedding,rho:spec.rho,center:spec.center,gaugeConvention:spec.gaugeConvention,domain:spec.domain,units:spec.units,coupling:spec.coupling,perturbation:p?{kind:p.kind,length:p.length,amplitude:p.amplitude,modes:p.modes,coefficients:p.coefficients,seed:p.seed}:null};}
export async function createStateFamily(group,baseInput,familyInput){
 const base=normalizeFieldSpec(group,baseInput),family=normalizeFamily(familyInput),selected=structuredClone(base);let lengthDisplayFactor=1,interpretation,modelAssumptions=[],fieldChanged=false;
 if(family.mode==='ASSUMED_BOUND'){
  interpretation='Delta changes only the declared spectral lower-bound assumption. It does not determine or alter this classical 4D connection.';
  modelAssumptions=[{id:family.assumptionId,statement:`If a separate specified Hamiltonian has spectrum outside (0,${family.delta}), the declared gap exclusions follow. No Hamiltonian is obtained from this classical field.`}];
 }else if(family.mode==='UNITS'){
  lengthDisplayFactor=family.delta/family.referenceDelta;
  interpretation='Physical field and physical coordinates are fixed. One displayed length unit is Lunit=Delta/referenceDelta base length units: x_display=x/Lunit, A_display=Lunit A, F_display=Lunit^2 F, q4_display=Lunit^4 q4. Delta is a unit label, not a changed physical energy.';
 }else if(family.mode==='CLASSICAL_SCALE'){
  const lambda=family.delta/family.referenceDelta;if(selected.rho!==null)selected.rho/=lambda;if(selected.perturbation)selected.perturbation.length/=lambda;
  if(selected.domain.kind==='PERIODIC_TORUS'){selected.domain.periods=selected.domain.periods.map(v=>v/lambda);selected.domain.origin=selected.domain.origin.map((v,j)=>selected.center[j]+(v-selected.center[j])/lambda);}
  interpretation='Actual classical dilation A_lambda(x)=lambda A(center+lambda(x-center)), lambda=Delta/referenceDelta. Rho and all trial-function lengths are divided by lambda. On a torus the physical periods are also rescaled. This chosen use of Delta is not a quantum mass-gap conclusion.';fieldChanged=lambda!==1;
 }else{
  const ell=base.units.hbarC/family.delta;if(selected.rho!==null)selected.rho=family.rhoOverEll*ell;if(selected.perturbation)selected.perturbation.length=ell;
  requireCondition(selected.domain.kind==='R4_WINDOW','EFFECTIVE_TORUS_RULE_REQUIRED','The shipped effective family is defined on R4; a torus family must additionally specify how volume changes.');
  interpretation='Explicit assumed effective family: ell=hbarC/Delta, rho=kappa ell, and A_trial=(epsilon/ell) sum c phi((x-center)/ell) T. The actual 4D connection is recomputed, including the recorded perturbation. This relation is a model definition, not a Yang-Mills spectral theorem.';
  modelAssumptions=[{id:family.assumptionId,statement:'The effective inverse energy-length relation ell=hbarC/Delta and rho=kappa ell is selected by the user as a model definition.'}];fieldChanged=true;
 }
 const field=createField(group,selected),basePhysical=physicalSource(base),selectedPhysical=physicalSource(field.spec),groupPart={spec:group.spec,dataSha256:group.data.dataSha256};
 const basePhysicalFieldHash=await sha256({group:groupPart,field:basePhysical}),physicalFieldHash=await sha256({group:groupPart,field:selectedPhysical}),assumptionHash=await sha256({family,modelAssumptions}),displayHash=await sha256({physicalFieldHash,lengthDisplayFactor});
 const stateId='state-'+(await sha256({physicalFieldHash,assumptionHash,displayHash})).slice(0,16),groupDescriptorHash=await sha256(groupDescriptor(group));
 const assumptionRecords=modelAssumptions.map(a=>({schema:'MathScope.AssumptionSpec/1',id:'gauge-assumption-'+assumptionHash.slice(0,16),revision:'m1-1',statement:a.statement,reason:family.mode==='ASSUMED_BOUND'?'A declared lower bound of a separately specified spectrum does not generate a classical connection.':'An explicit effective scale relation defines a selected family; it is not a spectral theorem.',origin:family.mode==='ASSUMED_BOUND'?'HYPOTHESIS':'DEFINITION',status:'DECLARED',sourceRefs:[],usedBy:[stateId],introducedBy:'normalized explicit MathScope M1 request'}));
 const assumptionRefs=[];for(const a of assumptionRecords)assumptionRefs.push({id:a.id,revision:a.revision,hash:await sha256(a)});
 return {field,stateId,groupDescriptorHash,assumptionRecords,assumptionRefs,baseFieldSpec:base,fieldSpec:field.spec,familySpec:family,physicalFieldHash,basePhysicalFieldHash,displayHash,assumptionHash,lengthDisplayFactor,modelAssumptions,interpretation,fieldChanged:physicalFieldHash!==basePhysicalFieldHash,displayTransform:{lengthDisplayFactor,coordinateScale:1/lengthDisplayFactor,connectionScale:lengthDisplayFactor,curvatureScale:lengthDisplayFactor**2,q4Scale:lengthDisplayFactor**4,q3Scale:lengthDisplayFactor**3},quantumState:false};
}
export function stateFamilyDescriptor(group,state){group=state.field.group;const s=state.fieldSpec,f=state.familySpec,kind=s.kind==='EMBEDDED_BPST'?'EMBEDDED_BPST':'LIE_ALGEBRA_EXPANSION';const mode={ASSUMED_BOUND:'ASSUMED_BOUND',UNITS:'UNIT_RESCALE',CLASSICAL_SCALE:'EFFECTIVE_FAMILY',EFFECTIVE_MODEL:'EFFECTIVE_FAMILY'}[f.mode];
 return {schema:'MathScope.StateFamilySpec/1',id:state.stateId,revision:'m1-1',sourceRefs:[],assumptionRefs:state.assumptionRefs,gaugeGroupRef:{id:`gauge-${group.id}`,revision:'m1-1',hash:state.groupDescriptorHash},fieldConstruction:{kind,rule:s.kind,gaugeConvention:s.gaugeConvention,parameters:{completeFieldSpec:s,completeFamilySpec:f,...state.displayTransform},...(s.embedding?{embedding:{domain:'SU(2)',codomainRef:{id:`gauge-${group.id}`,revision:'m1-1',hash:state.groupDescriptorHash},formula:'exact '+s.embedding+' generators and compact coordinates in group descriptor',index:group.index,certificateStatus:'THEOREM_REFERENCE',sourceRefs:[]}}:{})},delta:{mode,value:f.delta,units:f.energyUnits,role:state.interpretation},coupling:s.coupling,lattice:null,seed:s.perturbation?.seed??null,channels:[{id:'classical-action-density',kind:'LOCAL_GAUGE_INVARIANT_SCALAR',definition:'sum_{mu<nu} B(F_mu_nu,F_mu_nu)/g^2; this is not a quantum spectral channel'}],scope:{kind:'FINITE',spatial:{bounds:s.domain.kind==='R4_WINDOW'?s.domain.bounds:s.domain.origin.map((v,i)=>[v,v+s.domain.periods[i]])},finite:{description:'Finite matrix Lie basis and finite observation window of the explicit classical source formula',itemCount:group.dimension},description:s.scope},energyInterpretation:{ASSUMED_BOUND:'DECLARED_BOUND',UNITS:'UNIT_CONVENTION',CLASSICAL_SCALE:'EFFECTIVE_MODEL',EFFECTIVE_MODEL:'EFFECTIVE_MODEL'}[f.mode]};
}
export function finiteSpectralModel(s){requireCondition(s&&Number.isFinite(s.delta)&&s.delta>0&&s.delta<=1e4,'SPECTRAL_MODEL_REQUIRED','A positive finite energy Delta and explicit energies/weights are required.');requireCondition(Array.isArray(s.offsets)&&s.offsets.length>=1&&s.offsets.length<=32&&s.offsets.every(e=>Number.isFinite(e)&&e>=0&&e<=1e4),'SPECTRAL_OFFSETS','Offsets must be a nonempty finite list in [0,10000].');requireCondition(Array.isArray(s.weights)&&s.weights.length===s.offsets.length&&s.weights.every(w=>Number.isFinite(w)&&w>=0)&&s.weights.some(w=>w>0),'POSITIVE_CHANNEL_WEIGHTS','Channel weights must be nonnegative and not all zero.');requireCondition(Array.isArray(s.times)&&s.times.length>=2&&s.times.length<=256&&s.times.every(t=>Number.isFinite(t)&&t>=0&&t<=1e4),'SPECTRAL_TIMES','Provide 2..256 finite nonnegative physical time coordinates.');requireCondition(Number.isFinite(s.hbar)&&s.hbar>0,'SPECTRAL_UNITS','Positive hbar is required so exp(-E t/hbar) is dimensionless.');requireCondition(typeof s.assumptionId==='string'&&s.assumptionId.length>0,'SPECTRAL_ASSUMPTION_PROVENANCE','Name the explicit finite-model assumption.');
 const energies=s.offsets.map(e=>s.delta+e),dimension=energies.length+1,gap=Math.min(...energies),channelMass=Math.min(...energies.filter((e,i)=>s.weights[i]>0)),C0=s.weights.reduce((a,b)=>a+b,0),samples=s.times.map(t=>{const correlation=energies.reduce((v,e,i)=>v+s.weights[i]*Math.exp(-e*t/s.hbar),0),upperBound=C0*Math.exp(-s.delta*t/s.hbar);return {time:t,correlation,upperBound,boundResidual:Math.max(0,correlation-upperBound)};});
 return {model:{kind:'DECLARED_FINITE_DIAGONAL_HAMILTONIAN',dimension,diagonal:[0,...energies],vacuumIndex:0,weights:s.weights.slice(),hbar:s.hbar,declaredLowerBound:s.delta,assumptionId:s.assumptionId},gap,channelMass,channelMassInequality:'Delta <= actual finite-H gap <= channel mass; a channel can miss the lowest excitation.',samples,assumptions:[{id:s.assumptionId,statement:'This finite diagonal Hamiltonian and this positive spectral channel measure are explicitly constructed model choices, not inferred from the rendered 4D classical field.'}],finiteSemigroup:'exp(-tH/hbar) is constructed from the displayed diagonal energies for t>=0; finite sums require no limit exchange.',continuumAssumptionsRequired:['A specified self-adjoint nonnegative Hamiltonian on a Hilbert space with a normalized vacuum.','A projection off the full vacuum subspace, with spectral support on [Delta,infinity).','For a bounded O, C(t)=<v,exp(-tH/hbar)v>, v=(I-P0)O Omega; the spectral measure is finite positive.','For unbounded operators, specify a common invariant domain and finite vector norms before using this formula.','Four-dimensional quantum Yang-Mills reconstruction, continuum and infinite-volume limits are separate hypotheses and not implemented here.'],scope:'EXACTLY_SPECIFIED_FINITE_MODEL_WITH_FLOAT64_EVALUATION; NO_QUANTUM_YM_EXISTENCE_CLAIM'};
}
