import * as M from './matrix.mjs';
import {requireCondition,groupElementResidual} from './groups.mjs';
import {evaluateJet,transformedJet,gaugeAt,normalizeGauge} from './fields.mjs';
export function normalizePath(path){requireCondition(Array.isArray(path)&&path.length>=2&&path.length<=33&&path.every(p=>Array.isArray(p)&&p.length===4&&p.every(v=>Number.isFinite(v)&&Math.abs(v)<=1e4)),'PATH_REQUIRED','A piecewise linear path needs 2..33 explicit 4D vertices.','input.path');return path.map(p=>p.slice());}
export function linkTransport(field,x,y,steps,{gauge=null}={}){
 requireCondition(Number.isInteger(steps)&&steps>=1&&steps<=256,'HOLONOMY_STEPS','Midpoint steps per edge must be 1..256.');let u=M.identity(field.group.matrixDimension);const dx=y.map((v,j)=>(v-x[j])/steps);
 for(let k=0;k<steps;k++){const p=x.map((v,j)=>v+(k+.5)*dx[j]),A=gauge?transformedJet(field,p,gauge,{order:0}).A:evaluateJet(field,p,{order:0}).A,h=M.matrix(u.n);for(let mu=0;mu<4;mu++)M.addTo(h,A[mu],dx[mu]);u=M.multiply(u,M.exponential(h));}
 return u;
}
export function pathHolonomy(field,path,steps,{gauge=null}={}){path=normalizePath(path);let product=M.identity(field.group.matrixDimension);const links=[];for(let i=0;i<path.length-1;i++){const u=linkTransport(field,path[i],path[i+1],steps,{gauge});links.push(u);product=M.multiply(product,u);}return {matrix:product,links};}
export function wilsonLoop(field,path,{steps=16,gauge={generator:0,wave:[0.2,-0.1,0.3,0.15],amplitude:0.4,phase:0.2}}={}){
 path=normalizePath(path);requireCondition(Number.isInteger(steps)&&steps>=1&&steps<=128,'HOLONOMY_REFINEMENT_BUDGET','For two-level convergence, base steps must be 1..128.');const closed=path[0].every((v,j)=>v===path.at(-1)[j]);gauge=normalizeGauge(field.group,gauge);
 const coarse=pathHolonomy(field,path,steps),fine=pathHolonomy(field,path,2*steps),transformed=pathHolonomy(field,path,2*steps,{gauge});const omegas=path.map(x=>gaugeAt(field,x,gauge).u);
 let discrete=M.identity(field.group.matrixDimension),maxLinkMembership=0;
 for(let i=0;i<fine.links.length;i++){const l=fine.links[i],lp=M.multiply(M.multiply(omegas[i],l),M.dagger(omegas[i+1]));discrete=M.multiply(discrete,lp);maxLinkMembership=Math.max(maxLinkMembership,groupElementResidual(field.group,l).max);}
 const expected=M.multiply(M.multiply(omegas[0],fine.matrix),M.dagger(omegas.at(-1))),trace=M.trace(fine.matrix),d=field.group.matrixDimension,normalizedRealTrace=trace.re/d;
 const beta=2*d*field.group.metricTraceFactor/field.spec.coupling.g**2,tw=M.trace(discrete),tc=M.trace(transformed.matrix);
 return {path,closed,stepsPerEdge:steps,refinedStepsPerEdge:2*steps,orientation:'U_xy maps the fibre at y to x; midpoint ordered products exp(+A_mu dx_mu); U_xy -> Omega_x U_xy Omega_y^dagger',matrix:M.jsonMatrix(fine.matrix),links:fine.links.map(M.jsonMatrix),normalizedTrace:{re:normalizedRealTrace,im:trace.im/d},wilsonPlaquetteTerm:closed?beta*(1-normalizedRealTrace):null,beta,normalization:'beta=2 dim(R) c/g^2 when B=-c ReTr_R; this is the stated basic-form convention',gaugeInvariantObservable:closed?'normalized closed Wilson trace':'NONE: open-path trace is not gauge invariant',membership:groupElementResidual(field.group,fine.matrix),maxLinkMembership,convergence:{matrixDifference:M.distance(coarse.matrix,fine.matrix),normalizedTraceDifference:Math.abs(M.trace(coarse.matrix).re/d-normalizedRealTrace),interpretation:'two midpoint resolutions; no certified continuum error bound'},gaugeCheck:{spec:gauge,discreteEndpointCovariance:M.distance(discrete,expected),continuumConnectionIntegrationCovariance:M.distance(transformed.matrix,expected),closedDiscreteTraceDifference:closed?Math.hypot(tw.re-trace.re,tw.im-trace.im)/d:null,closedContinuumTraceDifference:closed?Math.hypot(tc.re-trace.re,tc.im-trace.im)/d:null},scope:'Finite deterministic transport of the specified classical field. This is not a sampled quantum Wilson ensemble.'};
}
export function plaquettePath(origin,mu,nu,spacing){requireCondition(Array.isArray(origin)&&origin.length===4&&origin.every(Number.isFinite)&&Number.isInteger(mu)&&Number.isInteger(nu)&&mu>=0&&nu>=0&&mu<4&&nu<4&&mu!==nu&&Number.isFinite(spacing)&&spacing>0,'PLAQUETTE_INPUT','An origin, two distinct axes and positive spacing are required.');const p=origin.slice(),q=origin.slice(),r=origin.slice();p[mu]+=spacing;q[mu]+=spacing;q[nu]+=spacing;r[nu]+=spacing;return [origin.slice(),p,q,r,origin.slice()];}
