const owners=new WeakMap(),EMPTY={type:'object',properties:{},additionalProperties:false};
export function createM1Tools(api){
  const wrap=(keys,required,fn)=>async(input={},options={})=>{try{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!keys.includes(k))||required.some(k=>!Object.hasOwn(input,k))||JSON.stringify(input).length>65536)throw Error('Invalid or oversized tool input.');if(options.signal?.aborted)return {ok:false,code:'CANCELLED',state:'NOT_STARTED'};return await fn(input,options);}catch(e){return {ok:false,code:e.code||'INVALID_REQUEST',message:String(e.message).slice(0,600)};}};
  const jobInput={type:'object',properties:{jobId:{type:'string',minLength:1,maxLength:150}},required:['jobId'],additionalProperties:false};
  const jobId=value=>{if(typeof value!=='string'||value.length<1||value.length>150)throw Error('Invalid job ID.');return value;};
  return [
    {name:'mathscope.research_m1.status',description:'Read installed M1 actual mathematical domains, examples, active session identity, finite jobs and native registration. No session mutation or formal proof is issued.',inputSchema:EMPTY,annotations:{readOnlyHint:true,untrustedContentHint:true},execute:wrap([],[],()=>api.getStatus())},
    {name:'mathscope.research_m1.validate_request',description:'Validate a finite M1 mathematical domain input with installed bounds. It validates a contract and does not establish its analytic hypotheses.',inputSchema:{type:'object',properties:{request:{type:'object'}},required:['request'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:wrap(['request'],['request'],({request})=>api.validateRequest(request))},
    {name:'mathscope.research_m1.run_example',description:'Load one named M1 example in the visible editor and execute it in the bounded static browser worker. Returns a job ID; no mathematical evidence is saved automatically.',inputSchema:{type:'object',properties:{exampleId:{type:'string',minLength:1,maxLength:160}},required:['exampleId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:wrap(['exampleId'],['exampleId'],({exampleId},options)=>{if(typeof exampleId!=='string'||exampleId.length>160)throw Error('Invalid example ID.');return api.runExample(exampleId,options);})},
    {name:'mathscope.research_m1.job_status',description:'Read one locally executed M1 job, including exact request, result scope, source hash, precision diagnostics and open obligations. It cannot issue a proof certificate.',inputSchema:jobInput,annotations:{readOnlyHint:true,untrustedContentHint:true},execute:wrap(['jobId'],['jobId'],({jobId:id})=>api.getJob(jobId(id)))},
    {name:'mathscope.research_m1.cancel_job',description:'Stop a named local M1 worker. The last diagnostic checkpoint is retained; restarting recomputes the exact original input from the beginning.',inputSchema:jobInput,annotations:{readOnlyHint:false,untrustedContentHint:false},execute:wrap(['jobId'],['jobId'],({jobId:id})=>api.cancelJob(jobId(id)))},
    {name:'mathscope.research_m1.save_result',description:'Save an already executed local M1 result to the same active research session with exact object, assumptions, source and job bindings. Refuses changed sessions, stale references and imported/forged receipts. This records finite computation metadata and never issues FORMAL PASS.',inputSchema:jobInput,annotations:{readOnlyHint:false,untrustedContentHint:false},execute:wrap(['jobId'],['jobId'],({jobId:id})=>api.saveResult(jobId(id)))},
    {name:'mathscope.research_m1.audit_adapters',description:'Check analytic-contract completeness and theorem-reference/Lean-target separation using finite negative controls. Does not prove the asserted hypotheses or recompile Lean.',inputSchema:EMPTY,annotations:{readOnlyHint:true,untrustedContentHint:false},execute:wrap([],[],()=>api.checkAdapters())}
  ];
}
export async function registerM1Tools(api,host=typeof document==='undefined'?null:document){
  if(!host)return {registered:false,reason:'NO_DOCUMENT',dispose(){}};
  owners.get(host)?.abort();const controller=new AbortController();owners.set(host,controller);
  const dispose=()=>{controller.abort();if(owners.get(host)===controller)owners.delete(host);};
  if(typeof host.modelContext?.registerTool!=='function')return {registered:false,reason:'NATIVE_REGISTRATION_UNAVAILABLE',dispose};
  const names=[];try{for(const tool of createM1Tools(api)){await host.modelContext.registerTool(tool,{signal:controller.signal});names.push(tool.name);}return {registered:true,names,contract:'document.modelContext.registerTool + AbortSignal',consumerVerification:'PENDING_CURRENT_CLIENT',dispose};}catch(e){dispose();return {registered:false,reason:'REGISTRATION_REJECTED',message:e.message,dispose};}
}
