#!/usr/bin/env python3
"""Independent Fraction replay and 120-decimal checks of A.21 bound evidence.

No JavaScript arithmetic is called here. Exponential enclosures are replayed
from exact fractions, then compared with mpmath. The analytic measure argument
is documented separately; this is not a Lean proof or a global NS witness.
Frozen outer files are read only, and are never regenerated by this script.
"""
from fractions import Fraction as F
from pathlib import Path
import hashlib
import json
import math
import sys
import time

HERE = Path(__file__).resolve().parent
try:
    import mpmath as mp
except ImportError:
    sys.path.insert(0, str(HERE.parents[1] / 'arithmetic' / 'vendor'))
    import mpmath as mp
mp.mp.dps = 120
started = time.monotonic()
checks = []

def check(name, condition, detail=None):
    row = {'id': name, 'pass': bool(condition)}
    if detail is not None:
        row['detail'] = detail
    checks.append(row)
    print(('PASS ' if condition else 'FAIL ') + name)

def mpq(value):
    x = F(value)
    return mp.mpf(x.numerator) / x.denominator

def box(v):
    return F(v['lower']), F(v['upper'])

def product(a, b):
    v = [x*y for x in a for y in b]
    return min(v), max(v)

def square(a):
    if a[0] <= 0 <= a[1]:
        return F(0), max(a[0]**2, a[1]**2)
    return min(a[0]**2, a[1]**2), max(a[0]**2, a[1]**2)

def ceilq(v):
    return -((-v.numerator)//v.denominator)

def dyadic(v, bits, up=False):
    scale = 2**bits
    return F(ceilq(v*scale) if up else (v*scale).__floor__(), scale)

def replay_exp(c, label):
    known = {}
    for k, t in enumerate(c['exponentialAudit']):
        x = F(t['argument'])
        lo, hi = box(t['enclosure'])
        valid = lo > 0 and lo <= hi
        if x < 0:
            a, b = known[-x]
            valid &= (lo, hi) == (1/b, 1/a)
        else:
            s = F(t['reducedArgument'])
            n = t['termsThrough']
            bits = t['scaleBits']
            kpow = t['rangeReductionPowerOfTwo']
            valid &= n == 24 and 0 <= s <= F(1, 8) and x == s*2**kpow
            partial = sum(s**i/F(math.factorial(i)) for i in range(n+1))
            first = s**(n+1)/math.factorial(n+1)
            ratio = s/F(n+2)
            tail = first/(1-ratio)
            valid &= (partial, first, ratio, tail) == tuple(F(t[key]) for key in ['smallPartialSum','firstOmittedTerm','tailRatioUpper','tailUpper'])
            a, b = dyadic(partial, bits), dyadic(partial+tail, bits, True)
            valid &= (a, b) == box(t['smallEnclosure'])
            valid &= len(t['squaringEnclosures']) == kpow
            for step in t['squaringEnclosures']:
                a, b = dyadic(a*a, bits), dyadic(b*b, bits, True)
                valid &= (a, b) == box(step)
            valid &= (a, b) == (lo, hi)
        true_exp = mp.exp(mpq(x))
        valid &= mpq(lo) <= true_exp <= mpq(hi)
        known[x] = lo, hi
        check(f'{label}-exp-{k:02d}-exact-replay-and-mp120', valid)
    return known

def verify_real(c, b, label):
    a = box(b['eta'])
    s = square(a)
    fmin, fmax = 1+s[0], 1+s[1]
    cl, cu = F(c['totalMassLower']), F(c['totalMassUpper'])
    inner, tail = F(c['innerThetaOneMassLower']), F(c['mixedThetaSuffix']['upper'])
    simple_p = -cu, -cl/fmax**2
    improved_p = -cu/fmin**2-tail*(1-1/fmax**2), -cl/fmax**2
    p = max(simple_p[0],improved_p[0]), min(simple_p[1],improved_p[1])
    j = inner/fmax**3, cu/fmin
    simple_pd = product((4*a[0],4*a[1]),j)
    main = product((4*a[0],4*a[1]),(cl/fmax**3,cu/fmin**3))
    err = 4*max(abs(a[0]),abs(a[1]))*tail/fmin
    pd = max(simple_pd[0],main[0]-err), min(simple_pd[1],main[1]+err)
    valid = p == box(b['P']) and pd == box(b['Pprime']) and p[0] <= p[1] < 0 and pd[0] <= pd[1]
    check(label, valid)

def verify_complex(c, b, label):
    w, r = F(b['realWindow']), F(b['tubeRadius'])
    d, az = 1-r*r, w+r
    cu = F(c['totalMassUpper'])
    valid = d > 0 and F(b['denominatorRealPartLower']) == d and F(b['denominatorAbsLower']) == d
    valid &= F(b['pressureAbsUpper']) == cu/d**2 and F(b['pressureDerivativeAbsUpper']) == 4*az*cu/d**3
    valid &= b['branch'] == 'Principal Log on Re(1+z^2)>0' and b['domination']['independentOfY']
    angles = [mp.mpc(0,0),mp.mpc('0.6','0.6'),mp.mpc('-0.6','0.6'),mp.mpc(0,'0.99'),mp.mpc('0.99',0),mp.mpc(0,'-0.99')]
    for anchor in [-mpq(w),mp.mpf(0),mpq(w)]:
        for offset in angles:
            z = anchor+mpq(r)*offset
            v = 1+z*z
            valid &= mp.re(v) >= mpq(d)
            for theta in [mp.mpf(0),mp.mpf(1)/7,mp.mpf(1)/3,mp.mpf('0.5'),mp.mpf(4)/5,mp.mpf(1)]:
                f = mp.exp(-2*theta*mp.log(v))
                fp = -4*theta*z*mp.exp((-2*theta-1)*mp.log(v))
                valid &= abs(f) <= mpq(1/d**2) and abs(fp) <= mpq(4*az/d**3)
    check(label+'-rational-and-noninteger-complex-samples', valid,
          'The sample checks test implementation and do not substitute for the uniform Re(1+z^2)>1-r^2 argument.')

def verify_certificate(c, label):
    e = replay_exp(c, label)
    p = {key:F(v) for key,v in c['parametersExact'].items()}
    rho = p['co']*p['h']
    pslo, pshi = e[2*p['logP']]
    normalized = F(5,2)*e[F(1,5)][1]+F(1,2)*e[F(-2,5)][1]/(1-rho)**2
    cl, cu = F(5,2)*pslo, normalized*pshi
    k = min(512,(13/p['lambda']).__floor__())
    mixed = F(1,2)*pshi/(1-rho)**2/F(2**k)
    check(label+'-mass-envelope-and-both-infinite-tails',
          F(c['totalMassLower']) == cl and F(c['totalMassUpper']) == cu and
          F(c['mass']['normalizedUpper']) == normalized and F(c['mixedThetaSuffix']['upper']) == mixed and
          c['mass']['bothInfiniteEndsIncluded'] and not c['mass']['finiteCutoffUsed'] and not c['mass']['quadratureUsed'])
    expected_h = p['h']
    check(label+'-exact-h-source-binding', F(c['parameterHExact']) == expected_h and F(c['inputBinding']['h']['exact']) == expected_h)
    check(label+'-exp-symbol-vs-rational-enclosure',
          c['innerThetaOneMass']['isRationalValueClaim'] is False and box(c['innerThetaOneMass']) == (F(5,2)*pslo,F(5,2)*pshi))
    q0 = (p['lambda']-p['h'])/(1-p['lambda'])
    q1lo, q1hi = e[-(1-p['lambda'])][0]*q0, q0+1-p['h']
    qholdlo, qholdhi = q1lo+(1-p['h'])*16, q1hi+(1-p['h'])*4*(1/p['h']-1)
    qblo = qholdlo*e[-(1-p['h'])/2][0]
    qbhi = qholdhi+1-p['h']
    qplo = rho/(1-rho)*e[1-p['h']][0]
    qphi = rho/(1-rho)*e[3*(1-p['h'])][1]
    wait = (qbhi/qplo-1)/(1-p['h'])
    s = c['scheduleExistence']
    check(label+'-terminal-comparison-without-ODE-sampling',
          box(s['terminalQBeforeWait']) == (qblo,qbhi) and box(s['terminalQp']) == (qplo,qphi) and
          F(s['wait']['finiteUpper']) == wait and qblo > qphi > 0 and wait > 0)
    verify_real(c,c['realBounds'],label+'-full-real-box')
    verify_complex(c,c['complexBounds'],label+'-default-complex-tube')
    for n,b in enumerate(c['observations']['samples']):
        verify_real(c,{'eta':{'lower':b['eta'],'upper':b['eta']},'P':b['P'],'Pprime':b['Pprime']},f'{label}-observation-{n:02d}-raw-interval')
        lo,hi = box(b['P'])
        normal = lo/pslo,hi/pshi
        center,halfwidth = (normal[0]+normal[1])/2,(normal[1]-normal[0])/2
        check(f'{label}-observation-{n:02d}-normalization',
              box(b['normalizedPressure']) == normal and F(b['normalizedCenter']) == center and F(b['normalizedHalfWidth']) == halfwidth)
    n = c['coefficientNorm']
    q,r = F(n['radiusRatio']),F(n['cauchyRadius'])
    loss = (1+q)/(1-q)**3
    cb = c['complexBounds']
    normp = ceilq(F(cb['pressureAbsUpper'])*loss)
    normpd = ceilq(F(cb['pressureDerivativeAbsUpper'])*loss)
    check(label+'-all-orders-cauchy-coefficient-norm',
          0<q<1 and F(n['radiusLoss']) == loss and F(n['coefficientRadius']) == r*q and
          int(n['pressureNormUpper']) == normp and int(n['pressureDerivativeNormUpper']) == normpd and
          sum(F((k+1)**2)*q**k for k in range(81)) <= loss and n['allEtaDerivativeOrders'])
    check(label+'-global-and-generated-Lean-claims-remain-false',
          all(c['gates'][key] is False for key in ['globalWitness','fullOriginalParameterOrder','exactPressureEqualityWithRepairedE','existingFiniteJetsCertified','fullPremiseBundleLeanChecked']))

fixture = json.loads((HERE/'pressure-analytic-fixture.json').read_text())
cases = json.loads((HERE/'pressure-analytic-cases.json').read_text())
verify_certificate(fixture,'default')
for item in cases['variants']:
    verify_certificate(item['certificate'],item['id'])
for k,b in enumerate(cases['additionalRealBounds']):
    verify_real(fixture,b,f'extra-real-interval-{k:02d}')
for k,b in enumerate(cases['additionalComplexBounds']):
    verify_complex(fixture,b,f'extra-complex-tube-{k:02d}')

# A new independent diagnostic integral uses the exact binary64 input rationals,
# not the decimal inputs of the historical frozen numerical reference. The
# integrals themselves are high precision diagnostics, not proof premises.
nodes, weights = mp.gauss_quadrature(64,'legendre')
def integrate(fun,a,b):
    m,r = (a+b)/2,(b-a)/2
    return r*mp.fsum(weights[k]*fun(m+r*nodes[k]) for k in range(len(nodes)))
def sigma(t):
    if t <= 0:return mp.mpf(0)
    if t >= 1:return mp.mpf(1)
    return 1/(1+mp.exp(1/t**2-1/(1-t)**2))
def primitive(t):
    if t <= 0:return mp.mpf(0)
    if t >= 1:return t-mp.mpf('0.5')
    return integrate(sigma,mp.mpf(0),t)
p = {key:mpq(v) for key,v in fixture['parametersExact'].items()}
Td,lam = mp.exp(p['Md'])+10,p['lambda']
initial = integrate(lambda t:mp.exp(t/5-mp.mpf(6)/5*primitive(t)),mp.mpf(0),mp.mpf(1))/2
decay = mp.exp(-mp.mpf(2)/5)*(1-mp.exp(-Td))/2
entry = mp.exp(-mp.mpf(2)/5-Td)*integrate(lambda t:mp.exp(-t-2*lam*primitive(t)),mp.mpf(0),mp.mpf(1))/2
power_and_pulse = mp.exp(-mp.mpf(2)/5-Td-1-lam)*(-mp.expm1(-(1+2*lam)*(60*mp.log(1/lam)+13/lam)))/(2*(1+2*lam))
numeric_inner_through_pulse = mp.mpf(5)/2+initial+decay+entry+power_and_pulse
suffix_log_upper = -13/lam-mp.log(2)-2*mp.log(1-p['co']*p['h'])
normalization_lo, normalization_hi = box(fixture['mass']['pStarSquared'])
diagnostic_pressure = []
for eta in [mp.mpf(0),mp.mpf('0.5'),mp.mpf(1)]:
    value = -numeric_inner_through_pulse/(1+eta**2)**2
    row = next(x for x in fixture['observations']['samples'] if mpq(x['eta']) == eta)
    lo,hi = box(row['normalizedPressure'])
    check(f'independent-default-source-integral-eta-{eta}',mpq(lo)<value<mpq(hi),
          'Unvalidated quadrature diagnostic inside a separately analytic enclosure; omitted mixed suffix has a strictly positive analytic upper bound, retained by its logarithm.')
    diagnostic_pressure.append({'eta':mp.nstr(eta,10),'normalizedInnerThroughPulsePressure':mp.nstr(value,50)})

# Counterexamples to deliberately weakened alternatives. None are input truth.
positive_trace = next(t for t in fixture['exponentialAudit'] if F(t['argument']) == 28)
small = F(positive_trace['reducedArgument'])
partial = F(positive_trace['smallPartialSum'])
check('negative-control-omitted-exponential-remainder-rejected',mp.exp(mpq(small))>mpq(partial))
check('negative-control-inner-mass-only-upper-rejected',numeric_inner_through_pulse>mp.mpf(5)/2)
r = mpq(fixture['complexBounds']['tubeRadius'])
check('negative-control-missing-complex-denominator-loss-rejected',abs((1+(mp.j*r/2)**2)**(-2))>1)
eta = F(1,2)
check('negative-control-wrong-factor-in-pressure-derivative-rejected',4*eta/(1+eta**2)**3>2*eta/(1+eta**2)**3)
tail = F(fixture['mixedThetaSuffix']['upper'])/2
c = (F(fixture['totalMassLower'])+F(fixture['totalMassUpper']))/2
wrong_rational_datum = -c/F(4)
mixed = -(c-tail)/F(4)-tail
check('negative-control-dropping-nonzero-mixed-tail-rejected',tail>0 and mixed<wrong_rational_datum,
      'Exact Fraction counterexample in the certified positive-mixture class; no tiny subtraction is rounded to zero.')

failed = sum(not row['pass'] for row in checks)
def sha(name):return hashlib.sha256((HERE/name).read_bytes()).hexdigest()
report = {'schema':'MathScope.Navier.SourcePressureIndependentAudit/1','status':'PASS' if failed==0 else 'FAIL',
 'counts':{'passed':len(checks)-failed,'failed':failed,'total':len(checks)},'checks':checks,
 'method':{'exactArithmetic':'Python fractions.Fraction, independent from JavaScript BigInt implementation','highPrecision':f'mpmath {mp.__version__}, 120 decimal digits',
  'diagnosticQuadrature':'64-node Gauss-Legendre with nested integration of the original A.5 step; exact numeric input rationals',
  'negativeControls':5},
 'diagnostics':{'normalizedMassInnerThroughPulse':mp.nstr(numeric_inner_through_pulse,60),'normalizedMixedSuffixPositiveUpperLog':mp.nstr(suffix_log_upper,50),
  'pressure':diagnostic_pressure,'quadratureIsCertified':False,'quadratureUsedByProducer':False},
 'sourceSha256':sha('pressure-analytic.mjs'),'fixtureSha256':sha('pressure-analytic-fixture.json'),'caseSha256':sha('pressure-analytic-cases.json'),
 'scriptSha256':sha('pressure-analytic-reference.py'),'frozenOuterSha256':sha('outer.mjs'),
 'scope':{'wholeEtaBoundsFromAnalyticArgument':True,'samplingSubstitutesForUniformProof':False,'generatedLeanPremiseProof':False,
  'newLeanTargets':0,'exactRepairedFieldPressureIdentity':False,'globalNSWitness':False},
 'command':'python mathscope-m1/navier/followup-construction/pressure-analytic-reference.py','elapsedSeconds':time.monotonic()-started}
(HERE/'pressure-analytic-independent.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({'status':report['status'],'counts':report['counts'],'elapsedSeconds':report['elapsedSeconds']}))
if failed:sys.exit(1)
