import {small,bigint,fail,matrix,zero,identity,multiply,addMatrix,equalMatrix,reduceMatrix,hash,canonical} from './exact.mjs';
import {primeBase,crystallinePrism,validatePrismBase} from './padic.mjs';

export function p1Complex(D=1) {
  D=small(D,'D',1,256);const basis=[[],[],[]],a=[],b=[];
  for(const chart of ['U0','U1'])for(let j=0;j<=D;j++)basis[0].push({id:`${chart}:function:${j}`,chart,coordinate:chart==='U0'?'t':'s',exponent:j,formDegree:0,cechDegree:0,cohomologicalDegree:0,laurentWeight:chart==='U0'?j:-j});
  for(const chart of ['U0','U1'])for(let j=0;j<D;j++)basis[1].push({id:`${chart}:form:${j}`,chart,coordinate:chart==='U0'?'t':'s',exponent:j,formDegree:1,cechDegree:0,cohomologicalDegree:1,laurentWeight:chart==='U0'?j+1:-j-1});
  for(let k=-D;k<=D;k++)basis[1].push({id:`U01:function:${k}`,chart:'U01',coordinate:'t',exponent:k,formDegree:0,cechDegree:1,cohomologicalDegree:1,laurentWeight:k});
  for(let j=-D-1;j<D;j++)basis[2].push({id:`U01:form:${j}`,chart:'U01',coordinate:'t',exponent:j,formDegree:1,cechDegree:1,cohomologicalDegree:2,laurentWeight:j+1});
  for(let j=0;j<=D;j++){if(j){a.push([j-1,j,j]);a.push([D+j-1,D+1+j,j]);}a.push([3*D+j,j,-1]);a.push([3*D-j,D+1+j,1]);}
  for(let j=0;j<D;j++){b.push([D+1+j,j,-1]);b.push([D-j-1,D+j,-1]);}
  for(let k=-D;k<=D;k++)if(k)b.push([D+k,3*D+k,-k]);
  return{schema:'MathScope.IntegralCechDeRhamComplex/1',kind:'P1_CECH_DE_RHAM_SUBCOMPLEX',D,coefficientRing:{kind:'INTEGER_RING'},dims:[2*D+2,4*D+1,2*D+1],basis,differentials:[matrix(4*D+1,2*D+2,a),matrix(2*D+1,4*D+1,b)],convention:{columns:'source',rows:'target',d0:'(df0, df1, f1-f0)',d1:'omega1-omega0-dg',transition:'s=t^(-1); s^j ds = -t^(-j-2) dt'},multiplicativeStructure:{closedUnderProduct:false,certifiedEInfinity:false}};
}
export function p1Retraction(C) {
  const D=C.D,h1=[],h2=[];for(let k=-D;k<=D;k++){h1.push([k>0?k:D+1-k,3*D+k,k>0?-1:1]);if(k)h2.push([k>0?k-1:D-k-1,D+k,-1]);}
  return{schema:'MathScope.StrongDeformationRetract/1',K:{dims:[1,0,1],differentials:[zero(0,1),zero(1,0)],basis:[['1'],[],['dt/t']]},i:[matrix(C.dims[0],1,[[0,0,1],[D+1,0,1]]),zero(C.dims[1],0),matrix(C.dims[2],1,[[D,0,1]])],r:[matrix(1,C.dims[0],[[0,0,1]]),zero(0,C.dims[1]),matrix(1,C.dims[2],[[0,D,1]])],h:[zero(0,C.dims[0]),matrix(C.dims[0],C.dims[1],h1),matrix(C.dims[1],C.dims[2],h2)],identity:'r i=id_K and id_C-i r=d h+h d',denominators:[],uniformCoefficientBound:'Every h,i,r entry is 0, 1, or -1; maps preserve p^N divisibility for every p,N.'};
}
export function checkComplex(C,meter=null,modulus=null) {
  try {
    if(!C||!Array.isArray(C.dims)||C.dims.length<1||C.dims.length>64||!Array.isArray(C.differentials)||C.differentials.length!==C.dims.length-1)return{pass:false,reason:'Wrong complex length'};
    if(C.dims.some(d=>!Number.isSafeInteger(d)||d<0||d>4096))return{pass:false,reason:'Invalid finite free dimensions'};
    if(modulus!==null&&(typeof modulus!=='bigint'||modulus<=0n))return{pass:false,reason:'Positive integer modulus required'};
    const differentials=C.differentials.map((d,k)=>{if(!d||!Array.isArray(d.entries)||d.cols!==C.dims[k]||d.rows!==C.dims[k+1])fail('MATRIX_SHAPE','Differential shape or entries mismatch');return matrix(d.rows,d.cols,d.entries);});
    for(let k=0;k+1<differentials.length;k++)if(multiply(differentials[k+1],differentials[k],meter,modulus).entries.length)return{pass:false,reason:`d_${k+1} d_${k} != 0`};
    return{pass:true,scope:modulus?`mod ${modulus}`:'INTEGER_IDENTITY'};
  }catch(e){return{pass:false,reason:e.message};}
}
export function checkRetraction(C,R,meter=null,modulus=null) {
  const normalize=a=>modulus?reduceMatrix(a,modulus):a,checks=[];
  for(let k=0;k<3;k++){const ir=multiply(R.i[k],R.r[k],meter,modulus),ri=multiply(R.r[k],R.i[k],meter,modulus);let rhs=zero(C.dims[k],C.dims[k]);if(k>0)rhs=addMatrix(rhs,multiply(C.differentials[k-1],R.h[k],meter,modulus));if(k<2)rhs=addMatrix(rhs,multiply(R.h[k+1],C.differentials[k],meter,modulus));checks.push({degree:k,retraction:equalMatrix(normalize(ri),identity(R.K.dims[k])),homotopy:equalMatrix(normalize(addMatrix(identity(C.dims[k]),ir,-1n)),normalize(rhs))});}
  const iChain=checkChainMap(R.K,C,R.i,{meter,modulus}),rChain=checkChainMap(C,R.K,R.r,{meter,modulus});return{pass:checks.every(x=>x.retraction&&x.homotopy)&&iChain.pass&&rChain.pass,checks,iChain,rChain,coefficientScope:modulus?`mod ${modulus}`:'Z'};
}
export function checkChainMap(source,target,maps,{meter=null,modulus=null,sigma='identity'}={}) {
  if(sigma!=='identity')return{pass:false,reason:'Unsupported coefficient Frobenius: this base has phi_A=id.'};if(maps.length!==source.dims.length||maps.length!==target.dims.length)return{pass:false,reason:'Wrong number of component maps'};
  try{for(let k=0;k<maps.length;k++)if(maps[k].rows!==target.dims[k]||maps[k].cols!==source.dims[k])return{pass:false,reason:`Map ${k} has the wrong source/target`};for(let k=0;k<source.differentials.length;k++){const lhs=multiply(target.differentials[k],maps[k],meter,modulus),rhs=multiply(maps[k+1],source.differentials[k],meter,modulus);if(!equalMatrix(lhs,rhs))return{pass:false,reason:`D_target_${k} F_${k} != F_${k+1} sigma(D_source_${k})`};}return{pass:true,formula:'D_target,k F_k = F_(k+1) sigma(D_source,k)',sigma:'IDENTITY_ON_Z_P',scope:modulus?`mod ${modulus}`:'INTEGER_IDENTITY'};}catch(e){return{pass:false,reason:e.message};}
}
export function weightContraction(k) {
  k=bigint(k,'Laurent weight');if(!k)fail('ZERO_WEIGHT','Weight zero contains the surviving H0 and H2; it is not contractible.');
  return{weight:String(k),chart:k>0n?'U0':'U1',a:matrix(2,1,[[0,0,k>0n?k:-k],[1,0,k>0n?-1:1]]),b:matrix(1,2,[[0,0,-1],[0,1,-k]]),h1:matrix(1,2,[[0,1,k>0n?-1:1]]),h2:matrix(2,1,[[0,0,-1]]),universalProof:'MathScope.M1.Arithmetic.positive_weight_contractible / negative_weight_contractible',divisionByWeight:false};
}
export function verifyWeightContraction(w) {return{pass:!multiply(w.b,w.a).entries.length&&equalMatrix(multiply(w.h1,w.a),identity(1))&&equalMatrix(addMatrix(multiply(w.a,w.h1),multiply(w.h2,w.b)),identity(2))&&equalMatrix(multiply(w.b,w.h2),identity(1)),scope:'Z, with an arbitrary integer k in the universal Lean proof'};}
function permutationMinor(a,rows,cols) {const rowIndex=new Map(rows.map((r,i)=>[r,i])),colIndex=new Map(cols.map((c,i)=>[c,i])),e=a.entries.filter(([r,c])=>rowIndex.has(r)&&colIndex.has(c));const rowCount=Array(rows.length).fill(0),colCount=Array(cols.length).fill(0);for(const[r,c,v]of e){if(v!=='1'&&v!=='-1')return{pass:false};rowCount[rowIndex.get(r)]++;colCount[colIndex.get(c)]++;}return{pass:rows.length===cols.length&&rowCount.every(x=>x===1)&&colCount.every(x=>x===1),rows,cols,absoluteDeterminant:'1',method:'Signed permutation minor'};}
export function p1SmithCertificate(C) {const D=C.D;return{d0:{nonzeroInvariantFactors:Array(2*D+1).fill('1'),unitMinor:permutationMinor(C.differentials[0],Array.from({length:2*D+1},(_,i)=>2*D+i),Array.from({length:2*D+1},(_,i)=>i+1)),rankUpperBound:2*D+1,upperBoundReason:'The nonzero diagonal-constant vector lies in the kernel.'},d1:{nonzeroInvariantFactors:Array(2*D).fill('1'),unitMinor:permutationMinor(C.differentials[1],Array.from({length:2*D+1},(_,i)=>i).filter(i=>i!==D),Array.from({length:2*D},(_,i)=>i)),rankUpperBound:2*D,upperBoundReason:'The row of dt/t is zero.'},cohomology:{H0:{freeRank:1,torsion:[],generator:'diagonal constant (1,1)'},H1:{freeRank:0,torsion:[]},H2:{freeRank:1,torsion:[],generator:'[dt/t]'}},coefficientIndependence:'The integral strong deformation retract, not field-rank subtraction, proves these modules after arbitrary coefficient base change.'};}
export function p1Frobenius(source,p,{targetD,meter=null}={}) {
  p=primeBase(p);const expected=BigInt(source.D)*p;if(expected>256n)fail('RESOURCE_LIMIT','Frobenius target D*p exceeds the explicit sparse-complex bound.',{requiredTargetD:String(expected),maximumTargetD:256});if(targetD!==undefined&&BigInt(targetD)!==expected)fail('FROBENIUS_TARGET_MISMATCH','The geometric pullback requires target C(pD); arbitrary cropping is not this pullback.',{sourceD:source.D,p:String(p),requiredTargetD:String(expected)});const target=p1Complex(Number(expected)),lookup=target.basis.map(b=>new Map(b.map((x,i)=>[x.id,i])));
  const maps=source.basis.map((b,k)=>matrix(target.dims[k],source.dims[k],b.map((x,col)=>{const j=x.formDegree===0?Number(p)*x.exponent:Number(p)*(x.exponent+1)-1;const id=`${x.chart}:${x.formDegree?'form':'function'}:${j}`;const row=lookup[k].get(id);if(row===undefined)fail('INTERNAL_CERTIFICATE','Frobenius target basis omits an image.');return[row,col,x.formDegree?String(p):'1'];})));
  const verification=checkChainMap(source,target,maps,{meter});if(!verification.pass)fail('INTERNAL_CERTIFICATE','Frobenius is not a chain map.',verification);const R=p1Retraction(source),T=p1Retraction(target),transported=maps.map((F,k)=>multiply(multiply(T.r[k],F,meter),R.i[k],meter));return{target,maps,verification,transported,cohomologyFrobenius:[{degree:0,multiplier:'1'},{degree:2,multiplier:String(p)}],precision:{operation:'frobenius_pullback',coefficientFrobenius:'identity',coordinateDegree:{source:source.D,target:Number(expected)},lossDigits:0,formCoefficient:String(p),reason:'Integral pullback; multiplication by p does not lose input p-adic digits.'}};
}
export const COMPLETED_MODEL_PROOF=Object.freeze({
  schema:'MathScope.CompletedWeightCertificate/1',support:'The p-adic completion of the algebraic direct sum consists of Laurent coefficient families tending to zero p-adically as |k| tends to infinity. At every N only finitely many coefficients are nonzero modulo p^N.',
  positiveWeight:{a:'x -> (k*x,-x)',b:'(u,v) -> -u-k*v',h1:'(u,v) -> -v',h2:'w -> (-w,0)'},
  negativeWeight:{a:'x -> (-k*x,x)',b:'(u,v) -> -u-k*v',h1:'(u,v) -> v',h2:'w -> (-w,0)'},
  zeroWeight:{d0:'(a,b) -> b-a',r0:'(a,b) -> a',i0:'a -> (a,a)',h1:'c -> (0,c)',H2:'overlap form dt/t'},
  proof:'Each nonzero weight has h1*a=id, a*h1+h2*b=id and b*h2=id. Every h,i,r coefficient is 0 or +/-1. Thus the maps preserve p^N divisibility for every N, preserve restricted coefficient families, and extend continuously to the p-adic completion. The identities hold in every coefficient modulo p^N and hence in the separated inverse limit. No k is inverted, including p|k.',
  scope:'The underlying A-module complex and Frobenius; no claim of multiplicative or E-infinity formality.',
  allWeights:'UNIVERSAL_INTEGER_IDENTITIES',completion:'EXPLICIT_CONTINUOUS_EXTENSION_ARGUMENT',finiteCutoffIsJustifiedBy:'Uniform strong deformation retract, not stability of sampled Betti numbers.',
  leanTargets:['positive_weight_contractible','negative_weight_contractible','restricted_neg','restricted_mul_weight','restricted_select','inverse_system_identity'],
});
export function subcomplexByBasis(C,allowed,{name='SUBCOMPLEX'}={}) {
  if(!Array.isArray(allowed)||allowed.length!==C.dims.length)fail('INVALID_FILTRATION','One basis selector per cochain degree is required.');const look=allowed.map((xs,k)=>{if(!Array.isArray(xs)||new Set(xs).size!==xs.length||xs.some(i=>!Number.isInteger(i)||i<0||i>=C.dims[k]))fail('INVALID_FILTRATION','Invalid basis indices.');return new Map(xs.map((x,i)=>[x,i]));});
  for(let k=0;k<C.differentials.length;k++)for(const[r,c,v]of C.differentials[k].entries)if(look[k].has(c)&&!look[k+1].has(r)&&v!=='0')fail('NOT_SUBCOMPLEX','The differential leaves the selected subspace.',{degree:k,row:r,column:c});
  const dims=allowed.map(x=>x.length),differentials=C.differentials.map((a,k)=>matrix(dims[k+1],dims[k],a.entries.filter(([r,c])=>look[k].has(c)&&look[k+1].has(r)).map(([r,c,v])=>[look[k+1].get(r),look[k].get(c),v])));return{kind:name,dims,differentials,basis:allowed.map((xs,k)=>xs.map(i=>C.basis[k][i])),inclusion:allowed.map((xs,k)=>matrix(C.dims[k],xs.length,xs.map((i,j)=>[i,j,1]))),subcomplex:true};
}
export function filtration(C,{kind='stupid',r=1}={}) {r=small(r,'filtration index',-2,4);if(kind==='nygaard')return{kind:'NYGAARD',status:'UNSUPPORTED',reason:'A derived Nygaard filtration requires its Frobenius twist and descent comparison. Cochain degree or divisibility in an arbitrary splitting is not substituted.'};if(kind==='stupid'||kind==='hodge'){const allowed=C.basis.map((b,k)=>b.map((x,i)=>({x,i})).filter(({x})=>kind==='stupid'?k>=r:x.formDegree>=r).map(({i})=>i));return{...subcomplexByBasis(C,allowed,{name:kind==='stupid'?'DECREASING_COCHAIN_DEGREE':'DE_RHAM_FORM_DEGREE_HODGE'}),r,cohomologyDimensions:null,explanation:'Returned dimensions are cochain groups, not filtered cohomology dimensions.'};}if(kind==='naive_below'){return subcomplexByBasis(C,C.basis.map((b,k)=>k<=r?b.map((_,i)=>i):[]),{name:'REQUESTED_NAIVE_BELOW'});}if(kind==='quotient_below'){const dims=C.dims.map((d,k)=>k<=r?d:0);return{kind:'QUOTIENT_TRUNCATION',r,dims,differentials:C.differentials.map((d,k)=>k+1<=r?d:zero(dims[k+1],dims[k])),subcomplex:false,reason:'The quotient by degrees greater than r, with the outgoing top differential set to zero.'};}if(kind==='smart_below'){if(r<0)return{kind:'SMART_TRUNCATION',r,dims:[0,0,0],differentials:[zero(0,0),zero(0,0)]};if(r===0)return{kind:'SMART_TRUNCATION',r,dims:[1,0,0],differentials:[zero(0,1),zero(0,0)],topKernelGenerators:p1Retraction(C).i[0]};if(r===1){const D=C.D,n=2*D+1,entries=[...Array.from({length:n},(_,i)=>[i,i+1,1]),[D,0,-1]];return{kind:'SMART_TRUNCATION',r,dims:[C.dims[0],n,0],differentials:[matrix(n,C.dims[0],entries),zero(0,n)],topKernelGenerators:matrix(C.dims[1],n,C.differentials[0].entries.filter(([,c])=>c>0).map(([row,c,v])=>[row,c-1,v])),reason:'ker d1 = im d0; the omitted constant column equals the negative of the U1 constant column.'};}return{kind:'SMART_TRUNCATION',r,dims:C.dims,differentials:C.differentials};}fail('UNSUPPORTED_FILTRATION','Unknown filtration or truncation kind.');}
export function comparisonApplication(model,p) {
  if(!['point','P1'].includes(model))fail('UNSUPPORTED_MODEL','Only the point and projective line have this comparison application.');
  return{schema:'MathScope.PrismaticComparisonApplication/1',model,base:crystallinePrism(p),objectIdentity:'PRISMATIC_VIA_COMPARISON',geometry:{specialFiber:model==='point'?'Spec(F_p)':'P1/F_p',lift:model==='point'?'Spec(Z_p)':'P1/Z_p',smooth:true,proper:true,cover:model==='point'?['Spec(Z_p)']:['Spec(Z_p[t])','Spec(Z_p[s])'],overlap:model==='point'?null:'Spec(Z_p[t,t^-1]), s=t^-1',completion:'p-adic completion of the Cech-de Rham coefficient modules'},arrows:[{id:'explicit-replacement',from:'finite-perfect K',to:'completed Cech-de Rham',method:model==='point'?'identity':'integral strong deformation retract and uniformly continuous weight contraction',status:'EXPLICIT_MATHEMATICAL_CONSTRUCTION',formalCoverage:'Universal block identities plus finite matrix fixtures; see the actual Lean audit.'},{id:'de-rham-crystalline',from:'completed Cech-de Rham',to:'RΓ_crys(X/Z_p)',source:'S02',locator:'Theorem 3.6 and Corollary 3.8',hypotheses:['proper smooth lift over Z_p','special fiber X over F_p','completed de Rham hypercohomology'],status:'THEOREM_REFERENCE',leanImport:null},{id:'crystalline-prismatic',from:'RΓ_crys(X/Z_p)',to:'RΓ_Delta(X/Z_p) completed-tensor_(Z_p,phi) Z_p',source:'S01',locator:'Theorem 1.8(1), Theorem 5.2',hypotheses:['bounded prism (Z_p,(p))','smooth X/F_p','phi_A=id'],twist:'The base-change is along the identity, so no nontrivial coefficient twist remains.',frobeniusCompatible:true,status:'THEOREM_REFERENCE',leanImport:null}],multiplicativeCertification:'NOT_CLAIMED_FOR_THE_EXPLICIT_FINITE_REPLACEMENT',formalComplete:false,nativePrismaticSiteImplementation:false,remainingFormalization:['Scheme/formal-scheme geometry and Cech descent in Lean','The exact exported S02 and S01 comparison theorems are not imported into this Lean project.']};
}
export function reduceFreeComplex(C,p,N,meter=null) {
  p=primeBase(p);N=small(N,'N',1,256);if(!C||!Array.isArray(C.dims)||C.dims.length<1||C.dims.length>16||C.dims.some(d=>!Number.isInteger(d)||d<0||d>4096))fail('INVALID_COMPLEX','A bounded complex with explicit finite free dimensions is required.');
  const sourceRing=C.coefficientRing;if(!sourceRing||!['INTEGER_RING','FINITE_P_POWER_RING'].includes(sourceRing.kind))fail('UNSUPPORTED_BASE_CHANGE','Supply an integer free complex or an explicitly typed finite p-power free complex.');let sourceMod=null;
  if(sourceRing.kind==='FINITE_P_POWER_RING'){if(String(sourceRing.p)!==String(p))fail('PADIC_BASE_MISMATCH','This reduction does not identify different prime bases.');const M=small(sourceRing.N,'source N',1,256);if(N>M)fail('PRECISION_REQUIRED','Coefficient reduction cannot create missing digits.',{availableDigits:M,requiredDigits:N});sourceMod=p**BigInt(M);if(sourceRing.modulus!==String(sourceMod))fail('INVALID_MODULUS','Source ring modulus mismatch.');}
  const sourceCheck=checkComplex(C,meter,sourceMod);if(!sourceCheck.pass)fail('NOT_COMPLEX','The source differential does not square to zero in its coefficient ring.',sourceCheck);
  const modulus=p**BigInt(N),result={schema:'MathScope.BoundedFreeComplex/1',kind:'BOUNDED_FREE_COMPLEX',dims:C.dims.slice(),basis:C.basis??C.dims.map((d,k)=>Array.from({length:d},(_,i)=>({id:`C${k}:e${i}`}))),coefficientRing:{kind:'FINITE_P_POWER_RING',p:String(p),N,modulus:String(modulus)},differentials:C.differentials.map(d=>reduceMatrix(d,modulus))};
  if(result.basis.some((basis,k)=>!Array.isArray(basis)||basis.length!==result.dims[k]))fail('INVALID_BASIS','Ordered basis dimensions do not match the complex.');
  return{operation:'derived_base_change',sourceRing,targetRing:result.coefficientRing,result,checks:[{name:'source d squared',...sourceCheck},{name:'reduced d squared',...checkComplex(result,meter,modulus)}],justification:{KFlatReason:'A bounded complex of explicitly free modules is K-flat; tensoring its terms computes derived tensor.',cohomologyBeforeTensor:false,geometricComparison:'NOT_INFERRED_FROM_AN_ARBITRARY_INPUT_COMPLEX'},precision:{operation:'coefficient_reduction',outputDigits:N,lossDigits:sourceRing.kind==='FINITE_P_POWER_RING'?sourceRing.N-N:0,rounding:'0',map:'same-prime residue reduction'}};
}
export async function p1Model({p=3,N=4,D=1,filtrationKind='stupid',filtrationIndex=1,targetD}={},meter=null) {
  p=primeBase(p,meter);N=small(N,'N',1,256);D=small(D,'D',1,32);const C=p1Complex(D),R=p1Retraction(C),dSquared=checkComplex(C,meter),homotopy=checkRetraction(C,R,meter),F=p1Frobenius(C,p,{targetD,meter}),S=p1SmithCertificate(C),comparison=comparisonApplication('P1',p);if(!dSquared.pass||!homotopy.pass||!S.d0.unitMinor.pass||!S.d1.unitMinor.pass)fail('INTERNAL_CERTIFICATE','P1 exact model verification failed.');
  const modulus=p**BigInt(N),reduced={...C,coefficientRing:{kind:'FINITE_P_POWER_RING',p:String(p),N,modulus:String(modulus)},differentials:C.differentials.map(d=>reduceMatrix(d,modulus))},reducedR={...R,i:R.i.map(a=>reduceMatrix(a,modulus)),r:R.r.map(a=>reduceMatrix(a,modulus)),h:R.h.map(a=>reduceMatrix(a,modulus))},raw={complex:C,retraction:R,frobenius:{sourceD:D,targetD:F.target.D,maps:F.maps,transported:F.transported},p:String(p),N,comparison};
  const rawHash=await hash(raw);return{schema:'MathScope.PrismaticModelResult/1',object:{kind:'PRISMATIC_VIA_COMPARISON',model:'P1',p:String(p),relativeDimension:1,cohomologicalDegrees:[0,1,2]},scope:{arithmetic:'EXACT_INTEGER_CONSTRUCTION_AND_MOD_PN_OBSERVATION',geometricModels:['P1/F_p with its standard smooth proper Z_p lift'],precision:{N,D,targetD:F.target.D,cechDegree:1,cohomologicalDegree:2,rootDepth:null,qOrUDegree:null},proof:'FINITE_AND_UNIVERSAL_ALGEBRA_KERNEL_CHECKS_PLUS_EXTERNAL_COMPARISON_THEOREMS'},complex:C,finiteObservation:reduced,retraction:R,completedWeightCertificate:COMPLETED_MODEL_PROOF,frobenius:F,smith:S,comparison,filtration:filtration(C,{kind:filtrationKind,r:filtrationIndex}),checks:[{name:'integer d^2=0',...dSquared},{name:'integer strong deformation retract',...homotopy},{name:'Frobenius chain map',...F.verification},{name:'mod p^N homotopy',...checkRetraction(reduced,reducedR,meter,modulus)},{name:'unit Smith minors',pass:S.d0.unitMinor.pass&&S.d1.unitMinor.pass}],error:{rounding:'0',omittedCoordinates:'Eliminated by the explicit all-weight contraction; not by numeric convergence.',pAdic:'An exact residue class modulo p^N; no extra unknown digits.'},rawHash,integrityPayload:raw,formalComplete:false};
}
export async function pointModel({p=3,N=4}={}) {p=primeBase(p);N=small(N,'N',1,256);const base=crystallinePrism(p),comparison=comparisonApplication('point',p),data={p:String(p),N,complex:{ring:'Z_p',dims:[1],differentials:[],basis:[['1']]},finiteObservation:{ring:{kind:'FINITE_P_POWER_RING',p:String(p),N,modulus:String(p**BigInt(N))},dims:[1],differentials:[]},frobenius:{maps:[identity(1)],cohomology:[{degree:0,multiplier:'1'}]},cohomology:[{degree:0,module:'Z/p^N',freeRank:1,torsion:[]}],comparison};return{schema:'MathScope.PrismaticModelResult/1',object:{kind:'PRISMATIC_VIA_COMPARISON',model:'point',p:String(p),relativeDimension:0},...data,base,scope:{arithmetic:'EXACT_MOD_PN',geometricModel:'Spec(F_p)',precision:{N},proof:'THEOREM_REFERENCE_WITH_FINITE_IDENTITY_CHECK'},checks:[{name:'base prism admission',...validatePrismBase(base)},{name:'point differential and Frobenius',pass:true}],rawHash:await hash(data),integrityPayload:data,formalComplete:false};}
export async function verifyModel(result) {
  try {
    if(result?.object?.kind!=='PRISMATIC_VIA_COMPARISON'||!['P1','point'].includes(result.object.model))return{pass:false,reason:'Unsupported geometric object identity'};
    if(result.formalComplete!==false||result.comparison?.formalComplete!==false)return{pass:false,reason:'External comparison cannot claim complete Lean formalization'};
    if(result.comparison?.multiplicativeCertification!=='NOT_CLAIMED_FOR_THE_EXPLICIT_FINITE_REPLACEMENT')return{pass:false,reason:'Unsupported multiplicative formality claim'};
    if(!validatePrismBase(result.comparison.base).pass)return{pass:false,reason:'Invalid base prism'};
    if(await hash(result.integrityPayload)!==result.rawHash)return{pass:false,reason:'Raw-data hash mismatch'};
    const canonicalComparison=comparisonApplication(result.object.model,result.object.p);
    if(canonical(result.comparison)!==canonical(canonicalComparison))return{pass:false,reason:'Comparison assumptions, geometry, or theorem adapters were modified'};
    if(result.object.model==='P1') {
      const p=primeBase(result.object.p),N=small(result.scope.precision.N,'N',1,256),C=p1Complex(result.scope.precision.D),R=p1Retraction(C),F=p1Frobenius(C,p),S=p1SmithCertificate(C),modulus=p**BigInt(N);
      const finite={...C,coefficientRing:{kind:'FINITE_P_POWER_RING',p:String(p),N,modulus:String(modulus)},differentials:C.differentials.map(d=>reduceMatrix(d,modulus))};
      const raw={complex:C,retraction:R,frobenius:{sourceD:C.D,targetD:F.target.D,maps:F.maps,transported:F.transported},p:String(p),N,comparison:canonicalComparison};
      if(canonical(raw)!==canonical(result.integrityPayload)||canonical(C)!==canonical(result.complex)||canonical(R)!==canonical(result.retraction)||canonical(result.completedWeightCertificate)!==canonical(COMPLETED_MODEL_PROOF))return{pass:false,reason:'Basis, matrices, or all-weight contraction differs from the admitted model'};
      if(canonical(finite)!==canonical(result.finiteObservation)||canonical(S)!==canonical(result.smith))return{pass:false,reason:'Finite coefficient observation or cohomology modules were altered'};
      if(canonical(F)!==canonical(result.frobenius))return{pass:false,reason:'Wrong geometric Frobenius, transported action, or target cutoff'};
      if(!checkComplex(result.complex).pass||!checkRetraction(result.complex,result.retraction).pass)return{pass:false,reason:'Algebraic certificate failed'};
      if(result.filtration?.subcomplex&&(!checkComplex(result.filtration).pass||!checkChainMap(result.filtration,C,result.filtration.inclusion).pass))return{pass:false,reason:'Filtration is not the declared subcomplex'};
    } else {
      const expected=await pointModel({p:result.object.p,N:result.N});
      for(const key of ['complex','finiteObservation','frobenius','cohomology','base','integrityPayload'])if(canonical(result[key])!==canonical(expected[key]))return{pass:false,reason:'Point model or finite observation was altered: '+key};
    }
    return{pass:true,scope:'Explicit model and its exact certificate; literature comparison remains THEOREM_REFERENCE'};
  } catch(e) {return{pass:false,reason:e.message};}
}
