import {ArithmeticError,bigint,small,fail,canonical,hash,meter,matrix,reduceMatrix} from './exact.mjs';
import {PRIME_DOMAIN,segmentedPrimes,primeStatistics,primeView,generatePrimeCertificate,verifyPrimeCertificate,nextPrime,verifyPrimeSegments} from './primes.mjs';
import {padic,addPadic,multiplyPadic,divideByInteger,deltaPadic,precisionFailureFixture,finiteRingModule,verifyFiniteRingModule,determinantPadic,derivedReductionFixture,crystallinePrism,validatePrismBase} from './padic.mjs';
import {pointModel,p1Model,verifyModel,weightContraction,verifyWeightContraction,checkComplex,checkChainMap,checkRetraction,p1Complex,p1Retraction,filtration,reduceFreeComplex} from './complex.mjs';
import {localFactorBundle} from './local-factors.mjs';
import {SOURCES,LOCAL_DESIGN_SOURCES} from './sources.mjs';

export const VERSION='1.0.0';
const KINDS=['arithmetic.primes','arithmetic.primeCertificate','arithmetic.padic','arithmetic.point','arithmetic.p1','arithmetic.localFactors','arithmetic.verify'];
export function getCapabilities(){return{schema:'MathScope.ArithmeticCapabilities/1',version:VERSION,kinds:KINDS,primeDomain:PRIME_DOMAIN,limits:{maxPrimeIntervalWidth:8388608,defaultPrimeIntervalWidth:2097152,segmentIntegers:1048576,maxBasePrime:2000000,chartPoints:20000,primeCertificateIntegerDigits:256,padicDigits:256,p1SourceD:32,p1FrobeniusTargetD:256,moduleMatrixDimension:16,determinantDimension:32},supported:['exact bounded segmented enumeration and Lucas/Pratt certificates','Z_p observations, guard-digit delta, exact integer division, finite-ring Smith certificates','point and P1 crystalline/prismatic comparison models with integral all-weight contraction','explicit P1 chain Frobenius and good finite elliptic point-count Euler factors','decreasing cochain and de Rham Hodge subcomplexes, quotient and smart truncation'],unsupported:['arbitrary native prismatic-site computation','general Tate/minimal-model algorithm or complete elliptic L function','Nygaard descent certificate','general q/Breuil–Kisin/A_inf arithmetic','classical RH or general BSD proof'],externalTheoremAdapters:SOURCES.filter(x=>x.status==='THEOREM_REFERENCE'),formalComplete:false};}
export function validateRequest(request){const errors=[];try{canonical(request);if(!request||typeof request!=='object'||Array.isArray(request))fail('INVALID_REQUEST','An object is required.');if(!KINDS.includes(request.kind))fail('UNSUPPORTED_KIND','Unsupported arithmetic job kind.');for(const key of Object.keys(request))if(!['kind','input','precision','budget'].includes(key))fail('UNKNOWN_REQUEST_FIELD','Unknown request field '+key);for(const field of ['input','precision','budget'])if(request[field]!==undefined&&(!request[field]||typeof request[field]!=='object'||Array.isArray(request[field])))fail('INVALID_REQUEST',field+' must be an object.');for(const key of ['N','D'])if(request.precision?.[key]!==undefined)small(request.precision[key],key,1,key==='D'?32:256);if(request.input?.allPrimesComputed!==undefined)fail('INVALID_DOMAIN','There is no finite all-primes-computed state.');if(request.budget)meter(request.budget);}
catch(e){errors.push({code:e.code??'INVALID_REQUEST',message:e.message,details:e.details??{}});}return{ok:errors.length===0,valid:errors.length===0,errors};}
function padicJob(input,precision,m){const p=input.p??3,N=precision.N??input.N??4,operation=input.operation??'delta',a=input.a?.kind?input.a:padic(p,input.residue??17,input.inputDigits??N);if(operation==='delta')return{operation,...deltaPadic(a,N,{exactInteger:input.exactInteger}),guardDigitCounterexample:precisionFailureFixture(p,Math.min(N,8))};if(operation==='add')return{operation,...addPadic(a,input.b)};if(operation==='multiply')return{operation,...multiplyPadic(a,input.b)};if(operation==='divide')return{operation,...divideByInteger(a,input.denominator,N)};if(operation==='module')return{operation,...finiteRingModule(input.matrix??matrix(1,1,[[0,0,p]]),p,N,m)};if(operation==='determinant')return{operation,...determinantPadic(input.matrix,p,N)};if(operation==='baseChange')return reduceFreeComplex(input.complex,p,N,m);if(operation==='derivedReduction')return{operation,...derivedReductionFixture(p,N)};if(operation==='prism')return{operation,base:crystallinePrism(p),checks:[{name:'prism admission',...validatePrismBase(crystallinePrism(p))}]};fail('UNSUPPORTED_OPERATION','Unsupported p-adic operation.');}
async function verifyJob(input,m){switch(input.type){case'primeCertificate':return verifyPrimeCertificate(input.certificate,{meter:m});case'primeSegments':return verifyPrimeSegments(input.segments,input.a,input.b,{meter:m});case'module':return verifyFiniteRingModule(input.certificate);case'model':return verifyModel(input.result);case'weight':{const w=weightContraction(input.k);return{weight:w,...verifyWeightContraction(w)};}case'complex':return checkComplex(input.complex,m);case'chainMap':return checkChainMap(input.source,input.target,input.maps,{meter:m,sigma:input.sigma??'identity',modulus:input.modulus?bigint(input.modulus):null});case'filtration':return filtration(p1Complex(input.D??1),input);default:fail('UNSUPPORTED_VERIFICATION','Unknown arithmetic verifier type.');}}
function visualization(kind,data,input){if(kind==='arithmetic.primes'){const view=primeView(data,input.view??{});return{points:view.points.map(x=>({pos:[x.x,x.y,x.z],label:`p=${x.prime}`,value:{prime:x.prime,index:x.index}})),lines:[],axes:[{label:'정수 위치',type:'ARITHMETIC_LOCATION'},{label:view.representation.axisTypes.y,type:'COUNT_OR_GAP'},{label:view.representation.zAxis,type:'LAYOUT_ATTRIBUTE'}],description:'완료한 유한 구간의 소수 관측',coordinateMeaning:'좌표는 소수·간격·구간 속성이다. 물리 공간이나 소수집합과 동형인 공간이 아니다.',lostInformation:view.representation.sampled?['표시 예산에 따라 일부 점을 생략한다. 원래 소수 목록과 정확한 개수는 보존한다.']:[],manifest:view.representation,sourceHash:data.rawHash};}if(kind==='arithmetic.p1'){const points=data.complex.basis.flatMap((basis,k)=>basis.map((b,i)=>({pos:[k,i,b.laurentWeight],label:b.id,value:{cohomologicalDegree:k,basisIndex:i,laurentWeight:b.laurentWeight,formDegree:b.formDegree,cechDegree:b.cechDegree}})));const lines=[];for(let k=0;k<2;k++)for(const[r,c,v]of data.complex.differentials[k].entries)lines.push({points:[[k,c,data.complex.basis[k][c].laurentWeight],[k+1,r,data.complex.basis[k+1][r].laurentWeight]],label:`d${k}: ${v}`,value:v});return{points,lines,axes:[{label:'cohomological degree k',type:'DEGREE'},{label:'ordered basis index',type:'CATEGORICAL'},{label:'Laurent weight',type:'INTEGER_WEIGHT'}],description:'P¹의 실제 Čech–de Rham 비교 모델과 미분',coordinateMeaning:'고차원 복합체의 관계를 배치한 3D 도식이다. 공간의 물리적 사영이 아니다.',lostInformation:['무한 weight는 전체 contraction 공식으로 다룬다. 화면에는 요청한 유한 D만 표시한다.','배치 거리·각도는 p-adic 거리나 cohomological 불변량이 아니다.'],sourceHash:data.rawHash};}if(kind==='arithmetic.localFactors')return{points:data.places.filter(x=>x.oracle).map(x=>({pos:[Number(x.prime),Number(x.oracle.count),Number(x.oracle.aP??0)],label:`p=${x.prime}`,value:x.factor})),lines:[],axes:[{label:'prime p',type:'PRIME_INDEX'},{label:'#X(F_p)',type:'EXACT_POINT_COUNT'},{label:'a_p (elliptic only)',type:'TRACE_ATTRIBUTE'}],description:'소수별 점계수와 국소 Euler 인자',coordinateMeaning:'p는 서로 다른 계수환의 지표이다. 서로 다른 p 사이의 ring 연산을 뜻하지 않는다.',lostInformation:['유한 목록 밖의 소수와 미확정 bad factors는 계산되지 않았다.']};return{points:[],lines:[],axes:[],description:'정확한 산술 값은 결과 표와 원자료에 표시한다.',coordinateMeaning:'산술 결과를 물리적 3D 구조로 해석하지 않는다.',lostInformation:[]};}
export async function runJob(request,context={}) {
  const valid=validateRequest(request);if(!valid.ok)throw new ArithmeticError(valid.errors[0].code,valid.errors[0].message,valid.errors[0].details);const{kind,input={},precision={},budget={}}=request,m=meter(budget,context);m.tick(0);let data;
  if(kind==='arithmetic.primes'){if(input.operation==='nextPrime')data=nextPrime(input.after??2,budget,{...context,meter:m});else{data=await segmentedPrimes(input,budget,{...context,meter:m});data.statistics=primeStatistics(data,input,m);}}
  else if(kind==='arithmetic.primeCertificate')data=input.certificate?verifyPrimeCertificate(input.certificate,{meter:m}):generatePrimeCertificate(input.n??97,{meter:m,maxTrialDivisor:small(input.maxTrialDivisor??100000,'maxTrialDivisor',2,1000000),maxWitness:small(input.maxWitness??256,'maxWitness',2,4096)});
  else if(kind==='arithmetic.padic')data=padicJob(input,precision,m);
  else if(kind==='arithmetic.point')data=await pointModel({...input,N:precision.N??input.N??4});
  else if(kind==='arithmetic.p1')data=await p1Model({...input,N:precision.N??input.N??4,D:precision.D??input.D??1},m);
  else if(kind==='arithmetic.localFactors')data=await localFactorBundle(input,precision,m);
  else data=await verifyJob(input,m);
  m.tick(0);const object=data.object??{kind:kind==='arithmetic.primes'?'PRIME_QUERY':kind==='arithmetic.localFactors'?'PRIME_INDEXED_LOCAL_FACTOR_FAMILY':kind==='arithmetic.padic'?'PADIC_ARITHMETIC':'EXACT_FINITE_CERTIFICATE',p:input.p===undefined?null:String(input.p)},checks=data.checks??(data.verification?[{name:'independent certificate verifier',...data.verification}]:typeof data.pass==='boolean'?[{name:'requested verifier',pass:data.pass}]:[]),scope=data.scope??{finite:true,description:'Only the requested bounded input and explicitly supported operations are computed.',infiniteDomain:kind==='arithmetic.primes'?PRIME_DOMAIN:null};
  const payload={schema:'MathScope.M1.ArithmeticResult/1',version:VERSION,kind,status:'COMPLETED',object,request:JSON.parse(canonical(request)),scope,results:data,checks,precisionLedger:data.precision??data.frobenius?.precision??{requested:precision,roundingError:'0 for exact integer/modular operations; each numerical approximation is separately tagged.'},evidence:{calculation:kind==='arithmetic.primes'?'EXACT_CORE_WITH_SEPARATELY_TAGGED_APPROXIMATION':'EXACT_FINITE_OR_EXACT_MODULAR',geometricComparison:data.comparison?'THEOREM_REFERENCE':null,lean:'See separately hashed static Lean audit; this browser job is not a kernel execution.',formalComplete:false},provenance:{sources:SOURCES,localDesign:LOCAL_DESIGN_SOURCES,algorithmVersion:VERSION,assumptions:data.comparison?.base?.assumptions??[],operations:m.operations},visualization:kind==='arithmetic.primes'&&input.operation==='nextPrime'?{points:[],lines:[],axes:[],description:'증명서가 있는 다음 소수',coordinateMeaning:'정확한 정수 결과',lostInformation:[]}:visualization(kind,data,input)};
  payload.resultHash=await hash(payload);return payload;
}
export function getExamples(){return[
  {id:'prime-1000',label:'소수 구간 [2,1000] · π, ψ, Li₂',request:{kind:'arithmetic.primes',input:{a:'2',b:'1000'},precision:{},budget:{maxOperations:50000000}}},
  {id:'prime-million',label:'백만까지 정확한 소수 78,498개',request:{kind:'arithmetic.primes',input:{a:'2',b:'1000000',includePsi:false,segmentSize:65536},precision:{},budget:{maxIntegers:1048576,maxOperations:50000000,maxMillis:60000}}},
  {id:'prime-large-certificate',label:'Number 안전 범위를 넘는 Lucas 인증',request:{kind:'arithmetic.primeCertificate',input:{n:'18446744069414584321'},precision:{},budget:{maxOperations:50000000}}},
  {id:'point-p3',label:'점의 실제 crystalline/prismatic 비교 모델',request:{kind:'arithmetic.point',input:{p:'3'},precision:{N:4},budget:{}}},
  {id:'p1-p3',label:'P¹ · 두 chart · 전체 contraction · Frobenius',request:{kind:'arithmetic.p1',input:{p:'3'},precision:{N:4,D:1},budget:{}}},
  {id:'p1-p5-d2',label:'P¹ · p=5, D=2 → 10',request:{kind:'arithmetic.p1',input:{p:'5',filtrationKind:'hodge',filtrationIndex:1},precision:{N:8,D:2},budget:{}}},
  {id:'delta-guard',label:'δ의 한 자리 손실과 정확 원본 증액',request:{kind:'arithmetic.padic',input:{p:'3',operation:'delta',residue:'17',inputDigits:4,exactInteger:'17'},precision:{N:4},budget:{}}},
  {id:'padic-torsion',label:'Z/27 위 ×3: kernel/cokernel = Z/3',request:{kind:'arithmetic.padic',input:{p:'3',operation:'module',matrix:matrix(1,1,[[0,0,'3']])},precision:{N:3},budget:{}}},
  {id:'derived-reduction',label:'derived mod p: 사라지지 않는 Tor',request:{kind:'arithmetic.padic',input:{p:'3',operation:'derivedReduction'},precision:{N:3},budget:{}}},
  {id:'p1-local-factors',label:'p별 P¹ Frobenius·점계수·Euler 인자',request:{kind:'arithmetic.localFactors',input:{model:'P1',primes:['2','3','5','7']},precision:{levels:[1,2,4,8]},budget:{}}},
  {id:'elliptic-good-bad',label:'E:y²=x³−x · good/bad 국소 인자',request:{kind:'arithmetic.localFactors',input:{model:'elliptic',a:'-1',b:'0',primes:['2','3','5','7','13']},precision:{levels:[1,2,4]},budget:{}}}
];}
export {PRIME_DOMAIN,SOURCES,ArithmeticError};
