import {bigint,small,fail,mod,inverseUnit,valuation,hash} from './exact.mjs';
import {primeBase,crystallinePrism,padic,reducePadic} from './padic.mjs';
import {p1Complex,p1Frobenius} from './complex.mjs';

export function integerModel(input={}) {const kind=input.model??'P1';if(kind==='point'||kind==='P1')return{kind,base:'Spec(Z)',equations:kind==='point'?[]:['P1=Proj Z[X0,X1]'],badPrimes:[],smoothProperOverZ:true};if(kind==='elliptic'){const a=bigint(input.a??'-1','a'),b=bigint(input.b??'0','b'),discriminant=-16n*(4n*a*a*a+27n*b*b);if(!discriminant)fail('SINGULAR_CURVE','The rational cubic has discriminant zero; it is not an elliptic curve.');return{kind,a:String(a),b:String(b),equation:'y^2=x^3+a*x+b',base:'Spec(Z)',discriminant:String(discriminant),minimalModelClaim:false};}fail('UNSUPPORTED_MODEL','Only point, P1 and short Weierstrass elliptic inputs are admitted.');}
export function classifyReduction(model,p) {p=primeBase(p);if(model.kind==='point'||model.kind==='P1')return{prime:String(p),modelSmooth:true,curveGoodReduction:true,status:'GOOD',reason:'Standard projective space or identity point is smooth and proper over Z.'};const d=BigInt(model.discriminant),v=valuation(d,p),smooth=mod(d,p)!==0n;if(smooth)return{prime:String(p),modelSmooth:true,curveGoodReduction:true,status:'GOOD',discriminantValuation:0,minimality:'A unit discriminant is already minimal.',certificate:{discriminant:model.discriminant,residue:String(mod(d,p))}};
  const a=BigInt(model.a),b=BigInt(model.b);if(a%(p**4n)===0n&&b%(p**6n)===0n)return{prime:String(p),modelSmooth:false,curveGoodReduction:null,status:'MINIMIZATION_REQUIRED',discriminantValuation:v,transformation:{x:`${p}^2*x'`,y:`${p}^3*y'`,aPrime:String(a/(p**4n)),bPrime:String(b/(p**6n))},reason:'A singular displayed model may define a curve with good reduction after an integral minimal-model computation.'};
  if(v<12)return{prime:String(p),modelSmooth:false,curveGoodReduction:false,status:'BAD_REDUCTION',discriminantValuation:v,minimality:'Any discriminant-lowering integral Weierstrass transformation lowers v_p(Delta) by 12e. Since 0<v_p(Delta)<12, no integral model can lower it.',localFactorStatus:'UNKNOWN_UNTIL_BAD_REDUCTION_ALGORITHM_OR_CERTIFICATE'};
  return{prime:String(p),modelSmooth:false,curveGoodReduction:null,status:'MINIMIZATION_REQUIRED',discriminantValuation:v,reason:'This backend does not implement a general Tate/minimal-model algorithm.'};
}
export function countProjectiveLine(p,meter=null) {p=primeBase(p);if(p>257n)fail('RESOURCE_LIMIT','The independent normalized-pair oracle is limited to p <= 257.');const set=new Set();for(let x=0n;x<p;x++)for(let y=0n;y<p;y++){meter?.tick();if(x===0n&&y===0n)continue;if(x!==0n)set.add(`1:${mod(y*inverseUnit(x,p),p)}`);else set.add('0:1');}return{count:String(set.size),method:'Enumerate nonzero F_p^2 vectors and identify scalar multiples by normalization',chartCount:String(p+1n),pass:BigInt(set.size)===p+1n};}
export function countElliptic(model,p,meter=null) {p=primeBase(p);if(p>257n)fail('RESOURCE_LIMIT','Direct elliptic point enumeration is limited to p <= 257.');const reduction=classifyReduction(model,p);if(reduction.status!=='GOOD')fail('BAD_OR_UNVERIFIED_REDUCTION','The smooth-crystalline local path requires good reduction.',reduction);let count=1n;const a=BigInt(model.a),b=BigInt(model.b);for(let x=0n;x<p;x++)for(let y=0n;y<p;y++){meter?.tick();if(mod(y*y-x*x*x-a*x-b,p)===0n)count++;}const residues=new Map();for(let y=0n;y<p;y++){const r=String(y*y%p);residues.set(r,(residues.get(r)??0)+1);}let independent=1n;for(let x=0n;x<p;x++)independent+=BigInt(residues.get(String(mod(x*x*x+a*x+b,p)))??0);return{count:String(count),aP:String(p+1n-count),independentCount:String(independent),checks:[{name:'full pair enumeration vs square-residue multiplicities',pass:count===independent}],scope:'Exact finite-field point count; no integral elliptic prismatic complex or MW matrix is inferred.'};}
export async function localFactorBundle(input={},precision={},meter=null) {
  const model=integerModel(input),modelHash=await hash(model),ps=input.primes??['2','3','5','7'];if(!Array.isArray(ps)||ps.length<1||ps.length>64)fail('INPUT_RANGE','Provide 1 to 64 prime places.');const seen=new Set();for(const p of ps){const q=String(primeBase(p));if(seen.has(q))fail('DUPLICATE_PRIME','Duplicate local places are not allowed.');seen.add(q);}const levels=precision.levels??[1,2,4,8];if(!Array.isArray(levels)||levels.length<1||levels.length>16)fail('INPUT_RANGE','Provide 1 to 16 precision levels.');const Ns=[...new Set(levels.map(n=>small(n,'precision level',1,256)))].sort((a,b)=>a-b);if(Ns.length!==levels.length)fail('DUPLICATE_PRECISION','Precision levels must be unique.');const places=[];
  for(const place of ps){meter?.tick(0);const p=primeBase(place),reduction=classifyReduction(model,p),base=crystallinePrism(p);let factor,oracle=null,frobenius=null;
    if(reduction.status!=='GOOD')factor={kind:'UNRESOLVED_LOCAL_FACTOR',status:'UNKNOWN',reason:reduction.reason??reduction.localFactorStatus};
    else if(model.kind==='point'){frobenius=[{degree:0,eigenvalue:'1'}];factor={kind:'SCHEME_ZETA_LOCAL_FACTOR',numerator:['1'],denominator:['1','-1'],variable:'T',status:'EXACT_FINITE_POLYNOMIAL',formula:'1/(1-T)'};oracle={count:'1',frobeniusTrace:'1',pass:true};}
    else if(model.kind==='P1'){const F=p1Frobenius(p1Complex(1),p,{meter});frobenius=F.cohomologyFrobenius;oracle=countProjectiveLine(p,meter);factor={kind:'SCHEME_ZETA_LOCAL_FACTOR',numerator:['1'],denominator:['1',String(-p-1n),String(p)],variable:'T',status:'EXACT_FINITE_POLYNOMIAL',formula:'1/((1-T)(1-p*T))',cohomologyDeterminants:[{degree:0,coefficients:['1','-1']},{degree:2,coefficients:['1',String(-p)]}]};oracle.frobeniusTrace=String(1n+p);oracle.pass=oracle.pass&&oracle.count===oracle.frobeniusTrace;}
    else{oracle=countElliptic(model,p,meter);factor={kind:'ELLIPTIC_L_LOCAL_FACTOR',numerator:['1'],denominator:['1',String(-BigInt(oracle.aP)),String(p)],variable:'T',substitution:'T=p^(-s)',status:'EXACT_FINITE_POLYNOMIAL',formula:'1/(1-a_p*T+p*T^2)',cohomologyOrigin:'H1 Frobenius characteristic polynomial from the good-reduction trace theorem; not a computed integral prismatic matrix.',source:{id:'S08',locator:'pp.1-2',status:'THEOREM_REFERENCE'}};}
    const tower=Ns.map(N=>({N,coefficientRing:{kind:'FINITE_P_POWER_RING',p:String(p),N,modulus:String(p**BigInt(N))},modelHash,cohomologyFrobenius:frobenius?.map(f=>({degree:f.degree,multiplier:padic(p,f.multiplier??f.eigenvalue,N)}))??null}));
    const arrows=Ns.slice(1).map((N,i)=>({source:{p:String(p),N},target:{p:String(p),N:Ns[i]},kind:'COEFFICIENT_REDUCTION',method:'Termwise reduction of a bounded free replacement; derived tensor is computed on the complex.',crossPrime:false}));places.push({prime:String(p),modelHash,reduction,base,precisionTower:{levels:tower,arrows},factor,oracle,frobeniusConvention:'Geometric Frobenius on etale/rational cohomology; the crystalline pullback convention is fixed to have H2(P1) eigenvalue p.',conductor:{status:model.kind==='elliptic'?'UNKNOWN':'TRIVIAL_FOR_STANDARD_MODEL',value:model.kind==='elliptic'?null:'1'},sources:model.kind==='elliptic'?['S08']:['S01','S02','S07']});
  }
  const unresolved=places.filter(x=>x.factor.status==='UNKNOWN').map(x=>x.prime),archimedean=model.kind==='elliptic'?{kind:'ELLIPTIC_COMPLETED_FACTOR',gamma:'(2*pi)^(-s)*Gamma(s)',conductor:'UNKNOWN',normalization:'Lambda_E=N_E^(s/2)*(2*pi)^(-s)*Gamma(s)*L(E,s)',status:'INCOMPLETE_LOCAL_DATA'}:{kind:'PROJECTIVE_ZETA_COMPLETION',gamma:model.kind==='point'?'Gamma_R(s)':'Gamma_R(s)*Gamma_R(s-1)',GammaR:'pi^(-s/2)*Gamma(s/2)',conductor:'1',status:'SYMBOLIC_NORMALIZATION'};
  return{schema:'MathScope.PrimeIndexedArithmeticPackage/1',model,modelHash,primeDomain:{kind:'SYMBOLIC_PRIME_INDEX_SET',definition:'{ n : Nat | Nat.Prime n }'},places,coverage:{finitePrimePlaces:[...seen],unresolvedFinitePlaces:unresolved,uncomputed:'Every prime outside the finite place list'},globalBundle:{kind:model.kind==='elliptic'?'FINITE_INCOMPLETE_ELLIPTIC_EULER_PRODUCT':'FINITE_SCHEME_ZETA_EULER_PRODUCT',status:'INCOMPLETE_LOCAL_DATA',isCompleteGlobalLFunction:false,goodOnlyNotation:model.kind==='elliptic'?'L^S finite product':null,archimedean,analyticContinuation:null,rootNumber:null,reason:'Finite local data do not certify an infinite Euler product. Unresolved bad places and conductor remain explicit.'},checks:places.flatMap(x=>x.oracle?[{name:`local count/trace p=${x.prime}`,pass:x.oracle.pass??x.oracle.checks.every(c=>c.pass)}]:[]),crossPrimeArithmetic:'REJECTED; p indexes a family, not a coefficient-ring identification.'};
}
export function verifyTowerReduction(p,values,N1,N2) {p=primeBase(p);if(N1<N2)fail('INPUT_RANGE','Precision reduction cannot increase N.');return values.map(value=>({original:padic(p,value,N1),reduced:reducePadic(padic(p,value,N1),N2),direct:padic(p,value,N2),pass:reducePadic(padic(p,value,N1),N2).residue===padic(p,value,N2).residue}));}
