import {bigint,small,fail,mod,inverseUnit,valuation,powmod,matrix,dense,fromDense,identity,multiply,reduceMatrix,equalMatrix,determinant,canonical} from './exact.mjs';
import {trialPrime} from './primes.mjs';

export function primeBase(p,meter=null) {p=bigint(p,'p');if(p>2000000n||!trialPrime(p,meter))fail('INVALID_PRIME','This arithmetic base requires a certified prime p <= 2,000,000.');return p;}
export function padic(p,residue,N) {p=primeBase(p);N=small(N,'N',1,256);return{kind:'PADIC_BALL',p:String(p),residue:String(mod(bigint(residue),p**BigInt(N))),digits:N,interpretation:'A residue-class observation of Z_p, not an independent prism.'};}
function sameBase(a,b){if(a?.kind!=='PADIC_BALL'||b?.kind!=='PADIC_BALL'||String(a.p)!==String(b.p))fail('PADIC_BASE_MISMATCH','Different primes do not share coefficient arithmetic.');return[padic(a.p,a.residue,a.digits),padic(b.p,b.residue,b.digits)];}
export function reducePadic(a,N){a=padic(a.p,a.residue,a.digits);N=small(N,'target N',1,a.digits);return padic(a.p,a.residue,N);}
export function addPadic(a,b){[a,b]=sameBase(a,b);return{value:padic(a.p,BigInt(a.residue)+BigInt(b.residue),Math.min(a.digits,b.digits)),precision:{operation:'addition',lossDigits:0,inputDigits:[a.digits,b.digits],outputDigits:Math.min(a.digits,b.digits)}};}
export function multiplyPadic(a,b){[a,b]=sameBase(a,b);const p=BigInt(a.p),va=valuation(BigInt(a.residue),p,a.digits),vb=valuation(BigInt(b.residue),p,b.digits),N=Math.min(256,a.digits+vb,b.digits+va);return{value:padic(p,BigInt(a.residue)*BigInt(b.residue),N),precision:{operation:'multiplication',inputDigits:[a.digits,b.digits],valuationLowerBounds:[va,vb],outputDigits:N,formula:'min(N_a+v_p(b), N_b+v_p(a)); valuation of zero is only a lower bound'}};}
export function divideByInteger(a,denominator,targetN){a=padic(a.p,a.residue,a.digits);const p=BigInt(a.p),d=bigint(denominator);if(!d)fail('DIVISION_BY_ZERO','Nonzero denominator required.');const v=valuation(d,p),N=targetN===undefined?a.digits-v:small(targetN,'target N',1,256);if(N<1||a.digits<N+v)fail('PRECISION_REQUIRED','Division by p^v requires v additional input digits.',{operation:'division',requiredDigits:N+v,availableDigits:a.digits,lossDigits:v});const pv=p**BigInt(v);if(BigInt(a.residue)%pv)fail('NONINTEGRAL_QUOTIENT','The requested quotient is outside Z_p.');const m=p**BigInt(N),u=d/pv;return{value:padic(p,BigInt(a.residue)/pv*inverseUnit(u,m),N),precision:{operation:'division_by_exact_integer',lossDigits:v,inputDigits:a.digits,outputDigits:N,divisorValuation:v,unitDivisionOnlyAfterExtractingKnownPower:true}};}
export function deltaPadic(input,targetN,{exactInteger}={}) {
  input=padic(input.p,input.residue,input.digits);const p=BigInt(input.p),N=small(targetN??Math.max(1,input.digits-1),'target N',1,255);let a=input,upgraded=false;
  if(a.digits<N+1){if(exactInteger===undefined)fail('PRECISION_REQUIRED','delta modulo p^N requires an input modulo p^(N+1).',{requiredDigits:N+1,availableDigits:a.digits,lossDigits:1});const exact=bigint(exactInteger);if(mod(exact,p**BigInt(a.digits))!==BigInt(a.residue))fail('EXACT_SOURCE_MISMATCH','The exact source does not reduce to the supplied observation.');a=padic(p,exact,N+1);upgraded=true;}
  const workingMod=p**BigInt(N+1),r=mod(BigInt(a.residue),workingMod),numerator=mod(r-powmod(r,p,workingMod),workingMod);if(numerator%p)fail('INTERNAL_CERTIFICATE','Frobenius lift numerator is not divisible by p.');
  return{value:padic(p,numerator/p,N),precision:{operation:'delta',formula:'delta(a)=(a-a^p)/p on Z_p with phi_A=id',inputDigits:input.digits,workingDigits:a.digits,outputDigits:N,lossDigits:1,guardDigits:1,autoIncreasedFromExactSource:upgraded,exactSourceUsed:upgraded?String(exactInteger):null}};
}
export function precisionFailureFixture(p=3,N=3) {p=primeBase(p);N=small(N,'N',1,255);const a=0n,b=p**BigInt(N);return{p:String(p),N,inputsEqualModuloPN:true,residues:[String(mod(a,b)),String(mod(b,b))],deltaAtN:[deltaPadic(padic(p,a,N+1),N).value,deltaPadic(padic(p,b,N+1),N).value],conclusion:'The same p^N residue has two distinct delta residues modulo p^N. An unknown guard digit cannot be invented.'};}
export function crystallinePrism(p) {
  p=primeBase(p);return{schema:'MathScope.ArithmeticBase/1',kind:'SYMBOLIC_CRYSTALLINE_PRISM',p:String(p),A:'Z_'+p,I:'(p)',phi:{kind:'IDENTITY_RING_ENDOMORPHISM',formula:'phi_A(a)=a'},delta:'(a-a^p)/p',finiteObservationIsPrism:false,assumptions:[{id:'base-p-prime',statement:`${p} is prime`,status:'EXACT_FINITE_CHECK'},{id:'base-torsionfree',statement:'Z_p is p-torsionfree',status:'STANDARD_MATHEMATICAL_CONSTRUCTION'},{id:'base-complete',statement:'Z_p = inverse_limit_N Z/p^N is p-adically complete',status:'STANDARD_MATHEMATICAL_CONSTRUCTION'},{id:'base-cartier',statement:'p is a nonzerodivisor and I=(p) is Cartier',status:'STANDARD_MATHEMATICAL_CONSTRUCTION'},{id:'base-prism',statement:'p belongs to I+phi(I)A and A/I has bounded p-power torsion',status:'EXTERNAL_THEOREM_APPLICATION'}],source:{id:'S01',locator:'Definition 1.1, Example 1.3(1), Definition 1.4',status:'THEOREM_REFERENCE'},admissions:[],formalComplete:false};
}
export function validatePrismBase(value) {const errors=[];if(value?.kind!=='SYMBOLIC_CRYSTALLINE_PRISM')errors.push('The admitted base is symbolic Z_p, not Z/p^N.');try{primeBase(value?.p);}catch(e){errors.push(e.message);}if(value?.A!=='Z_'+String(value?.p))errors.push('Coefficient ring and prime index disagree.');if(value?.finiteObservationIsPrism!==false)errors.push('Finite observation must not be promoted to a prism.');if(value?.phi?.kind!=='IDENTITY_RING_ENDOMORPHISM'||value?.phi?.formula!=='phi_A(a)=a'||value?.delta!=='(a-a^p)/p')errors.push('This backend only implements the specified identity Frobenius lift.');if(value?.I!=='(p)')errors.push('Wrong prism ideal.');for(const id of ['base-p-prime','base-torsionfree','base-complete','base-cartier','base-prism'])if(!value?.assumptions?.some(x=>x.id===id&&!['UNVERIFIED','UNKNOWN','USER_AXIOM'].includes(x.status)))errors.push('Missing or unverified assumption '+id);if(value?.formalComplete!==false)errors.push('The base admission is not a complete Lean formalization.');return{pass:errors.length===0,errors};}

/* Smith diagonalization over Z/p^N. Every division used for row/column operations is by a unit.
   A representative divisible by p^v may be divided as an integer to choose an elimination coefficient;
   p^v is never treated as an invertible ring element. */
export function finiteRingModule(a,p,N,meter=null) {
  p=primeBase(p);N=small(N,'N',1,256);a=matrix(a.rows,a.cols,a.entries);if(a.rows>16||a.cols>16)fail('RESOURCE_LIMIT','Module certificates currently support matrices up to 16 x 16.');const modulus=p**BigInt(N),B=dense(reduceMatrix(a,modulus)),U=dense(identity(a.rows)),V=dense(identity(a.cols)),ops=[];
  const rowSwap=(i,j)=>{[B[i],B[j]]=[B[j],B[i]];[U[i],U[j]]=[U[j],U[i]];ops.push({kind:'row_swap',i,j});};
  const colSwap=(i,j)=>{for(const r of B)[r[i],r[j]]=[r[j],r[i]];for(const r of V)[r[i],r[j]]=[r[j],r[i]];ops.push({kind:'column_swap',i,j});};
  const rowScale=(i,u)=>{B[i]=B[i].map(x=>mod(x*u,modulus));U[i]=U[i].map(x=>mod(x*u,modulus));ops.push({kind:'row_unit_scale',i,unit:String(u)});};
  const rowAdd=(i,k,c)=>{B[i]=B[i].map((x,j)=>mod(x+c*B[k][j],modulus));U[i]=U[i].map((x,j)=>mod(x+c*U[k][j],modulus));ops.push({kind:'row_add',i,k,c:String(c)});};
  const colAdd=(j,k,c)=>{for(const row of B)row[j]=mod(row[j]+c*row[k],modulus);for(const row of V)row[j]=mod(row[j]+c*row[k],modulus);ops.push({kind:'column_add',j,k,c:String(c)});};
  const vals=[];for(let k=0;k<Math.min(a.rows,a.cols);k++){let best=N,br=-1,bc=-1;for(let i=k;i<a.rows;i++)for(let j=k;j<a.cols;j++){meter?.tick();const v=valuation(B[i][j],p,N);if(v<best){best=v;br=i;bc=j;}}if(br<0)break;if(br!==k)rowSwap(br,k);if(bc!==k)colSwap(bc,k);const pv=p**BigInt(best),unit=B[k][k]/pv;rowScale(k,inverseUnit(unit,modulus));for(let i=k+1;i<a.rows;i++)if(B[i][k]){if(B[i][k]%pv)fail('INTERNAL_CERTIFICATE','DVR pivot valuation is not minimal.');rowAdd(i,k,-B[i][k]/pv);}for(let j=k+1;j<a.cols;j++)if(B[k][j]){if(B[k][j]%pv)fail('INTERNAL_CERTIFICATE','DVR pivot valuation is not minimal.');colAdd(j,k,-B[k][j]/pv);}vals.push(best);}
  const certificate={schema:'MathScope.DVRSmithCertificate/1',ring:{kind:'FINITE_P_POWER_RING',p:String(p),N,modulus:String(modulus)},original:a,U:fromDense(U),V:fromDense(V),diagonal:fromDense(B,a.cols),valuations:vals,operations:ops};
  const checked=verifyFiniteRingModule(certificate);if(!checked.pass)fail('INTERNAL_CERTIFICATE','DVR normal-form certificate failed independent verification.',checked);
  const factors=vals.filter(v=>v>0).map(v=>({kind:'CYCLIC_P_POWER_MODULE',p:String(p),exponent:v}));
  return{certificate,verification:checked,module:{kernel:{cyclic:factors,freeRank:a.cols-vals.length,generators:'Columns of V scaled by p^(N-v_i); zero columns give free generators.'},cokernel:{cyclic:factors,freeRank:a.rows-vals.length,presentation:'Diagonal presentation in the U-transformed codomain.'},image:{cyclic:vals.map(v=>({kind:'CYCLIC_P_POWER_MODULE',p:String(p),exponent:N-v})),freeRank:0},fieldRank:null},precision:{operation:'basis_reduction',inputDigits:N,outputDigits:N,lossDigits:0,reason:'Verified unit row and column transformations; no inverse of a nonunit.'}};
}
export function verifyFiniteRingModule(c) {try{const p=primeBase(c.ring.p),N=small(c.ring.N,'N',1,256),m=p**BigInt(N);if(c.ring.modulus!==String(m))return{pass:false,reason:'Ring modulus mismatch'};const A=matrix(c.original.rows,c.original.cols,c.original.entries),U=matrix(c.U.rows,c.U.cols,c.U.entries),V=matrix(c.V.rows,c.V.cols,c.V.entries),S=matrix(c.diagonal.rows,c.diagonal.cols,c.diagonal.entries);if(U.rows!==A.rows||U.cols!==A.rows||V.rows!==A.cols||V.cols!==A.cols)return{pass:false,reason:'Basis dimensions mismatch'};if(mod(determinant(U),p)===0n||mod(determinant(V),p)===0n)return{pass:false,reason:'Basis map is not a unit'};if(!equalMatrix(multiply(multiply(U,A,null,m),V,null,m),reduceMatrix(S,m)))return{pass:false,reason:'U A V differs from S'};const vals=c.valuations;if(!Array.isArray(vals)||vals.some((v,i)=>!Number.isInteger(v)||v<0||v>=N||(i&&v<vals[i-1])))return{pass:false,reason:'Invalid invariant valuations'};const expected=matrix(A.rows,A.cols,vals.map((v,i)=>[i,i,p**BigInt(v)]));if(!equalMatrix(reduceMatrix(S,m),expected))return{pass:false,reason:'Not the declared Smith diagonal'};return{pass:true,method:'Independent transformation product + exact Bareiss determinant unit check',coefficientScope:`mod ${p}^${N}`};}catch(e){return{pass:false,reason:e.message};}}
export function determinantPadic(a,p,N) {p=primeBase(p);N=small(N,'N',1,256);const d=determinant(a);return{value:padic(p,d,N),integerLiftDeterminant:String(d),precision:{operation:'determinant',inputDigits:N,outputDigits:N,lossDigits:0,reason:'The determinant is an integral polynomial in entries. Fraction-free computation on integer lifts does not consume p-adic digits.'}};}
export function derivedReductionFixture(p,N=3) {p=primeBase(p);N=small(N,'N',1,256);return{schema:'MathScope.DerivedReductionFixture/1',source:{ring:'Z_'+p,degrees:[0,1],differential:String(p),cohomology:{H0:'0',H1:'Z/p'}},derivedBaseChange:{method:'Tensor the bounded free complex, which is K-flat',ring:'F_'+p,differential:'0',cohomology:{H0:'F_'+p,H1:'F_'+p}},ordinaryCohomologyTensor:{H0:'0',H1:'F_'+p},finiteModule:finiteRingModule(matrix(1,1,[[0,0,p]]),p,N),reason:'Tor contributes in degree 0; taking cohomology before base change loses it.',formalScope:'The vanishing reduced differential and finite module identities have separate kernel-checked fixtures; the general derived-category theorem is an external mathematical construction.'};}
