export const SOURCES = Object.freeze([
  {id:'S01',title:'Bhatt–Scholze, Prisms and Prismatic Cohomology',url:'https://people.mpim-bonn.mpg.de/scholze/prisms.pdf',locator:'Definition 1.1; Example 1.3(1); Definition 1.4; Theorem 1.8(1), printed pp.2–4; Theorem 5.2',accessed:'2026-10-09',role:'Bounded crystalline prism and Frobenius-compatible crystalline comparison',status:'THEOREM_REFERENCE',leanImport:null},
  {id:'S02',title:'Bhatt–de Jong, Crystalline cohomology and de Rham cohomology',url:'https://arxiv.org/html/1110.5001v1',locator:'Theorem 3.6 and Corollary 3.8',accessed:'2026-10-09',role:'De Rham hypercohomology of a proper smooth Z_p lift computes crystalline cohomology of its special fiber.',status:'THEOREM_REFERENCE',leanImport:null},
  {id:'S07',title:'Deligne, La conjecture de Weil I',url:'https://www.numdam.org/item/PMIHES_1974__43__273_0.pdf',locator:'(1.5.1)–(1.5.4), printed pp.275–276',accessed:'2026-10-09',role:'Finite-field trace and alternating determinant convention; not a classical RH bridge.',status:'THEOREM_REFERENCE',leanImport:null},
  {id:'S08',title:'Wiles, The Birch and Swinnerton-Dyer Conjecture',url:'https://www.claymath.org/wp-content/uploads/2022/05/birchswin.pdf',locator:'pp.1–2, good elliptic Euler factors and the BSD statement',accessed:'2026-10-09',role:'Local H1 L-factor and distinction from the scheme zeta factor.',status:'THEOREM_REFERENCE',leanImport:null},
  {id:'S10',title:'NIST DLMF §25.16 Mathematical Applications',url:'https://dlmf.nist.gov/25.16',locator:'§25.16(i), equations 25.16.1–25.16.4',accessed:'2026-10-09',role:'Chebyshev psi, prime counting, PNT/RH scope.',status:'THEOREM_REFERENCE',leanImport:null},
  {id:'MATHLIB-LUCAS',title:'mathlib Lucas primality theorem',url:'https://github.com/leanprover-community/mathlib4/blob/d13f23b723b8a846827a245b89c10fc7d3f11612/Mathlib/NumberTheory/LucasPrimality.lean',locator:'lucas_primality, reverse_lucas_primality',accessed:'2026-10-09',role:'The library theorem is imported by the arithmetic Lean adapter. The JavaScript Pratt certificate checker is separately tested.',status:'LEAN_IMPORT_CHECKED',leanImport:'MathScope.M1.Arithmetic.lucas_certificate_sound',audit:'evidence/lean-audit.json'},
  {id:'S14',title:'SageMath, Isomorphisms between Weierstrass models',url:'https://doc.sagemath.org/html/en/reference/arithmetic_curves/sage/schemes/elliptic_curves/weierstrass_morphism.html',locator:'WeierstrassIsomorphism: explicit (u,r,s,t) coordinate and coefficient transformation formulas',accessed:'2026-10-09',role:'A displayed singular nonminimal model is distinguished from the reduction of the curve; x=u^2*x_new, y=u^3*y_new rescales short coefficients by u^4 and u^6.',status:'THEOREM_REFERENCE',leanImport:null},
]);
export const LOCAL_DESIGN_SOURCES=Object.freeze(['blueprint-work/arithmetic-stages.json: P1-01..P3-08','blueprint-work/arithmetic-design.md: §§3–5, §§9–11','blueprint-work/appendix-arithmetic.tex: A1–A4','blueprint-work/platform-stages.json: I1-03,I1-07,I3-02,I3-04']);
