import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFile,readFile} from 'node:fs/promises';
import {getExamples,getCapabilities,runJob,validateRequest} from '../index.mjs';
import {matrix,dense,mod,hash,clone,canonical,multiply,equalMatrix,identity,reduceMatrix,inverseUnit,isqrt} from '../exact.mjs';
import {segmentedPrimes,linearPrimeOracle,verifyPrimeSegments,generatePrimeCertificate,verifyPrimeCertificate,primeStatistics,primeView,streamInterval,nextPrime} from '../primes.mjs';
import {padic,deltaPadic,precisionFailureFixture,addPadic,multiplyPadic,divideByInteger,finiteRingModule,verifyFiniteRingModule,determinantPadic,derivedReductionFixture,crystallinePrism,validatePrismBase} from '../padic.mjs';
import {p1Complex,p1Retraction,p1Frobenius,p1Model,pointModel,verifyModel,checkComplex,checkChainMap,checkRetraction,weightContraction,verifyWeightContraction,filtration,reduceFreeComplex} from '../complex.mjs';
import {integerModel,classifyReduction,countElliptic,countProjectiveLine,localFactorBundle,verifyTowerReduction} from '../local-factors.mjs';

const D0=[[0,1,0,0],[0,0,0,1],[0,0,0,1],[-1,0,1,0],[0,-1,0,0]];
const D1=[[0,-1,1,0,0],[0,0,0,0,0],[-1,0,0,0,-1]];
const bigRows=a=>a.map(r=>r.map(BigInt));

test('P1-01/02: exact interval counts including one million match an independent linear sieve',async()=>{
  for(const[b,count]of[[10,4],[100,25],[1000,168],[1000000,78498]]){const r=await segmentedPrimes({a:'2',b:String(b),segmentSize:65536},{maxMillis:60000});assert.equal(r.primes.length,count);assert.deepEqual(r.primes,linearPrimeOracle(b));assert.equal(Object.hasOwn(r,'allPrimesComputed'),false);}
});
test('P1-02: 0/1, square boundaries and reversed intervals',async()=>{assert.deepEqual((await segmentedPrimes({a:0,b:2})).primes,['2']);assert.deepEqual((await segmentedPrimes({a:49,b:43})).primes,['43','47']);assert.equal((await runJob({kind:'arithmetic.primes',input:{a:0,b:1}})).results.intervalCount.value,'0');assert.equal(isqrt(999999999999999999999999n),999999999999n);});
test('P1-03: 17 uneven partitions equal one complete interval; omissions and duplication fail',async()=>{
  const cuts=[2,3,100,999,1000,7919,20000,65535,65536,70000,123457,250001,400000,500003,700001,800003,999983,1000001],segments=[];
  for(let i=0;i<17;i++)segments.push(...(await segmentedPrimes({a:cuts[i],b:cuts[i+1]-1})).segments);
  const v=await verifyPrimeSegments(segments,2,1000000);assert.equal(v.pass,true);assert.equal(v.count,78498);
  assert.equal((await verifyPrimeSegments(segments.slice(1),2,1000000)).pass,false);
  assert.equal((await verifyPrimeSegments([segments[0],...segments],2,1000000)).pass,false);
});
test('P1-03: cancellation commits only completed segments and exact resume agrees',async()=>{
  let saved=null,cancel=false;await assert.rejects(segmentedPrimes({a:2,b:1000,segmentSize:111},{},{isCancelled:()=>cancel,onCheckpoint:cp=>{saved=cp;if(cp.segments.length===2)cancel=true;}}),e=>e.code==='CANCELLED');assert.equal(saved.segments.length,2);
  const resumed=await segmentedPrimes({a:2,b:1000,segmentSize:111,checkpoint:saved});assert.deepEqual(resumed.primes,linearPrimeOracle(1000));
  const changed=clone(saved);changed.segments[0].primes.shift();await assert.rejects(segmentedPrimes({a:2,b:1000,checkpoint:changed}),e=>e.code==='CHECKPOINT_INVALID');
});
test('P1-03: lazy stream computes one tile before the consumer asks for the next',async()=>{let count=0;const it=streamInterval({a:2,b:1000000,segmentSize:100},{},{onCheckpoint:()=>{count++;}});const first=await it.next();assert.equal(count,1);assert.equal(first.value.b,'101');await it.return();assert.equal(count,1);});
test('P1-04: psi(10.5) is the exact logarithmic combination of 2520',async()=>{const r=await segmentedPrimes({a:2,b:11});const s=primeStatistics(r,{statisticsAt:'10.5'});assert.deepEqual(s.psi.terms,[{prime:'2',weight:3},{prime:'3',weight:2},{prime:'5',weight:1},{prime:'7',weight:1}]);assert.equal(s.pi.value,'4');assert.equal(s.Li2.value.certified,false);assert.equal(s.psi.ball.certified,true);await writeFile(new URL('../evidence/psi-fixture.json',import.meta.url),JSON.stringify(s,null,2));});
test('P1-04: exact prime-power boundaries add one log weight',async()=>{const r=await segmentedPrimes({a:2,b:17});const s=x=>primeStatistics(r,{statisticsAt:String(x)}).psi.terms.find(t=>t.prime==='2').weight;assert.equal(s('7.999'),2);assert.equal(s(8),3);assert.equal(s(16),4);});
test('P1-05: Carmichael/pseudoprime controls are not certified',()=>{for(const n of[341,561,1105])assert.equal(generatePrimeCertificate(n).status,'COMPOSITE');assert.equal(verifyPrimeCertificate({scheme:'MILLER_RABIN',n:'561',probable:true}).status,'UNKNOWN');});
test('P1-05: exact BigInt certificate, recursive mutation rejection and next-prime scope',()=>{const r=generatePrimeCertificate('18446744069414584321');assert.equal(r.status,'PRIME_CERTIFIED');assert.equal(verifyPrimeCertificate(r.certificate).pass,true);const bad=clone(r.certificate);bad.factors[0].exponent++;assert.equal(verifyPrimeCertificate(bad).pass,false);assert.equal(nextPrime(97).n,'101');assert.throws(()=>generatePrimeCertificate(9007199254740993),e=>e.code==='INVALID_EXACT_INTEGER');});
test('P1-06: prime indices never mix and nonminimal discriminant does not prove bad reduction',()=>{assert.throws(()=>addPadic(padic(5,1,3),padic(7,1,3)),e=>e.code==='PADIC_BASE_MISMATCH');assert.equal(classifyReduction(integerModel({model:'elliptic',a:'-81',b:0}),3).status,'MINIMIZATION_REQUIRED');assert.equal(classifyReduction(integerModel({model:'elliptic'}),2).curveGoodReduction,false);});
test('P1-07: good-only finite local data cannot claim a complete global L function',async()=>{const r=await localFactorBundle({model:'elliptic',primes:[3,5,7]},{levels:[1,2]});assert.equal(r.globalBundle.status,'INCOMPLETE_LOCAL_DATA');assert.equal(r.globalBundle.isCompleteGlobalLFunction,false);assert.equal(r.globalBundle.archimedean.conductor,'UNKNOWN');const withBad=await localFactorBundle({model:'elliptic',primes:[2,3]});assert.deepEqual(withBad.coverage.unresolvedFinitePlaces,['2']);});
test('P1-08: camera and LOD preserve raw hash and exact count',async()=>{const r=await segmentedPrimes({a:2,b:1000});const a=primeView(r,{maxPoints:5,camera:{yaw:2}}),b=primeView(r,{maxPoints:20000,camera:{yaw:0}});assert.equal(a.sourceHash,b.sourceHash);assert.deepEqual(a.intervalCount,b.intervalCount);assert(a.points.length<b.points.length);assert.equal(a.representation.proofClaim,null);});
test('P2-01: finite observation cannot be admitted as the symbolic prism',()=>{const p=crystallinePrism(3);assert.equal(validatePrismBase(p).pass,true);const bad={...p,kind:'FINITE_P_POWER_RING',finiteObservationIsPrism:true};assert.equal(validatePrismBase(bad).pass,false);});
test('P2-02/I1-03: delta guard digit auto-upgrade only from consistent exact source',()=>{assert.throws(()=>deltaPadic(padic(3,17,4),4),e=>e.code==='PRECISION_REQUIRED');const good=deltaPadic(padic(3,17,4),4,{exactInteger:17});assert.equal(good.precision.autoIncreasedFromExactSource,true);assert.equal(good.value.residue,mod((17n-17n**3n)/3n,81n).toString());assert.throws(()=>deltaPadic(padic(3,17,4),4,{exactInteger:18}),e=>e.code==='EXACT_SOURCE_MISMATCH');assert.notEqual(...precisionFailureFixture(3,3).deltaAtN.map(x=>x.residue));});
test('P2-02: all lifts of small residues obey reported delta precision',()=>{for(const p of[2,3,5])for(const N of[1,2,3]){const M=BigInt(p)**BigInt(N+1);for(let r=0n;r<M&&r<150n;r++){const v=deltaPadic(padic(p,r,N+1),N).value.residue;const exact=(r-r**BigInt(p))/BigInt(p);assert.equal(v,mod(exact,BigInt(p)**BigInt(N)).toString());const lift=r+M;assert.equal(v,mod((lift-lift**BigInt(p))/BigInt(p),BigInt(p)**BigInt(N)).toString());}}});
test('P2-03: finite ring module has torsion and rejects nonunit inversion',()=>{const r=finiteRingModule(matrix(1,1,[[0,0,3]]),3,3);assert.deepEqual(r.module.kernel.cyclic,[{kind:'CYCLIC_P_POWER_MODULE',p:'3',exponent:1}]);assert.deepEqual(r.module.cokernel.cyclic,r.module.kernel.cyclic);assert.equal(r.module.fieldRank,null);assert.throws(()=>inverseUnit(3n,27n),e=>e.code==='NONUNIT_DIVISION');});
test('P2-03: DVR Smith modules agree with exhaustive kernel/image enumeration',()=>{for(const p of[2,3])for(let seed=0;seed<12;seed++){const N=p===2?3:2,q=p**N,A=matrix(2,2,[[0,0,seed+1],[0,1,2*seed+3],[1,0,seed*seed],[1,1,seed+2]]),r=finiteRingModule(A,p,N),rows=dense(A);let ker=0;const image=new Set();for(let x=0;x<q;x++)for(let y=0;y<q;y++){const out=rows.map(row=>Number(mod(row[0]*BigInt(x)+row[1]*BigInt(y),BigInt(q))));if(out.every(x=>x===0))ker++;image.add(out.join(','));}const v=r.certificate.valuations,sum=v.reduce((a,b)=>a+b,0);assert.equal(ker,p**(sum+N*(2-v.length)));assert.equal(image.size,p**v.reduce((s,x)=>s+N-x,0));assert.equal(q*q/image.size,p**(sum+N*(2-v.length)));}});
test('P2-03: a forged change of basis fails its independent verifier',()=>{const r=finiteRingModule(matrix(2,2,[[0,0,3],[0,1,1],[1,1,3]]),3,3);const c=clone(r.certificate);c.U.entries[0][2]=String(BigInt(c.U.entries[0][2])+1n);assert.equal(verifyFiniteRingModule(c).pass,false);});
test('P2-03: zero-dimensional free modules retain rectangular shape',()=>{const a=finiteRingModule(matrix(0,5),3,3),b=finiteRingModule(matrix(4,0),3,3);assert.equal(a.module.kernel.freeRank,5);assert.equal(a.certificate.diagonal.cols,5);assert.equal(b.module.cokernel.freeRank,4);assert.equal(b.certificate.diagonal.rows,4);});
test('P2-04/P3-03: golden integer matrices exactly match the blueprint',()=>{const C=p1Complex(1);assert.deepEqual(dense(C.differentials[0]),bigRows(D0));assert.deepEqual(dense(C.differentials[1]),bigRows(D1));assert.equal(checkComplex(C).pass,true);const bad=clone(C);bad.differentials[1].entries[0][2]='2';assert.equal(checkComplex(bad).pass,false);});
test('P2-04: vacuous d-squared checks still validate every dimension and coefficient',()=>{for(const C of[{dims:[-1],differentials:[]},{dims:[1,1],differentials:[{rows:1,cols:1,entries:[[2,0,'1']]}]},{dims:[1,1],differentials:[{rows:1,cols:1,entries:[[0,0,'NaN']]}]},{dims:[1,1],differentials:[{rows:1,cols:1}]}])assert.equal(checkComplex(C).pass,false);assert.equal(checkComplex({dims:[1],differentials:[]}).pass,true);});
test('P2-04/P3-04: every sampled signed weight including p-divisible weights contracts',()=>{for(let k=-100;k<=100;k++)if(k)assert.equal(verifyWeightContraction(weightContraction(k)).pass,true);const bad=weightContraction(3);bad.h1.entries[0][2]='1';assert.equal(verifyWeightContraction(bad).pass,false);});
test('P2-05: reject incorrect Frobenius cutoff and asymmetric crop',()=>{const C=p1Complex(1);assert.throws(()=>p1Frobenius(C,3,{targetD:1}),e=>e.code==='FROBENIUS_TARGET_MISMATCH');const F=p1Frobenius(C,3),bad=clone(F.maps);bad[1].entries=bad[1].entries.filter(([,c])=>c!==0);assert.equal(checkChainMap(C,F.target,bad).pass,false);});
test('P2-06: derived reduction retains degree-zero Tor',()=>{const r=derivedReductionFixture(3,3);assert.equal(r.source.cohomology.H0,'0');assert.equal(r.derivedBaseChange.cohomology.H0,'F_3');assert.equal(r.derivedBaseChange.cohomology.H1,'F_3');assert.equal(r.ordinaryCohomologyTensor.H0,'0');});
test('P2-06: generic bounded-free derived base change verifies its source and ring map',()=>{const C={dims:[1,1],coefficientRing:{kind:'INTEGER_RING'},differentials:[matrix(1,1,[[0,0,3]])]},r=reduceFreeComplex(C,3,1);assert.deepEqual(r.result.differentials[0].entries,[]);assert(r.checks.every(c=>c.pass));assert.throws(()=>reduceFreeComplex(r.result,5,1),e=>e.code==='PADIC_BASE_MISMATCH');assert.throws(()=>reduceFreeComplex(r.result,3,2),e=>e.code==='PRECISION_REQUIRED');});
test('P2-07: degree, Hodge, smart and quotient truncations have distinct contracts',()=>{const C=p1Complex(2),st=filtration(C,{kind:'stupid',r:1}),ho=filtration(C,{kind:'hodge',r:1}),smart=filtration(C,{kind:'smart_below',r:1}),quot=filtration(C,{kind:'quotient_below',r:1});assert.deepEqual(st.dims,[0,9,5]);assert.deepEqual(ho.dims,[0,4,5]);assert.equal(checkComplex(smart).pass,true);assert.equal(quot.subcomplex,false);assert.throws(()=>filtration(C,{kind:'naive_below',r:1}),e=>e.code==='NOT_SUBCOMPLEX');assert.equal(filtration(C,{kind:'nygaard'}).status,'UNSUPPORTED');assert.equal(st.cohomologyDimensions,null);});
test('P2-08: source model replay rejects altered bases, coefficient rings and observations',async()=>{const r=await p1Model({p:3,N:4,D:1});assert.equal((await verifyModel(r)).pass,true);for(const mutate of[r=>{r.complex.basis[0][0].id='fake';},r=>{r.finiteObservation.coefficientRing.p='5';},r=>{r.smith.cohomology.H2.freeRank=2;},r=>{r.frobenius.transported[2].entries[0][2]='5';}]){const bad=clone(r);mutate(bad);assert.equal((await verifyModel(bad)).pass,false);}});
test('P3-01: point fixtures for p=2,3,5,7 and N=1,2,4,8',async()=>{for(const p of[2,3,5,7])for(const N of[1,2,4,8]){const r=await pointModel({p,N});assert.equal(r.finiteObservation.ring.modulus,String(BigInt(p)**BigInt(N)));assert.equal(r.cohomology[0].freeRank,1);assert.equal((await verifyModel(r)).pass,true);}});
test('P3-02/03: arbitrary D dimensions and integral strong deformation retract',()=>{for(const D of[1,2,5,12,32]){const C=p1Complex(D);assert.deepEqual(C.dims,[2*D+2,4*D+1,2*D+1]);assert.equal(checkRetraction(C,p1Retraction(C)).pass,true);for(let k=0;k<3;k++)for(const b of C.basis[k])assert.equal(b.cechDegree+b.formDegree,k);}});
test('P3-05: p-adic reductions commute and preserve the integral retract',async()=>{for(const p of[2,3,5,7])for(const N of[1,2,4,8]){const r=await p1Model({p,N,D:1});assert(r.checks.every(c=>c.pass));assert.deepEqual(r.smith.d0.nonzeroInvariantFactors,['1','1','1']);assert.deepEqual(r.smith.d1.nonzeroInvariantFactors,['1','1']);}assert(verifyTowerReduction(3,[-9007199254740993n,0n,17n],8,2).every(x=>x.pass));});
test('P3-06: Frobenius is transported to (1,p), not inferred from a plot',()=>{for(const p of[2,3,5,7])for(const D of[1,2,5]){const C=p1Complex(D),F=p1Frobenius(C,p);assert.equal(F.target.D,p*D);assert.equal(F.verification.pass,true);assert.deepEqual(dense(F.transported[0]),[[1n]]);assert.deepEqual(dense(F.transported[2]),[[BigInt(p)]]);}});
test('P3-07/08: comparison assumptions and type boundaries cannot be relabelled',async()=>{const r=await p1Model();for(const mutate of[r=>{r.completedWeightCertificate=null;},r=>{r.object.kind='CW_TOY';},r=>{r.comparison.geometry.proper=false;},r=>{r.comparison.multiplicativeCertification='E_INFINITY_FORMAL';},r=>{r.formalComplete=true;}]){const bad=clone(r);mutate(bad);assert.equal((await verifyModel(bad)).pass,false);}assert(r.comparison.arrows.filter(x=>x.source).every(x=>x.status==='THEOREM_REFERENCE'&&x.leanImport===null));});
test('I1-03: determinant, basis reduction, division and Frobenius have distinct losses',()=>{const A=matrix(2,2,[[0,0,3],[0,1,4],[1,0,5],[1,1,7]]),B=matrix(2,2,[[0,0,3+81],[0,1,4],[1,0,5],[1,1,7]]);assert.equal(determinantPadic(A,3,4).value.residue,determinantPadic(B,3,4).value.residue);assert.equal(determinantPadic(A,3,4).precision.lossDigits,0);assert.equal(finiteRingModule(A,3,4).precision.lossDigits,0);assert.equal(divideByInteger(padic(3,54,5),9,3).precision.lossDigits,2);assert.throws(()=>divideByInteger(padic(3,54,4),9,3),e=>e.code==='PRECISION_REQUIRED');assert.equal(p1Frobenius(p1Complex(1),3).precision.lossDigits,0);});
test('I1-07: projective orbit point counts independently match Frobenius trace',()=>{for(const p of[2,3,5,7,11,13]){const C=p1Frobenius(p1Complex(1),p),trace=C.transported[0].entries[0][2];assert.equal(trace,'1');const q=countProjectiveLine(p);assert.equal(q.pass,true);assert.equal(q.count,String(p+1));}});
test('I1-07: elliptic counts use both full pairs and residue multiplicities',()=>{const E=integerModel({model:'elliptic'});for(const[p,n,a]of[[3,4,0],[5,8,-2],[7,8,0],[11,12,0],[13,8,6],[17,16,2]]){const r=countElliptic(E,p);assert.equal(r.count,String(n));assert.equal(r.aP,String(a));assert(r.checks.every(c=>c.pass));}});
test('API: malformed requests, resource budgets and unsupported arithmetic reject explicitly',async()=>{assert.equal(validateRequest({kind:'arithmetic.fake'}).ok,false);assert.equal(validateRequest({kind:'arithmetic.primes',input:{allPrimesComputed:true}}).ok,false);await assert.rejects(runJob({kind:'arithmetic.primes',input:{a:2,b:1000},budget:{maxOperations:1}}),e=>e.code==='RESOURCE_LIMIT');await assert.rejects(runJob({kind:'arithmetic.primes',input:{a:'9007199254740993',b:'9007199254740999'}}),e=>e.code==='RESOURCE_LIMIT');await assert.rejects(runJob({kind:'arithmetic.p1',input:{p:4}}),e=>e.code==='INVALID_PRIME');assert.equal(getCapabilities().formalComplete,false);});
test('API: every shipped example is serializable, deterministic and has explicit 3D meaning',async()=>{for(const e of getExamples()){const r=await runJob(e.request);assert.equal(r.status,'COMPLETED');assert.doesNotThrow(()=>JSON.stringify(r));assert(r.visualization.coordinateMeaning);assert.equal(r.evidence.formalComplete,false);const {resultHash,...payload}=r;assert.equal(await hash(payload),resultHash);}const e=getExamples().find(e=>e.id==='p1-p3');assert.equal(canonical(await runJob(e.request)),canonical(await runJob(e.request)));});

test('Export independent algebra fixtures without rendered coordinates',async()=>{const fixtures={complexes:[1,2,5].map(D=>{const C=p1Complex(D),R=p1Retraction(C);return{D,complex:C,retraction:R,frobenius:[2,3,5,7].map(p=>({p,...p1Frobenius(C,p)}))};}),largePrime:'18446744069414584321'};await writeFile(new URL('../evidence/independent-fixtures.json',import.meta.url),JSON.stringify(fixtures));});
