"""Extract accepted actual-core values; never regenerate or edit the original receipt."""
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parents[3]
M1 = ROOT / 'mathscope-m1/navier'
OUT = Path(__file__).resolve().parents[1]
ASSEMBLY = M1 / 'followup-20261010-symbolic-gluing/attempts/one-profile-0002/receipt.json'
ASSEMBLY_SHA = '184152e17553d825f1f590b611b575f646d182e3d891aa010e6a3f5cbb201afd'
CORE_SHA = '8f65d85d903df534c2c10501119fbcef636678c95ec214e165041681d16fb5a5'

def pinned(path, expected):
    raw = path.read_bytes()
    actual = hashlib.sha256(raw).hexdigest()
    if actual != expected:
        raise SystemExit(f'Immutable source mismatch: {path}')
    return json.loads(raw), {'path': str(path.relative_to(ROOT)), 'sha256': actual, 'bytes': len(raw)}

assembly, assembly_pin = pinned(ASSEMBLY, ASSEMBLY_SHA)
entry = assembly['acceptedEvidence']['core']
if entry['sha256'] != CORE_SHA:
    raise SystemExit('The accepted assembly selects a different core receipt.')
core, core_pin = pinned(M1 / entry['path'], CORE_SHA)
if core['passed'] != core['total'] or not core['claimBoundary']['actualInfiniteCoreEvaluationsEnclosed']:
    raise SystemExit('The source receipt did not accept actual infinite-core intervals.')
rows = []
for i, row in enumerate(core['evaluations']):
    rows.append({
        'sourceIndex': i,
        **{k: row[k] for k in ['quantity', 'eta', 'Y', 'radialDerivativeOrder', 'sameInfiniteCoreInterval', 'decimalDisplayOnly']},
        'sourceAnalyticErrorPositive': row['positiveAnalyticErrorUpper'] != '0',
        'analyticErrorIncluded': True,
        'sourcePath': f"{core_pin['path']}#/evaluations/{i}/sameInfiniteCoreInterval",
    })
data = {
    'schema': 'MathScope.PinnedActualN3CoreObservations/1',
    'profileId': 'same-profile-2026-10-10.3',
    'assembly': assembly_pin,
    'acceptedCore': core_pin,
    'acceptedEvidenceEntry': entry,
    'parameterExpressionSHA256': assembly['parameterExpressionSHA256'],
    'profileEvidenceSHA256': assembly['profileEvidenceSHA256'],
    'sourceInputs': core['source'],
    'sourceArithmetic': core['arithmetic'],
    'sourceClaimBoundary': core['claimBoundary'],
    'domain': {'etaExact': '0', 'sourceY': ['0', '1', '2', '4', '41/10'], 'sourceYDefinition': 'Y=Lambda*X', 'continuousCoreBoundDomain': 'eta=0, 0<=Y<=41/10', 'sampledYOnly': True, 'radialDerivativeOrders': [0, 1, 2]},
    'rows': rows,
    'wholeProfileFieldEvaluator': False,
    'sourceFilesModified': False,
    'newLeanExecution': False,
}
text = '// Generated by tests/build-source-core-binding.py from immutable, SHA-verified accepted receipts.\n'
text += 'export const PINNED_CORE = '+json.dumps(data, ensure_ascii=False, separators=(',', ':'))+';\n'
(OUT / 'source-core-data.mjs').write_text(text)
print(json.dumps({'output': 'source-core-data.mjs', 'rows': len(rows), 'assembly': assembly_pin, 'core': core_pin, 'outputSHA256': hashlib.sha256(text.encode()).hexdigest()}, ensure_ascii=False, indent=2))
