"""Read-only extraction of the final accepted N3 identity for the additive M2 code."""
from pathlib import Path
import json, hashlib

ROOT = Path(__file__).resolve().parents[3]
M1 = ROOT / 'mathscope-m1/navier'
OUT = Path(__file__).resolve().parents[1]
FILES = {
    'assessment': M1 / 'followup-20261010-final-stress-audit/ORIGINAL_NINE_GATES_ASSESSMENT_2026_10_10_3.json',
    'assembly': M1 / 'followup-20261010-symbolic-gluing/attempts/one-profile-0002/receipt.json',
    'formalConnectionReview': M1 / 'followup-20261010-final-stress-audit/FINAL_FORMAL_CONNECTION_REVIEW_2026_10_10_EN.md',
    'specification': M1 / 'followup-20261010-symbolic-gluing/ONE_PROFILE_SPECIFICATION.md',
    'sourceEnvelope': M1 / 'followup-20261010-same-datum-axis/global-source-envelope-certificate.json',
    'activationRectangle': M1 / 'followup-20261010-final-stress-audit/ACTIVATION_COLLAR_BOUNDS_EN.md',
}
EXPECTED = {
    'assessment': 'e57681b7bb751967b406ad440942728ecfd8fe47eb9672129ff19c8a7eb6634c',
    'assembly': '184152e17553d825f1f590b611b575f646d182e3d891aa010e6a3f5cbb201afd',
    'sourceEnvelope': 'bf9ca2766ad0ec90aa055becccc07b7ad882c71928e51c71529543c9d94efb4f',
}
inputs = {}
for key, path in FILES.items():
    raw = path.read_bytes(); digest = hashlib.sha256(raw).hexdigest()
    if key in EXPECTED and digest != EXPECTED[key]:
        raise SystemExit(f'{key}: original source digest mismatch')
    inputs[key] = {'path': str(path.relative_to(ROOT)), 'sha256': digest, 'bytes': len(raw)}
assessment = json.loads(FILES['assessment'].read_text())
assembly = json.loads(FILES['assembly'].read_text())
def normalize(value):
    if isinstance(value, bool): return value
    if isinstance(value, int): return str(value) if abs(value)>2**53-1 else value
    if isinstance(value, list): return [normalize(v) for v in value]
    if isinstance(value, dict): return {k:normalize(v) for k,v in value.items()}
    return value
data = {
    'schema': 'MathScope.PinnedN3SourceProfile/1',
    'id': 'same-profile-2026-10-10.3',
    'sourcePaperSHA256': assembly['sourcePaperSHA256'],
    'originalLeanCommit': 'f9e8bc5b38b6e212696e8a30e3e91517af887bbd',
    'parameterExpressionSHA256': assembly['parameterExpressionSHA256'],
    'profileEvidenceSHA256': assembly['profileEvidenceSHA256'],
    'inputs': inputs,
    'parametersExactExpressions': normalize(assembly['parametersExactExpressions']),
    'n3AcceptedGates': [{'id':r['id'],'status':r['currentStatus'],'evidenceLevel':r['evidenceLevel']} for r in assessment['gates'] if r['id'].startswith('N3')],
    'attachedAnalyticConclusions': assembly['attachedAnalyticConclusions'],
    'finiteEvaluations': assembly['finiteEvaluations'],
    'largeIntegerEncoding': 'Original integer tokens are preserved as decimal strings when outside the safe JSON integer range.',
    'globalNumericalEvaluator': False,
    'newLeanExecution': False,
    'm2HigherCoefficientsInArchive': False,
}
text = '// Generated by tests/build-source-binding.py from immutable, byte-verified N3 artifacts.\n'
text += 'export const PINNED_N3 = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n'
(OUT/'source-profile-data.mjs').write_text(text)
print(json.dumps({'inputs':inputs,'outputSHA256':hashlib.sha256(text.encode()).hexdigest()},ensure_ascii=False,indent=2))
