import test from 'node:test';import assert from 'node:assert/strict';
import {SourceBoundScene} from '../../visualization/renderer.mjs';
import {makeVisualization} from '../../visualization/observations.mjs';
const fakeGL=()=>{const state={lost:false,draws:[],uploads:[]},constants={VERTEX_SHADER:1,FRAGMENT_SHADER:2,COMPILE_STATUS:3,LINK_STATUS:4,ARRAY_BUFFER:5,DYNAMIC_DRAW:6,FLOAT:7,BLEND:8,ONE:9,ONE_MINUS_SRC_ALPHA:10,DEPTH_TEST:11,POINTS:12,COLOR_BUFFER_BIT:13,NO_ERROR:0};const gl=new Proxy({...constants,state,isContextLost:()=>state.lost,createShader:()=>({}),createProgram:()=>({}),createBuffer:()=>({}),getShaderParameter:()=>true,getProgramParameter:()=>true,getAttribLocation:(_,name)=>({a_position:0,a_radius:1,a_color:2}[name]),getUniformLocation:(_,name)=>name,getError:()=>0,bufferData:(_,a)=>state.uploads.push(Array.from(a)),drawArrays:(...a)=>state.draws.push(a)},{get:(o,k)=>k in o?o[k]:()=>{}});return gl;};
const fakeCanvas=gl=>{const calls=[],ctx=new Proxy({},{get:(_,name)=>(...args)=>{calls.push([name,...args]);},set:()=>true});const offscreen={width:0,height:0,getContext:()=>gl,addEventListener(){}};return {calls,dataset:{},ownerDocument:{createElement:()=>offscreen},getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:700,height:420}),setAttribute(){},addEventListener(){},hasPointerCapture:()=>false};};
test('accelerated and fallback routes use the same retained observation and exact selected value',()=>{
  globalThis.ResizeObserver=class{observe(){}disconnect(){}};globalThis.devicePixelRatio=1;
  const gl=fakeGL(),canvas=fakeCanvas(gl),scene=new SourceBoundScene(canvas),job={id:'renderer-branch-audit',status:'COMPLETED',inputHash:'source-input',resultHash:'source-result',request:{kind:'gauge.field',input:{}},result:{status:'COMPLETED',sourceHash:'source-observation',visualization:{points:[{pos:[.1,.2,.3],value:'9007199254740993123',label:'exact retained integer'},{pos:[1,1,1],value:'7'}],lines:[],arrows:[],axes:['x','y','z']}}};
  const view=makeVisualization(job),before=JSON.stringify(view);scene.setVisualization(view);scene.setRenderMode('CPU');const cpu=scene.projected.map(p=>({pos:p.pos,xy:p.xy,value:p.value,sourcePath:p.sourcePath}));canvas.calls.length=0;scene.setRenderMode('WEBGL');
  assert.equal(scene.getMetrics().renderer,'WEBGL_POINTS_WITH_CANVAS_AXES');assert.equal(gl.state.draws.at(-1)[2],2);assert.equal(canvas.calls.filter(c=>c[0]==='arc').length,0,'bulk marks do not also use CPU arc');assert.equal(canvas.calls.filter(c=>c[0]==='drawImage').length,1);const accelerated=scene.projected.map(p=>({pos:p.pos,xy:p.xy,value:p.value,sourcePath:p.sourcePath}));assert.deepEqual(accelerated,cpu);let p=scene.projected.find(p=>p.value==='9007199254740993123');scene.pick({clientX:p.xy[0],clientY:p.xy[1]});assert.equal(scene.lastPicked.value,'9007199254740993123');
  gl.state.lost=true;scene.draw();assert.match(scene.getMetrics().renderer,/CPU_CANVAS2D/);assert.deepEqual(scene.projected.map(p=>({pos:p.pos,xy:p.xy,value:p.value,sourcePath:p.sourcePath})),cpu);p=scene.projected.find(p=>p.value==='9007199254740993123');scene.pick({clientX:p.xy[0],clientY:p.xy[1]});assert.equal(scene.lastPicked.value,'9007199254740993123');assert.equal(JSON.stringify(view),before);scene.destroy();
});
