/** Finite compact-group Wilson Gibbs samplers. No continuum/quantum gap claim. */
import * as M from '../../mathscope-m1/gauge/matrix.mjs';
import {createGroup,groupElementResidual} from '../../mathscope-m1/gauge/groups.mjs';
import {sha256} from '../../mathscope-m0/contracts.mjs';
import {REVISION,check,rngFromSeed,latticeEstimate,assertBudget,yieldToRuntime} from './contracts.mjs';
import {haarSU2,randomExponential,createConfiguration,modelDescriptor,descriptor,plaquetteTerm,action,measure,configurationHash,serializeLinks,visualizeLattice,gaugeDiagnostics} from './lattice.mjs';
import {analyzeSeries,compareReplicas,topologyMobility,diagnoseEnsemble} from './statistics.mjs';
import {reflectionAudit} from './reflection.mjs';
import {su2Reference} from './enclosures.mjs';

export function metropolisProbability(delta){check(Number.isFinite(delta),'FAILED','A nonfinite action difference cannot be accepted.');return delta<=0?1:Math.exp(-delta);}
export function createActionCache(configuration){const terms=configuration.geometry.plaquettes.map(p=>plaquetteTerm(configuration,p));return {terms,action:terms.reduce((a,b)=>a+b,0)};}
export function proposeLink(configuration,cache,id,candidate,logUniform){
  const indices=configuration.geometry.affectedByLink[id],old=configuration.links[id],oldLocal=indices.reduce((s,p)=>s+cache.terms[p],0);configuration.links[id]=candidate;
  const newTerms=indices.map(p=>plaquetteTerm(configuration,configuration.geometry.plaquettes[p])),newLocal=newTerms.reduce((a,b)=>a+b,0),delta=newLocal-oldLocal;
  check(Number.isFinite(delta)&&Number.isFinite(logUniform)&&logUniform<=0,'FAILED','Metropolis input left the finite numerical domain.');
  const logAcceptance=Math.min(0,-delta),accepted=logUniform<logAcceptance;
  if(accepted){for(let k=0;k<indices.length;k++)cache.terms[indices[k]]=newTerms[k];cache.action+=delta;}else configuration.links[id]=old;
  return {id,oldLocalAction:oldLocal,newLocalAction:newLocal,deltaAction:delta,logAcceptance,logUniform,acceptanceProbability:metropolisProbability(delta),accepted};
}
function samplerContract(settings,group){return {revision:REVISION,algorithm:settings.algorithm,scan:settings.scan,updatesPerSweep:'one uniformly selected link per update, with replacement; active-link count updates form one reported sweep',proposal:settings.algorithm==='SU2_HAAR_METROPOLIS'?{measure:'Normalized Haar measure on full SU(2)',construction:'Four independent Box–Muller standard normals, normalized to S³, mapped to a unitary determinant-one 2×2 matrix.',symmetry:'Q and Q⁻¹ have the same Haar law; U′=Q U is an independence-Haar proposal relative to Haar measure.'}:{measure:'Pushforward of a symmetric full-dimensional coefficient box by Lie exponential',construction:`All ${group.dimension} actual compact-basis directions have independent symmetric coefficients in [-stepSize/sqrt(dim g), stepSize/sqrt(dim g)].`,symmetry:'X and -X have the same law, so exp(X) and exp(X)⁻¹ have the same proposal law. No Euclidean-density/Haar-density identification is used.'},acceptance:'min(1, exp(-(S(U′)-S(U)))) with the full affected-plaquette action difference',detailedBalanceDerivation:'Haar invariance and inversion-symmetric increments give a symmetric link proposal. e^-S(U) min(1,e^-(S(V)-S(U)))=min(e^-S(U),e^-S(V)); uniform random link selection preserves this identity.',allTangentDirections:settings.algorithm==='SU2_HAAR_METROPOLIS'?'Full S³ support':group.dimension,ergodicityScope:'The ideal full-group Haar or full-dimensional local proposal has the required support on these connected groups. No quantitative mixing-time or topological-sector exploration certificate is inferred from finite Float64 trajectories.',rng:'M1 xorshift32 with FNV-1a UTF-16 seed; rejection-based integer selection; Box–Muller normals. Finite PRNG simulation approximates ideal continuous randomness.',projectionAfterUpdate:'NONE; links are never silently reunitarized',flow:null};}
export async function runReplica(input,start,replicaIndex,modelHash,context={}){
  const settings=input.sampler,replicaSeed=`${settings.seed}:replica:${replicaIndex}:${start}`,initial={kind:start==='COLD'?'IDENTITY':start==='HOT_HAAR'?'HOT_HAAR':'SEEDED_EXPONENTIAL',seed:replicaSeed+':initial'},configuration=await createConfiguration({...input,initial},context),rng=rngFromSeed(replicaSeed+':updates'),cache=createActionCache(configuration),history=[],samples=[],acceptanceAudit=[];
  const totalSweeps=settings.burnIn+settings.samples*settings.thin;let totalAccepted=0,totalProposed=0,maxActionCacheDrift=0;
  for(let sweep=1;sweep<=totalSweeps;sweep++){
    context.checkCancelled?.();let accepted=0;
    for(let update=0;update<configuration.geometry.active.length;update++){
      if(update%16===0)context.checkCancelled?.();const edge=configuration.geometry.active[rng.integer(configuration.geometry.active.length)],increment=settings.algorithm==='SU2_HAAR_METROPOLIS'?haarSU2(rng):randomExponential(configuration.group,rng,settings.stepSize),candidate=M.multiply(increment,configuration.links[edge.id]),step=proposeLink(configuration,cache,edge.id,candidate,Math.log(rng.open()));
      accepted+=+step.accepted;if(acceptanceAudit.length<12)acceptanceAudit.push({sweep,update,...step});
    }
    totalAccepted+=accepted;totalProposed+=configuration.geometry.active.length;
    const measured=measure(configuration,input.measurement,{includeSites:false,topology:true}),drift=Math.abs(measured.action-cache.action)/Math.max(1,Math.abs(measured.action));maxActionCacheDrift=Math.max(maxActionCacheDrift,drift);check(drift<=1e-9,'FAILED','Cached local Metropolis action no longer agrees with the independently recomputed full action.');
    const row={sweep,phase:sweep<=settings.burnIn?'BURN_IN':'MEASUREMENT',accepted,proposed:configuration.geometry.active.length,acceptance:accepted/configuration.geometry.active.length,action:measured.action,meanPlaquette:measured.meanPlaquette,meanPolyakovReal:measured.meanPolyakovReal,topologyEstimate:measured.topology.rawCharge};history.push(row);
    if(sweep>settings.burnIn&&(sweep-settings.burnIn)%settings.thin===0)samples.push({...row,index:samples.length,configurationHash:await configurationHash(configuration,modelHash)});
    if(sweep%4===0)await yieldToRuntime(context,{phase:'wilson-ensemble',replica:replicaIndex,start,sweep,totalSweeps,retainedSamples:samples.length,acceptance:totalAccepted/totalProposed});
  }
  const options={maxLag:settings.maxLag,minimumESS:settings.minimumESS},statistics={action:analyzeSeries(samples.map(s=>s.action),{...options,allowConstant:input.beta===0}),plaquette:analyzeSeries(samples.map(s=>s.meanPlaquette),options)};
  const topology=samples.map(s=>s.topologyEstimate);if(topology.every(Number.isFinite))statistics.topology=analyzeSeries(topology,options);
  const loops=samples.map(s=>s.meanPolyakovReal);if(loops.every(Number.isFinite))statistics.polyakov=analyzeSeries(loops,options);
  let membership=0;for(const u of configuration.links)if(u)membership=Math.max(membership,groupElementResidual(configuration.group,u).max);check(membership<=1e-9,'FAILED','Accumulated updates no longer satisfy the actual compact-group constraints.');
  const topologyRange=topology.every(Number.isFinite)?Math.max(...topology)-Math.min(...topology):null;
  return {replicaIndex,start,seed:replicaSeed,configuration,history,samples,statistics,acceptance:totalAccepted/totalProposed,accepted:totalAccepted,proposed:totalProposed,acceptanceAudit,maxActionCacheDrift,maxGroupMembershipResidual:membership,topologyDiagnostic:{...topologyMobility(topology,statistics.topology),estimator:input.measurement}};
}
export async function runEnsemble(input,context={}){
  const estimate=latticeEstimate(input.lattice,createGroup(input.group));assertBudget(estimate,{ensemble:true,maxBytes:context.budget?.maxBytes,updates:estimate.activeLinks*(input.sampler.burnIn+input.sampler.samples*input.sampler.thin)*input.sampler.starts.length});
  const model=modelDescriptor(input),modelHash=await sha256(model),replicas=[];
  for(let i=0;i<input.sampler.starts.length;i++)replicas.push(await runReplica(input,input.sampler.starts[i],i,modelHash,context));
  const comparison=compareReplicas(replicas,'plaquette'),configuration=replicas.at(-1).configuration,measurement=measure(configuration,input.measurement),lastHash=await configurationHash(configuration,modelHash),contract=samplerContract(input.sampler,configuration.group),allAdequate=replicas.every(r=>r.statistics.plaquette.status==='FINITE_SAMPLE_DIAGNOSTICS_ACCEPTABLE'&&(r.statistics.action.status==='FINITE_SAMPLE_DIAGNOSTICS_ACCEPTABLE'||r.statistics.action.status==='DETERMINISTIC_OBSERVABLE')&&r.statistics.plaquette.segmentMeans?.diagnosticZ<=4),compatible=comparison.status==='MEANS_COMPATIBLE_AT_DIAGNOSTIC_THRESHOLD';
  const manifestBody={schema:'MathScope.M2.WilsonEnsembleManifest/1',model,modelHash,algorithm:contract,algorithmRevision:REVISION,sampler:input.sampler,measurement:{fieldStrengthEstimator:input.measurement,flow:null},replicas:replicas.map(r=>({replicaIndex:r.replicaIndex,seed:r.seed,start:r.start,sampleList:r.samples.map(s=>({index:s.index,sweep:s.sweep,configurationHash:s.configurationHash})),finalConfigurationHash:r.samples.at(-1).configurationHash})),sampleStorage:'All retained observable rows and configuration hashes are exported. The final raw configuration of each replica is exported. Other raw configurations are reproducible by the pinned seed/algorithm; they are not falsely reported as stored.',revisionPolicy:'Any model, beta, group, representation, spacing, volume, boundary, seed, sampler or flow change requires a fresh run. No reweighting adapter is implemented.'};
  const manifest={...manifestBody,ensembleHash:await sha256(manifestBody)},observationHash=await sha256({ensembleHash:manifest.ensembleHash,measurement:input.measurement,view:input.view}),visualization=visualizeLattice(configuration,measurement,input.view,lastHash);visualization.observationHash=observationHash;
  const equilibrium=diagnoseEnsemble(replicas,{beta:input.beta});const blockers=[];if(!equilibrium.passed)blockers.push('FINITE_EQUILIBRIUM_OR_TOPOLOGY_MOBILITY_DIAGNOSTICS_INCOMPLETE');if(!allAdequate)blockers.push('FINITE_SAMPLE_EFFECTIVE_SIZE_OR_STATIONARITY_DIAGNOSTICS_INCOMPLETE');if(!compatible)blockers.push('INDEPENDENT_REPLICA_COMPATIBILITY_NOT_ESTABLISHED');
  const serializedReplicas=replicas.map(({configuration,...rest})=>({...rest,finalSource:{modelHash,sourceHash:rest.samples.at(-1).configurationHash,links:serializeLinks(configuration)}}));
  const betaZeroReference=input.beta===0?replicas.map(r=>({replica:r.replicaIndex,observable:'meanPlaquette',reference:0,actual:r.statistics.plaquette.mean,predeclaredAbsoluteTolerance:r.statistics.plaquette.standardError===null?null:6*r.statistics.plaquette.standardError,withinTolerance:r.statistics.plaquette.standardError!==null&&Math.abs(r.statistics.plaquette.mean)<=6*r.statistics.plaquette.standardError,scope:'At beta=0 the target is product Haar; an elementary nondegenerate plaquette has zero normalized defining trace expectation.'})):null;
  // History and retained rows have their own identities. A final x4 slice
  // cannot identify a Monte Carlo chart that includes earlier configurations.
  const historyHash=await sha256({modelHash,replicas:serializedReplicas.map(r=>({replicaIndex:r.replicaIndex,seed:r.seed,history:r.history}))}),sampleHash=await sha256({modelHash,replicas:serializedReplicas.map(r=>({replicaIndex:r.replicaIndex,seed:r.seed,samples:r.samples}))});
  const charts=[{id:'wilson-action-history',title:'Wilson action · burn-in and retained histories',x:{label:'Monte Carlo sweep',unit:'sweeps',type:'ALGORITHM_ITERATION'},y:{label:'S',unit:'dimensionless'},series:replicas.map(r=>({label:`${r.start} / replica ${r.replicaIndex}`,points:r.history.map(s=>({x:s.sweep,y:s.action,phase:s.phase})),sourceField:`replicas[${r.replicaIndex}].history[*].action`}))},{id:'wilson-plaquette-history',title:'Normalized plaquette trace',x:{label:'Monte Carlo sweep',unit:'sweeps',type:'ALGORITHM_ITERATION'},y:{label:'Re Tr Up / dR',unit:'dimensionless'},series:replicas.map(r=>({label:`${r.start} / replica ${r.replicaIndex}`,points:r.history.map(s=>({x:s.sweep,y:s.meanPlaquette,phase:s.phase})),sourceField:`replicas[${r.replicaIndex}].history[*].meanPlaquette`}))}];
  for(const chart of charts){
    chart.sourceHash=historyHash;chart.sourcePath='replicas[*].history';
    chart.observation={kind:'MONTE_CARLO_SWEEP_HISTORY',coordinateTypes:['ALGORITHM_ITERATION','OBSERVABLE'],sourceFields:chart.series.map(s=>s.sourceField),includesBurnIn:true,physicalTime:false,retainedRows:'replicas[*].samples'};
    chart.observationHash=await sha256({sourceHash:historyHash,observation:chart.observation,x:chart.x,y:chart.y});
  }
  return {status:blockers.length?'PARTIAL':'COMPLETED',evidenceGrade:'NUMERIC_ESTIMATE',model,modelHash,sourceHash:lastHash,sampleHash,historyHash,ensembleHash:manifest.ensembleHash,manifest,lattice:descriptor(configuration),replicas:serializedReplicas,diagnostics:{quantitativeStatus:blockers.length?'EXPLORATORY_FINITE_ENSEMBLE':'FINITE_OBSERVABLE_DIAGNOSTICS_ACCEPTABLE',replicaComparison:comparison,equilibrium,betaZeroReference,confidenceMeaning:'Any emitted interval is approximate and conditional on equilibrium; finite diagnostics do not prove equilibrium.',topologyMixing:equilibrium.topologyEstimatorMobilityPassed?'MEASURED_ESTIMATOR_MOBILE_INTEGER_SECTORS_UNCERTIFIED':'TOPOLOGY_DIAGNOSTIC_INCOMPLETE'},measurements:measurement,visualization,charts,gaugeCheck:gaugeDiagnostics(configuration,'m2-ensemble-final-gauge-check'),checks:[{id:'Y4-local-action-recomputation',ok:replicas.every(r=>r.maxActionCacheDrift<=1e-9)},{id:'Y4-group-membership',ok:replicas.every(r=>r.maxGroupMembershipResidual<=1e-9)},{id:'Y4-independent-replica-diagnostics',ok:compatible}],blockers,scopeBlockers:['CONTINUUM_AND_INFINITE_VOLUME_LIMITS_NOT_CONSTRUCTED'],reflectionPositivity:reflectionAudit(input),transferOperator:{status:'SEPARATE_EXPLICIT_CUTOFF_JOB_AVAILABLE',jobKind:'gauge.transfer-cutoff',hilbertSpace:'Gauge-invariant subspace of L²(G^spatialEdges,dHaar), normally infinite-dimensional even for finitely many edges.',finiteMatrix:null,requiredForFiniteMatrix:['Peter–Weyl cutoff or declared cubature','basis and Gauss constraints','approximation error','positivity and symmetry preservation checks']}};
}
function simpson(f,panels){const n=panels%2===0?panels:panels+1,h=Math.PI/n;let sum=f(0)+f(Math.PI);for(let i=1;i<n;i++)sum+=(i%2?4:2)*f(i*h);return sum*h/3;}
export function su2Quadrature(beta,panels=2048){
  const weight=theta=>2/Math.PI*Math.sin(theta)**2*Math.exp(-beta*(1-Math.cos(theta))),z=simpson(weight,panels),first=simpson(theta=>Math.cos(theta)*weight(theta),panels)/z,second=simpson(theta=>Math.cos(theta)**2*weight(theta),panels)/z;
  return {partition:z,meanNormalizedTrace:first,secondMoment:second,panels:panels%2===0?panels:panels+1,formula:'U=cos(theta) I+i sin(theta) n·sigma; normalized Haar radial weight (2/pi) sin²(theta) dtheta, theta∈[0,pi].',method:'Independent one-dimensional angular Simpson quadrature of the exact SU(2) Haar measure.'};
}
export async function runSingleLinkReference(input,context={}){
  const rng=rngFromSeed(input.seed),values=[],squares=[],history=[];let current=M.identity(2),currentAction=input.beta*(1-M.trace(current).re/2),accepted=0;
  for(let step=0;step<input.burnIn+input.samples;step++){
    context.checkCancelled?.();const candidate=input.algorithm==='FULL_BASIS_LIE_METROPOLIS'?M.multiply(randomExponential(createGroup(input.group),rng,input.stepSize),current):haarSU2(rng),proposedAction=input.beta*(1-M.trace(candidate).re/2),delta=proposedAction-currentAction;
    if(Math.log(rng.open())<Math.min(0,-delta)){current=candidate;currentAction=proposedAction;accepted++;}
    if(step>=input.burnIn){const q=M.trace(current).re/2;values.push(q);squares.push(q*q);history.push({sample:values.length-1,normalizedTrace:q,action:currentAction});}
    if(step%1024===1023)await yieldToRuntime(context,{phase:'su2-independent-haar-reference',completed:step+1,total:input.burnIn+input.samples});
  }
  const stats=analyzeSeries(values,{maxLag:256,minimumESS:100}),squareStats=analyzeSeries(squares,{maxLag:256,minimumESS:100}),coarse=su2Quadrature(input.beta,input.quadraturePanels),reference=su2Quadrature(input.beta,input.quadraturePanels*2),quadDifference=Math.abs(reference.meanNormalizedTrace-coarse.meanNormalizedTrace),comparisonTolerance=6*(stats.standardError??0)+quadDifference+1e-4,secondTolerance=6*(squareStats.standardError??0)+Math.abs(reference.secondMoment-coarse.secondMoment)+1e-4;
  const certifiedReference=su2Reference(input.beta);const passed=stats.effectiveSampleSize>=100&&reference.meanNormalizedTrace>=certifiedReference.meanTrace.lower-1e-12&&reference.meanNormalizedTrace<=certifiedReference.meanTrace.upper+1e-12&&Math.abs(stats.mean-reference.meanNormalizedTrace)<=comparisonTolerance&&Math.abs(squareStats.mean-reference.secondMoment)<=secondTolerance,sourceHash=await sha256({revision:REVISION,input,history});
  return {status:passed?'COMPLETED':'PARTIAL',evidenceGrade:'NUMERIC_VALIDATED',sourceHash,model:{kind:'ONE_SU2_LINK_BOLTZMANN_HAAR',action:'beta (1-Re Tr(U)/2)',beta:input.beta,group:input.group,algorithm:input.algorithm,stepSize:input.algorithm==='FULL_BASIS_LIE_METROPOLIS'?input.stepSize:null,notAFourDimensionalEnsemble:true},reference,certifiedReference,coarseReference:coarse,statistics:stats,secondMomentStatistics:squareStats,acceptance:accepted/(input.samples+input.burnIn),history,comparison:{passed,meanError:Math.abs(stats.mean-reference.meanNormalizedTrace),predeclaredMeanTolerance:comparisonTolerance,secondMomentError:Math.abs(squareStats.mean-reference.secondMoment),predeclaredSecondMomentTolerance:secondTolerance,rule:'Six autocorrelation-adjusted standard errors plus quadrature refinement difference plus 1e-4; minimum ESS 100.',interpretation:'This is a distributional numerical control against independent Haar quadrature, not merely a same-seed replay.'},visualization:{kind:'SAMPLER_REFERENCE',points:history.filter((_,i)=>i%Math.max(1,Math.ceil(history.length/600))===0).map(p=>({pos:[p.sample,p.normalizedTrace,0],value:p.normalizedTrace,sourceIndex:p.sample,sourceField:`history[${p.sample}].normalizedTrace`,label:`sample ${p.sample}`})),lines:[],axes:[{label:'retained sample',unit:'index',type:'ALGORITHM_ITERATION',scale:'linear'},{label:'Re Tr(U)/2',unit:'dimensionless',type:'OBSERVABLE',scale:'linear'},{label:'display plane',unit:'none',type:'CATEGORICAL_LAYOUT',scale:'linear'}],description:'Actual retained one-link Monte Carlo samples, checked against independent Haar angular quadrature. Display LOD leaves the complete source history unchanged.',sourceHash,sourcePath:'history',lostInformation:['The 2×2 matrix orientation is not recoverable from its normalized trace.'],reconstruction:{enabled:false}},checks:[{id:'Y4-03-independent-haar-quadrature',ok:passed}],blockers:passed?[]:['The retained chain did not meet the predefined independent-reference tolerance and effective sample requirement.']};
}
