/** Independent product-Haar importance reference for an actual four-dimensional lattice. */
import {sha256} from '../../mathscope-m0/contracts.mjs';
import {check,rngFromSeed,yieldToRuntime} from './contracts.mjs';
import {createGeometry,modelDescriptor,createConfiguration} from './lattice.mjs';
import {qConfiguration,qWilson,qFromMatrix} from './quaternion-oracle.mjs';
import {runEnsemble} from './ensemble.mjs';
import {expEnclosure} from './enclosures.mjs';

export function referenceInterval({samples,plaquetteCount,sumWeight,sumWeightedPlaquette,failureProbability}){
  const L=Math.log(4/failureProbability),z=sumWeight/samples,y=sumWeightedPlaquette/samples,zRadius=Math.sqrt(L/(2*samples))+1e-10,v=1/(4*plaquetteCount),yRadius=Math.sqrt(2*v*L/samples)+4*L/(3*samples)+1e-10,Z={lower:Math.max(0,z-zRadius),upper:Math.min(1,z+zRadius)},Y={lower:y-yRadius,upper:y+yRadius};
  if(Z.lower<=0)return {status:'UNRESOLVED_SMALL_DENOMINATOR',partition:Z,weightedTraceNumerator:Y,meanTrace:null,estimate:null};
  const values=[Y.lower/Z.lower,Y.lower/Z.upper,Y.upper/Z.lower,Y.upper/Z.upper];
  return {status:'SIMULTANEOUS_INDEPENDENT_REFERENCE_INTERVAL',partition:Z,weightedTraceNumerator:Y,meanTrace:{lower:Math.max(-1,Math.min(...values)),upper:Math.min(1,Math.max(...values))},estimate:y/z,probabilityAtLeast:1-failureProbability,bounds:{partitionHoeffdingRadius:zRadius,numeratorBernsteinRadius:yRadius,productHaarVarianceUpper:v,proof:'Distinct elementary plaquettes on this open, nondegenerate graph have zero Haar covariance: at least one link occurs in only one loop. Each normalized SU(2) fundamental trace has Haar variance 1/4. Thus E[(mean plaquette)^2]=1/(4 Np). For Y=exp(-S) mean plaquette, Var(Y)<=E[Y²]<=1/(4 Np), since 0<=exp(-S)<=1. The centered variable is bounded by 2. Bernstein gives sqrt(2 v L/N)+4L/(3N). Hoeffding applies to exp(-S) in [0,1]; a union bound uses L=log(4/delta).'}};
}
export function compareWithReference(mean,standardError,interval){
  const margin=standardError===null?null:6*standardError;
  return {passed:margin!==null&&interval!==null&&mean>=interval.lower-margin&&mean<=interval.upper+margin,mean,referenceInterval:interval,chainMargin:margin,rule:'The chain mean must lie in the independently constructed simultaneous Haar reference interval expanded by six autocorrelation-adjusted chain standard errors. The rule and failure probability are fixed before sampling.'};
}
export async function runSmallLatticeReference(input,context={}){
  const geometry=createGeometry(input.lattice,input.beta),rng=rngFromSeed(input.seed+':independent-product-haar'),rows=[],firstConfigurations=[];let sumWeight=0,sumWeightedPlaquette=0;
  for(let i=0;i<input.oracleSamples;i++){
    context.checkCancelled?.();const links=qConfiguration(geometry,rng),measured=qWilson(geometry,links),weightBounds=expEnclosure(-measured.action),weight=(weightBounds.lower+weightBounds.upper)/2;
    sumWeight+=weight;sumWeightedPlaquette+=weight*measured.meanPlaquette;rows.push({sample:i,action:measured.action,meanPlaquette:measured.meanPlaquette,weight});if(i<3)firstConfigurations.push({sample:i,positiveLinks:links});
    if(i%256===255)await yieldToRuntime(context,{phase:'independent-four-dimensional-haar-reference',completed:i+1,total:input.oracleSamples});
  }
  const reference=referenceInterval({samples:input.oracleSamples,plaquetteCount:geometry.plaquettes.length,sumWeight,sumWeightedPlaquette,failureProbability:input.failureProbability}),ensemble=await runEnsemble({...input,sampler:input.sampler},context),comparisons=ensemble.replicas.map(r=>({replica:r.replicaIndex,start:r.start,...compareWithReference(r.statistics.plaquette.mean,r.statistics.plaquette.standardError,reference.meanTrace)}));
  const pure=await createConfiguration({...input,initial:{kind:'PURE_GAUGE',seed:input.seed+':pure-gauge-oracle'}},context),pureOracle=qWilson(geometry,pure.links.map(u=>u?qFromMatrix(u):null)),last=ensemble.replicas.at(-1),matrixConfiguration={...pure,links:last.finalSource.links.map(u=>u?{n:u.n,re:Float64Array.from(u.re),im:Float64Array.from(u.im)}:null)},independentLast=qWilson(geometry,matrixConfiguration.links.map(u=>u?qFromMatrix(u):null)),actionAgreement=Math.abs(independentLast.action-ensemble.measurements.action),traceAgreement=Math.abs(independentLast.meanPlaquette-ensemble.measurements.meanPlaquette),passed=comparisons.every(c=>c.passed)&&ensemble.status==='COMPLETED'&&Math.abs(pureOracle.action)<=1e-10&&actionAgreement<=1e-10&&traceAgreement<=1e-10;
  const model=modelDescriptor(input),modelHash=await sha256(model),source={modelHash,seed:input.seed,oracleSamples:input.oracleSamples,failureProbability:input.failureProbability,rows,firstConfigurations},sourceHash=await sha256(source),sampleHash=await sha256(rows);
  return {status:passed?'COMPLETED':'PARTIAL',evidenceGrade:'INDEPENDENT_FINITE_DISTRIBUTION_VALIDATION',model,modelHash,sourceHash,sampleHash,reference:{...reference,scope:'Actual SU(2) Wilson links on the four-dimensional 2×2×2×2 open lattice, at the selected nonzero beta. No one-link system is substituted for this comparison.',method:'Independent product-Haar draws with Boltzmann importance weights; quaternion arithmetic is separate from the dense-matrix Markov implementation.',probabilityQualification:'The concentration inequality assumes ideal independent Haar draws. The pinned xorshift/Box–Muller implementation is a reproducible finite PRNG simulation of that law; it is not a deterministic proof of randomness.',actionInterval:reference.meanTrace?{lower:input.beta*geometry.plaquettes.length*(1-reference.meanTrace.upper),upper:input.beta*geometry.plaquettes.length*(1-reference.meanTrace.lower)}:null},comparisons,independentControls:{pureGauge:{action:pureOracle.action,meanPlaquette:pureOracle.meanPlaquette,passed:Math.abs(pureOracle.action)<=1e-10},lastConfiguration:{actionAgreement,traceAgreement,passed:actionAgreement<=1e-10&&traceAgreement<=1e-10}},ensemble,source,checks:[{id:'Y4-03-independent-nonzero-beta-reference',ok:comparisons.every(c=>c.passed)},{id:'Y4-03-independent-quaternion-action',ok:actionAgreement<=1e-10&&traceAgreement<=1e-10},{id:'Y4-03-pure-gauge-reuse',ok:Math.abs(pureOracle.action)<=1e-10},{id:'Y4-04-reference-chain-diagnostics',ok:ensemble.status==='COMPLETED'}],blockers:passed?[]:['The independent-reference comparison, chain diagnostic, or independent arithmetic control did not pass. A fixed seed alone is not acceptance evidence.'],visualization:{kind:'INDEPENDENT_LATTICE_REFERENCE',sourceHash,sourcePath:'source.rows',points:rows.filter((_,i)=>i%Math.max(1,Math.ceil(rows.length/600))===0).map(r=>({pos:[r.sample,r.meanPlaquette,0],value:r.meanPlaquette,sourceIndex:r.sample,sourceField:`source.rows[${r.sample}].meanPlaquette`,label:`independent Haar draw ${r.sample}`})),lines:[],axes:[{label:'independent reference draw',unit:'index',type:'ALGORITHM_ITERATION'},{label:'normalized mean plaquette',unit:'1',type:'OBSERVABLE'},{label:'display plane',unit:'1',type:'CATEGORICAL_LAYOUT'}],observation:{kind:'INDEPENDENT_HAAR_IMPORTANCE_HISTORY',coordinateTypes:['ALGORITHM_ITERATION','OBSERVABLE'],sourceFields:['source.rows','reference','comparisons'],physicalTime:false},description:'Raw independent product-Haar plaquettes, with separate Boltzmann weights and reference intervals. Draw index is not Euclidean time.',lostInformation:['Scalar rows do not reconstruct every gauge matrix. Three raw independent configurations are retained; other configurations can be reproduced from the pinned generator.']}};
}
