/** Model-specific Wilson reflection-positivity audit; not a numeric Gram test. */
import {createGroup} from '../../mathscope-m1/gauge/groups.mjs';
import {sha256} from '../../mathscope-m0/contracts.mjs';

export const REFLECTION_SOURCE={id:'YM-R08',author:'M. Lüscher',title:'Construction of a selfadjoint, strictly positive transfer matrix for Euclidean lattice gauge theories',doi:'10.1007/BF01614090',url:'https://bib-pubdb1.desy.de/record/396349/files/7611148.pdf',locator:'DESY 76/54, §II A–C, Proposition 1 and Proposition 2; equations (17), (20)–(23), (28)–(30)',retrieved:'2026-10-10',sourceScope:'SU(N), Wilson action, normalized Haar links; periodic spatial and temporal gauge boundaries. Pure-gauge factor obtained by omitting the fermion factor.'};

export function reflectionAudit(input,group=createGroup(input.group)){
  const l=input.lattice,action=input.actionKind??'WILSON_REAL_CHARACTER',extra=input.extraTerms??[],beta=input.beta,xi=l.as/l.at;
  const assumptions=[
    {id:'COMPACT_UNITARY_GROUP',ok:!!group.data&&group.matrixDimension>=2,source:'M1 exact faithful compact-group representation',value:{group:group.id,representation:group.spec.representation,exactDataHash:group.data.dataSha256}},
    {id:'NORMALIZED_HAAR',ok:input.measure===undefined||input.measure==='PRODUCT_NORMALIZED_HAAR',source:'Proposition 1, normalized invariant measure in §I',value:{selected:input.measure??'PRODUCT_NORMALIZED_HAAR',required:'A finite product of normalized Haar measures, including the temporal-link gauge projector.'}},
    {id:'LOCAL_WILSON_ACTION',ok:action==='WILSON_REAL_CHARACTER'&&Array.isArray(extra)&&extra.length===0,source:'Equations (20)–(23)',value:{action,extraTerms:extra}},
    {id:'NONNEGATIVE_COEFFICIENTS',ok:Number.isFinite(beta)&&beta>=0&&Number.isFinite(xi)&&xi>0,source:'Positive coefficients of the character expansion in the proof of Proposition 1',value:{spatial:beta/xi,temporal:beta*xi}},
    {id:'REFLECTION_SYMMETRIC_BOUNDARY',ok:['OPEN','PERIODIC'].includes(l.spatialBoundary)&&['OPEN','PERIODIC'].includes(l.temporalBoundary)&&Number.isInteger(l.Nt)&&l.Nt>=2,source:'Proposition 2 periodic case; the open case uses the explicit equal boundary vector in the derivation below',value:{spatial:l.spatialBoundary,temporal:l.temporalBoundary,Nt:l.Nt}},
    {id:'POSITIVE_TIME_GAUGE_INVARIANT_ALGEBRA',ok:input.observableAlgebra===undefined||input.observableAlgebra==='POSITIVE_TIME_GAUGE_INVARIANT_CYLINDER_FUNCTIONS',source:'Equations (4)–(5), Proposition 2',value:{selected:input.observableAlgebra??'POSITIVE_TIME_GAUGE_INVARIANT_CYLINDER_FUNCTIONS',required:'Finite gauge-invariant polynomials in link matrix coefficients and their conjugates supported in the positive-time half, followed by the L² closure.'}}
  ];
  const applied=assumptions.every(x=>x.ok),direct=group.spec.family==='SU'&&l.spatialBoundary==='PERIODIC'&&l.temporalBoundary==='PERIODIC'&&xi===1;
  const half=(l.Nt-1)/2,reflection=l.temporalBoundary==='OPEN'?{map:'theta(t)=Nt-1-t',center:half,plane:l.Nt%2?'SITE_PLANE':'LINK_MIDPLANE',boundaryState:'b(U)=exp(-S_spatial(U)/2); identical at both ends'}:{map:'theta(t)=(-t) mod Nt',plane:'SITE_PLANE',secondPlane:l.Nt%2?'LINK_MIDPLANE':'SITE_PLANE',boundaryState:'Periodic gauge trace, Z proportional to Tr(T^Nt)'};
  return {status:applied?(direct?'EXTERNAL_THEOREM_APPLIED':'ANALYTIC_EXTENSION_APPLIED'):'NOT_APPLICABLE',criterion:'Y4-06',sourceTheorem:REFLECTION_SOURCE,assumptions,reflection,antilinearMap:'(Theta F)(U)=conjugate(F(theta U)); a reversed oriented link is represented by its inverse.',operator:{space:'H_phys=P_G L²(G^E,dHaar), with E the active spatial links; generally infinite-dimensional.',gaussProjector:'(P_G f)(U)=integral_{G^vertices} f((Omega_x U_xy Omega_y^-1)_edges) dOmega; P_G=P_G*=P_G².',spatialMultiplier:'M f=exp(-S_spatial/2) f; M is bounded, positive, gauge invariant and invertible at a finite beta.',kineticKernel:'K(U,V)=product_edges k_beta_t(U_e V_e^-1), k_b(g)=exp[-b(1-Re chi_R(g)/dim R)]/z_b.',transfer:'T=M P_G K P_G M, up to a strictly positive scalar normalization from the temporal one-link integrals.',positivity:applied?'POSITIVE_SEMIDEFINITE':'NOT_ESTABLISHED',strictPositivity:applied&&beta>0?'The faithful R and its conjugate generate every irreducible representation; all kinetic Fourier coefficients are positive. T is injective on H_phys.':'No strictly-positive spectrum is claimed at beta=0.',unitarity:'Euclidean T is self-adjoint positive, not a unitary time evolution. For beta>0, H=-log(T)/a_t is defined by spectral calculus; real-time exp(-itH) is unitary.'},derivation:applied?[
    {step:'CHARACTER_COEFFICIENTS',identity:'exp[c Re chi_R]=sum_{n,m>=0} (c/2)^(n+m)/(n!m!) chi_{R^tensor n tensor Rbar^tensor m}',reason:'Every finite tensor product decomposes with nonnegative integer multiplicities. Compactness gives uniform absolute convergence, so all irreducible character coefficients of the kernel are nonnegative.'},
    {step:'KINETIC_POSITIVITY',identity:'<f,Kf>=sum_pi d_pi (a_pi/d_pi) ||fhat(pi)||_HS² >=0, with fhat(pi)=integral f(g) pi(g)* dg',reason:'Peter–Weyl orthogonality diagonalizes a central convolution kernel. Tensor products over finitely many spatial links preserve positivity.'},
    {step:'GAUSS_AND_POTENTIAL',identity:'<f,Tf>=<P_G M f,K P_G M f> >=0',reason:'The temporal-link integral is the orthogonal gauge projector. Both K and M commute with the gauge action. Nonnegative anisotropic coefficients change these factors without changing this argument.'},
    {step:'REFLECTED_EXPECTATION',identity:'Open reflection gives ||K^(1/2) P_G h_F||²/Z (link plane) or an integral of |h_F|²/Z (site plane). Periodic reflection gives Tr(A_F* A_F)/Z after splitting the positive transfer powers.',reason:'The two halves have the same local action and Haar measure and are related by the displayed antilinear reflection. For open boundaries the two boundary vectors agree. These identities apply to the entire stated algebra, rather than a finite collection of numeric correlations.'}
  ]:[],extensionFromSource:direct?null:{status:'EXPLICIT_DERIVATION_FROM_THE_SOURCE_ARGUMENT',differences:{group:group.spec.family==='SU'?'Within source group family':'Faithful compact group supplied by the M1 matrix data, using the same tensor-character positivity argument.',anisotropy:xi===1?'Isotropic':'Positive beta_s and beta_t are separate multipliers/kernel coefficients.',boundary:l.spatialBoundary==='PERIODIC'&&l.temporalBoundary==='PERIODIC'?'Periodic':'Open boundary links are absent; the equal-boundary-vector factorization above replaces the periodic trace.'},notClaimed:'The source theorem is not quoted as literally stating every extension; the separate derivation and hypothesis checks are exposed.'},numericEvidenceRole:'Finite correlation matrices or numerical eigenvalues are not the proof of this property.',newLeanKernelRun:false,continuumQFT:'NOT_CONSTRUCTED',blockers:assumptions.filter(x=>!x.ok).map(x=>x.id)};
}

export async function runReflection(input){
  const report=reflectionAudit(input),model={group:input.group,lattice:input.lattice,beta:input.beta,measure:input.measure??'PRODUCT_NORMALIZED_HAAR',actionKind:input.actionKind??'WILSON_REAL_CHARACTER',extraTerms:input.extraTerms??[],observableAlgebra:input.observableAlgebra??'POSITIVE_TIME_GAUGE_INVARIANT_CYLINDER_FUNCTIONS'},modelHash=await sha256(model),sourceHash=await sha256({modelHash,report});
  return {status:report.blockers.length?'PARTIAL':'COMPLETED',evidenceGrade:report.status,model,modelHash,sourceHash,sampleHash:await sha256(report.assumptions),reflectionPositivity:report,checks:report.assumptions.map(x=>({id:x.id,ok:x.ok})),blockers:report.blockers,visualization:{kind:'THEOREM_HYPOTHESIS_AUDIT',sourceHash,sourcePath:'reflectionPositivity.assumptions',points:report.assumptions.map((a,i)=>({pos:[i,a.ok?1:0,0],value:a.ok?1:0,label:a.id,sourceIndex:i,sourceField:`reflectionPositivity.assumptions[${i}]`})),lines:[],axes:[{label:'assumption index',type:'CATEGORICAL',unit:'1'},{label:'hypothesis mapping',type:'LOGICAL_STATUS',unit:'1'},{label:'display plane',type:'CATEGORICAL_LAYOUT',unit:'1'}],observation:{kind:'THEOREM_HYPOTHESIS_MAPPING',coordinateTypes:['CATEGORICAL','LOGICAL_STATUS'],sourceFields:['reflectionPositivity.assumptions'],physicalDimension:0},description:'Model-specific theorem hypotheses and the displayed analytic factorization; logical rows do not measure a physical coordinate.',lostInformation:['A green hypothesis row is not a new theorem-prover kernel execution. The complete argument and source mapping are in reflectionPositivity.']}};
}
