/** Fixed-volume classical energy and real topological charge refinement. */
import * as M from '../../mathscope-m1/gauge/matrix.mjs';
import {createGroup} from '../../mathscope-m1/gauge/groups.mjs';
import {createField,densities} from '../../mathscope-m1/gauge/fields.mjs';
import {sha256} from '../../mathscope-m0/contracts.mjs';
import {normalizeInput,check,yieldToRuntime} from './contracts.mjs';
import {createConfiguration,serializeLinks,action} from './lattice.mjs';
import {smoothnessBounds,multiplicationRoundoff,projectedCurvatureWithError,localCurvatureBound,metricFactorEnclosure,piEnclosure} from './transport-certificates.mjs';
import {densityErrorBounds} from './refinement.mjs';
import * as I from './enclosures.mjs';
const up=x=>I.nextUp(x),norm=x=>Math.max(Math.abs(x.lower),Math.abs(x.upper));
const safe=x=>typeof x==='number'&&Number.isInteger(x)&&!Number.isSafeInteger(x)?{kind:'FLOAT64',value:x}:Array.isArray(x)?x.map(safe):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,safe(v)])):x;
function product(a){return a.reduce((s,x)=>I.mul(s,x),I.point(1));}
export async function bpstVolumeReference(field,origin,lengths,panels,context={}){
  const extents=lengths.map(I.point),spacings=extents.map(x=>I.div(x,I.point(panels))),nodes=spacings.map((a,j)=>Array.from({length:panels},(_,i)=>I.add(I.point(origin[j]),I.mul(I.point(i+.5),a)))),rho2=I.pow(I.point(field.spec.rho),2),rho4=I.pow(I.point(field.spec.rho),4),pi2=I.pow(piEnclosure(),2),C=I.div(I.mul(I.point(6*field.group.index),rho4),pi2),volume=product(extents),cellVolume=product(spacings);let sum=I.point(0);
  for(let t=0;t<panels;t++){
    for(let z=0;z<panels;z++)for(let y=0;y<panels;y++)for(let x=0;x<panels;x++){
      let D=rho2;for(const [j,i] of [x,y,z,t].entries()){const q=I.sub(nodes[j][i],I.point(field.spec.center[j])),q2=I.mul(q,q);q2.lower=Math.max(0,q2.lower);D=I.add(D,q2);}sum=I.add(sum,I.div(C,I.pow(D,4)));
    }
    await yieldToRuntime(context,{phase:'independent-bpst-fixed-volume-quadrature',completed:t+1,total:panels});
  }
  const quadrature=I.mul(sum,cellVolume),secondDerivative=I.div(I.mul(I.point(8),C),I.pow(I.point(field.spec.rho),10)),lengthSquared=extents.reduce((s,L)=>I.add(s,I.mul(L,L)),I.point(0)),error=I.div(I.mul(I.mul(volume,secondDerivative),lengthSquared),I.point(24*panels*panels)).upper,charge={lower:I.nextDown(quadrature.lower-error),upper:I.nextUp(quadrature.upper+error)},energyFactor=I.div(I.mul(I.point(8),pi2),I.pow(I.point(field.spec.coupling.g),2)),energy=I.mul(charge,energyFactor);
  return {method:'Independent tensor midpoint integration of the closed BPST density, using directed arithmetic and a global second-derivative remainder.',panelsPerCoordinate:panels,pointCount:panels**4,charge:{...charge,estimate:I.midpoint(quadrature)},energy:{...energy,estimate:I.midpoint(I.mul(quadrature,energyFactor))},quadratureErrorUpper:error,proof:'q=C/(rho²+|x-center|²)^4, C=6 index rho^4/pi². For every coordinate |d_jj q|<=8C/rho^10: |9y-1|/(1+y)^6<=1 for y>=0. Tensor midpoint error is <=Vol sum_j L_j² sup|d_jj q|/(24 m²). This encloses the continuous fixed-box integral independently of the group-valued link discretization.',rawQuadratureStorage:'The complete implicit tensor grid, source rule, directed accumulation and point count are recorded. Node arrays are not represented as stored gauge configurations.'};
}
function intervalDistance(value,reference){const difference=I.sub(I.point(value),reference);return {lower:difference.lower<=0&&difference.upper>=0?0:Math.min(Math.abs(difference.lower),Math.abs(difference.upper)),upper:norm(difference),estimate:Math.abs(value-reference.estimate)};}
export async function runVolumeRefinement(input,context={}){
  const field=createField(createGroup(input.group),input.field),lengths=[input.spatialLength,input.spatialLength,input.spatialLength,input.temporalLength],box=input.origin.map((x,j)=>[I.nextDown(x-1e-12),I.nextUp(x+lengths[j]+1e-12)]);check(box.every((b,j)=>b[0]>=field.spec.domain.bounds[j][0]&&b[1]<=field.spec.domain.bounds[j][1]),'INVALID_INPUT','The fixed-volume certificate needs its entire rounding enclosure inside the declared source window.');
  const bounds=smoothnessBounds(field,box),reference=await bpstVolumeReference(field,input.origin,lengths,input.referencePanels,context),volume=product(lengths.map(I.point)),c=metricFactorEnclosure(field.group).upper,{A:M0,first:M1,second:M2}=bounds.maximum,F0=I.add(I.mul(I.point(2),I.point(M1)),product([I.point(2),I.point(M0),I.point(M0)])).upper,F1=I.add(I.mul(I.point(2),I.point(M2)),product([I.point(4),I.point(M0),I.point(M1)])).upper,qLipschitz=I.div(product([I.point(6),I.point(c),I.point(F0),I.point(F1)]),I.mul(I.point(4),I.pow(piEnclosure(),2))).upper,energyLipschitz=I.div(product([I.point(12),I.point(c),I.point(F0),I.point(F1)]),I.pow(I.point(field.spec.coupling.g),2)).upper,levels=[];
  for(const n of input.cellCounts){
    const exactSpacing=lengths.map(L=>I.div(I.point(L),I.point(n))),as=input.spatialLength/n,at=input.temporalLength/n,lattice={Ns:n+1,Nt:n+1,as,at,spatialBoundary:'OPEN',temporalBoundary:'OPEN',lengthUnit:field.spec.units.length,origin:input.origin},request=normalizeInput('gauge.lattice',{group:input.group,lattice,beta:2*field.group.matrixDimension*field.group.metricTraceFactor/field.spec.coupling.g**2,initial:{kind:'CLASSICAL_FIELD',field:field.spec,transportSteps:input.transportSteps}}),configuration=await createConfiguration(request,context),geometry=configuration.geometry,linkCertificate=configuration.numericalError.certificate;
    let coordinateError=0;
    for(const edge of geometry.active){const x=geometry.physical(edge.site),y=x.slice();y[edge.mu]+=geometry.spacings[edge.mu];for(const [coordinates,site] of [[x,edge.site],[y,edge.end]]){const integers=geometry.coords(site);let error=0;for(let j=0;j<4;j++){const ideal=I.add(I.point(input.origin[j]),I.mul(I.point(integers[j]),exactSpacing[j]));error=up(error+norm(I.sub(I.point(coordinates[j]),ideal)));}coordinateError=Math.max(coordinateError,error);}}
    const geometryError=I.add(product([I.point(Math.max(as,at)),I.point(M1),I.point(coordinateError)]),product([I.point(2),I.point(M0),I.point(coordinateError)])).upper,perLink=up(linkCertificate.maximumLinkErrorUpper+geometryError),siteFields=Array.from({length:geometry.V},()=>Array.from({length:4},()=>Array(4).fill(null))),siteErrors=Array.from({length:geometry.V},()=>Array.from({length:4},()=>Array(4).fill(null)));
    for(const p of geometry.plaquettes){
      let U=M.identity(field.group.matrixDimension),error=0;for(const edge of p.edges){const a=configuration.links[edge.id],v=edge.inverse?M.dagger(a):a;error=up(up(up(error*up(1+perLink))+perLink)+multiplicationRoundoff(U,v));U=M.multiply(U,v);}
      const area=I.mul(exactSpacing[p.mu],exactSpacing[p.nu]),projected=projectedCurvatureWithError(field.group,U,geometry.spacings[p.mu]*geometry.spacings[p.nu],{exactArea:area}),curvature=localCurvatureBound(bounds,exactSpacing[p.mu].upper,exactSpacing[p.nu].upper,error,{areaLower:area.lower});siteFields[p.site][p.mu][p.nu]=projected.matrix;siteFields[p.site][p.nu][p.mu]=M.scale(projected.matrix,-1);siteErrors[p.site][p.mu][p.nu]=up(curvature.upper+projected.projectionRoundoffUpper);
    }
    let chargeSum=I.point(0),energySum=I.point(0),chargeError=0,energyError=0;const cells=[];
    for(let site=0;site<geometry.V;site++){
      if(!geometry.coords(site).every(i=>i<n))continue;const F=siteFields[site];for(let j=0;j<4;j++)F[j][j]=M.matrix(field.group.matrixDimension);const density=densities(field,F),err=densityErrorBounds(field,F,siteErrors[site],density);chargeSum=I.add(chargeSum,I.point(density.topologicalDensity));energySum=I.add(energySum,I.point(density.actionDensity));chargeError=up(chargeError+err.topologyDensityUpper);energyError=up(energyError+err.energyUpper);cells.push({site,integerCoordinate:geometry.coords(site),physicalCoordinate4:geometry.physical(site),topologicalDensity:density.topologicalDensity,energyDensity:density.actionDensity});
    }
    const cellVolume=product(exactSpacing),chargeProduct=I.mul(chargeSum,cellVolume),energyProduct=I.mul(energySum,cellVolume),Q=I.midpoint(chargeProduct),E=I.midpoint(energyProduct),sumSpacing=exactSpacing.reduce((s,x)=>I.add(s,x),I.point(0)).upper,riemannQ=product([volume,I.point(qLipschitz),I.point(sumSpacing),I.point(.5)]).upper,riemannE=product([volume,I.point(energyLipschitz),I.point(sumSpacing),I.point(.5)]).upper,globalQ=I.add(I.add(I.mul(I.point(chargeError),cellVolume),I.point(riemannQ)),I.point(I.radius(chargeProduct))).upper,globalE=I.add(I.add(I.mul(I.point(energyError),cellVolume),I.point(riemannE)),I.point(I.radius(energyProduct))).upper;
    levels.push({cellsPerCoordinate:n,spatialSpacing:as,temporalSpacing:at,rhoOverAs:field.spec.rho/as,siteCount:geometry.V,cellCount:cells.length,activeLinks:geometry.active.length,realCharge:Q,energyIntegral:E,wilsonAction:action(configuration),chargeError:intervalDistance(Q,reference.charge),energyError:intervalDistance(E,reference.energy),certificate:{status:'FIXED_VOLUME_CLASSICAL_INTEGRAL_ERROR_BOUND',chargeErrorUpper:globalQ,energyErrorUpper:globalE,curvatureDensityPart:{chargeUpper:up(chargeError*cellVolume.upper),energyUpper:up(energyError*cellVolume.upper)},riemannQuadraturePart:{chargeUpper:riemannQ,energyUpper:riemannE},coordinateRoundoffUpper:coordinateError,transportGeometryCorrectionUpper:geometryError,sourceLinkCertificate:linkCertificate,derivation:'Sum the separately enclosed local curvature/density errors over all actual cells, then add the left-rectangle quadrature error Vol sum_j a_j sup|partial_j density|/2. Bounds |F|<=2M1+2M0² and |partial F|<=2M2+4M0M1 come from this field/representation. The intended grid uses exact box-length/n intervals; the stored vertex rounding and resulting link deformation are bounded separately.'},source:{links:serializeLinks(configuration),cells}});
    await yieldToRuntime(context,{phase:'gauge-fixed-volume-refinement',completed:levels.length,total:input.cellCounts.length});
  }
  const shrinking=levels.slice(1).every((row,i)=>row.chargeError.upper<levels[i].chargeError.lower&&row.energyError.upper<levels[i].energyError.lower),boundsDecrease=levels.slice(1).every((row,i)=>row.certificate.chargeErrorUpper<levels[i].certificate.chargeErrorUpper&&row.certificate.energyErrorUpper<levels[i].certificate.energyErrorUpper),model={kind:'FIXED_PHYSICAL_BOX_CLASSICAL_BPST_INTEGRALS',group:input.group,field:field.spec,origin:input.origin,lengths,units:field.spec.units.length,integerTopology:'NOT_CERTIFIED',boundary:'OPEN_RESTRICTION_OF_THE_SAME_CLASSICAL_FIELD'},modelHash=await sha256(model),sourceHash=await sha256(safe({modelHash,levels,reference})),sampleHash=await sha256(levels.map(l=>l.source.cells)),passed=shrinking&&boundsDecrease;
  return {status:passed?'COMPLETED':'PARTIAL',evidenceGrade:'FIXED_VOLUME_CLASSICAL_INTEGRAL_ENCLOSURE',model,modelHash,sourceHash,sampleHash,reference,levels,sourceDerivativeBounds:bounds,convergence:{fixedPhysicalVolume:true,bothSpacingsDecrease:true,independentErrorIntervalsStrictlyDecrease:shrinking,analyticBoundsDecrease:boundsDecrease,continuumTarget:'The integral of classical energy density and real topological density over exactly the same finite physical box.',globalIntegerCharge:null,quantumContinuumTheory:false},checks:[{id:'Y3-06-fixed-volume-energy-and-real-charge',ok:shrinking},{id:'Y3-07-separated-global-error-budget',ok:boundsDecrease}],blockers:passed?[]:['The independent integral error intervals or conservative global bounds did not strictly decrease. Increase the declared resolution/reference panels and inspect the same fixed model; global integer topology is never inferred.'],visualization:{kind:'FIXED_VOLUME_CONVERGENCE',sourceHash,sourcePath:'levels',points:levels.map((r,i)=>({pos:[r.spatialSpacing,r.chargeError.estimate,0],value:r.chargeError.estimate,sourceIndex:i,sourceField:`levels[${i}].chargeError.estimate`,label:`${r.cellCount} cells · Q=${r.realCharge}`})),lines:[{points:levels.map(r=>[r.spatialSpacing,r.chargeError.estimate,0])}],axes:[{label:'spatial spacing as',unit:field.spec.units.length,type:'PHYSICAL_LENGTH'},{label:'fixed-volume real-charge error',unit:'1',type:'NUMERIC_ERROR'},{label:'display plane',unit:'1',type:'CATEGORICAL_LAYOUT'}],observation:{kind:'FIXED_VOLUME_ENERGY_AND_REAL_CHARGE_REFINEMENT',coordinateTypes:['PHYSICAL_LENGTH','NUMERIC_ERROR'],sourceFields:['levels[*].chargeError','levels[*].energyError','reference'],physicalDimension:0},description:'The complete physical box remains fixed while both spacings shrink. Each level retains every actual source link and cell density. Real charge is compared with an independently enclosed BPST box integral.',lostInformation:['A finite-box real charge is not an integer bundle invariant.','This is a classical smooth-field continuum approximation, not a quantum continuum construction.']}};
}
