import {canonicalStringify} from '../mathscope-m0/contracts.mjs';
import {createM2Engine} from './core/engine.mjs';
import {M2_VERSION,normalizeRequest,validateDomainRequest,listExamples} from './core/registry.mjs';
import {commitM2SessionBundle} from './core/session-binding.mjs';
import {SourceBoundScene,renderObservationTable,renderObservationDetails} from './visualization/renderer.mjs';
import {numericValue} from './visualization/observations.mjs';
import {makeM2Visualization,listM2Panels} from './visualization/m2-views.mjs';
import {installM1ResearchControls} from './visualization/m1-controls.mjs';
import {CHECKLIST,ARCHIVE} from './evidence/checklist-data.mjs';
import {registerM2Tools} from './webmcp.mjs';

const pretty=v=>JSON.stringify(v,null,2),TERMINAL=new Set(['COMPLETED','PARTIAL','FAILED','CANCELLED','BUDGET_EXCEEDED','UNSUPPORTED','PRECISION_REQUIRED']);
const DESCRIPTIONS={arithmetic:'Pⁿ의 cohomology와 국소 zeta, 타원곡선의 유한체 점계수·Newton slope, 형식 q와 BK 비교, 유한 Witt 연산·perfectoid tower를 계산합니다.',gauge:'실제 군 행렬로 4차원 격자 링크·Wilson 작용을 만들고, 고전 장의 이산화와 유한 앙상블의 통계 진단을 계산합니다.',ns:'원문의 차수별 convolution, 축소 cutoff, potential의 curl, dyadic chart 및 projected pulse ODE·covariance·log tail을 계산합니다.'};
const BOUNDARIES={arithmetic:'지원된 유한환·다항식·점계수는 정확히 계산합니다. MW Frobenius backend, 일반 q descent, 전체 AΩ 비교는 진행 현황에 남아 있습니다.',gauge:'유한 격자와 명시한 확률 모형의 계산입니다. 짧은 chain의 통계 진단은 평형·위상 혼합을 보증하지 않으며, 연속체 이론·질량 간극은 별도 과제입니다.',ns:'N3 원본 검증 기록을 보존합니다. 여기의 실행 가능한 구성 요소를 동일 N3 프로파일의 전체 N4/N5 구성으로 연결하는 공통 Picard 구간·모멘트·잔차·Gaussian 인증은 추가 작업입니다.'};

export async function bootM2(){
  const root=document.getElementById('mathscopeResearchM2');if(!root||root.dataset.mounted==='true')return;
  const $=id=>document.getElementById(id),engine=createM2Engine(),examples=await listExamples(),environment=await engine.environment(),scene=new SourceBoundScene($('m2-scene')),origins=new Map(),saved=new Set();
  let selected=null,domain='arithmetic',lastComputeDomain='arithmetic',registration=null,exportURL=null,panelsFor=null,currentView=null,submissionSequence=0,presentationRevision=0;
  const foundation=()=>{const f=window.MathScopeV031Foundation;if(!f?.getSession||!f?.commitTypedBundle)throw Error('Research Session 연결이 준비되지 않았습니다.');return f;};
  const text=(id,v)=>{$(id).textContent=typeof v==='string'?v:pretty(v);};
  const status=(v,error=false)=>{text('m2-status',v);$('m2-status').dataset.error=String(error);};
  const option=(el,value,label)=>{const o=document.createElement('option');o.value=value;o.textContent=label;el.append(o);};
  const request=()=>normalizeRequest(JSON.parse($('m2-input').value));
  const matches=j=>{try{return canonicalStringify(request())===canonicalStringify(j.request);}catch{return false;}};
  const origin=()=>{const s=foundation().getSession();return {id:s.id,revision:s.sessionRevision};};
  function clearValidation(){text('m2-validation','현재 입력의 검사·재현 결과는 아직 없습니다.');$('m2-validation-panel').open=false;}
  function syncExample(req){const key=canonicalStringify(req),ex=examples.find(e=>canonicalStringify(e.request)===key),el=$('m2-example');if(!ex&&![...el.options].some(o=>o.value==='__custom__'))option(el,'__custom__','사용자 입력 · 실행 기록');el.value=ex?.id||'__custom__';}
  function renderSession(){try{const s=foundation().getSession();text('m2-session',s.id+' · session revision '+s.sessionRevision);}catch(e){text('m2-session',e.message);}}
  function on(id,fn){$(id).addEventListener('click',async()=>{const b=$(id);if(b.dataset.busy==='true')return;b.dataset.busy='true';b.disabled=true;try{await fn();}catch(e){status(e.message,true);}finally{b.dataset.busy='false';b.disabled=false;renderJobs();}});}
  function metric(label,value){const d=document.createElement('div'),a=document.createElement('strong'),b=document.createElement('small');d.className='m1-metric';a.textContent=String(value??'—');b.textContent=label;d.append(a,b);$('m2-metrics').append(d);}
  function setDomain(name,updateHash=true,focus=false){
    if(!['arithmetic','gauge','ns','checklist'].includes(name))return;
    const changed=name!=='checklist'&&lastComputeDomain!==name;if(domain!==name)presentationRevision++;domain=name;
    for(const b of root.querySelectorAll('[data-m2-tab]')){const yes=b.dataset.m2Tab===name;b.setAttribute('aria-selected',String(yes));b.tabIndex=yes?0:-1;if(yes&&focus)b.focus();}
    $('m2-compute-area').hidden=name==='checklist';$('m2-checklist-area').hidden=name!=='checklist';
    if(name!=='checklist'){lastComputeDomain=name;$('m2-compute-area').setAttribute('aria-labelledby','m2-tab-'+name);text('m2-domain-description',DESCRIPTIONS[name]);text('m2-domain-boundary',BOUNDARIES[name]);if(changed||!$('m2-example').options.length){$('m2-example').replaceChildren();for(const e of examples.filter(e=>e.domain===name))option($('m2-example'),e.id,e.label);loadExample();}requestAnimationFrame(()=>scene.draw());}
    if(updateHash&&root.classList.contains('active'))history.replaceState(null,'','#research-m2/'+name);
  }
  function loadExample(){const ex=examples.find(e=>e.id===$('m2-example').value);if(!ex)return;presentationRevision++;selected=null;panelsFor=null;$('m2-input').value=pretty(ex.request);text('m2-kind',ex.request.kind);clearValidation();renderResult();renderJobs();status('예제 입력 준비 · '+ex.request.kind);}
  function selectJob(id){const j=engine.getJob(id);presentationRevision++;if(!root.classList.contains('active'))document.querySelector('[data-view-target="research-m2"]')?.click();setDomain(j.request.kind.split('.')[0]);selected=id;$('m2-input').value=pretty(j.request);text('m2-kind',j.request.kind);syncExample(j.request);clearValidation();panelsFor=null;renderResult();renderJobs();status(j.request.kind+' · '+j.status+' · 선택한 실행 기록');return {ok:true,jobId:id,status:j.status,visualization:visualStatus()};}
  function renderJobs(){
    const jobs=engine.listSummaries();text('m2-job-count',jobs.length+' / 64 jobs');$('m2-jobs').replaceChildren();
    for(const j of jobs.slice().reverse()){const b=document.createElement('button'),s=document.createElement('strong'),small=document.createElement('small');b.type='button';s.textContent=j.kind+' · '+j.status;small.textContent=j.id+(saved.has(j.id)?' · 세션 저장됨':'');b.append(s,small);b.dataset.selected=String(j.id===selected);b.addEventListener('click',()=>selectJob(j.id));$('m2-jobs').append(b);}
    const j=jobs.find(x=>x.id===selected),done=j&&TERMINAL.has(j.status),canSave=j&&['COMPLETED','PARTIAL'].includes(j.status)&&origins.has(j.id)&&!saved.has(j.id);
    $('m2-cancel').disabled=!j||done;$('m2-save').disabled=!canSave||currentView?.binding.currentEditorMatches===false||$('m2-save').dataset.busy==='true';$('m2-replay').disabled=!done||$('m2-replay').dataset.busy==='true';$('m2-export').disabled=!done;
  }
  function visualStatus(){if(!currentView)return null;const v=currentView;return {state:v.state,kind:v.kind,title:v.title,binding:v.binding,tableRows:v.table.rows.length,totalRows:v.table.totalRows,points:v.scene.points.length,lines:v.scene.lines.length,arrows:v.scene.arrows.length,lod:v.lod,renderer:scene.getMetrics(),panel:$('m2-observation-select').value};}
  function renderResult(){
    const j=selected?engine.getJob(selected):null,r=j?.result,editorMatches=j?matches(j):true;
    if(panelsFor!==j?.id+(r?'result':'pending')){const options=listM2Panels(j);$('m2-observation-select').replaceChildren();for(const p of options.length?options:[{id:'main',title:'원본 관측'}])option($('m2-observation-select'),p.id,p.title);panelsFor=j?.id+(r?'result':'pending');}
    const v=makeM2Visualization(j,{currentEditorMatches:editorMatches,maxPoints:Number($('m2-lod').value),maxRows:200,panel:$('m2-observation-select').value});currentView=v;scene.setVisualization(v);root.dataset.resultStatus=j?.status||'NOT_RUN';root.dataset.resultKind=j?.request.kind||'';root.dataset.visualizationState=v.state;
    text('m2-result-status',v.state==='INPUT_CHANGED'?'INPUT_CHANGED':j?.status||'NOT_RUN');text('m2-result-description',j?j.request.kind+' · '+(editorMatches?'현재 입력의 실행':'이전 입력의 실행 기록')+' · '+j.id:'현재 입력의 계산을 실행하세요.');
    $('m2-metrics').replaceChildren();
    if(j){metric('실행 상태',j.status);metric('입력 SHA-256',j.inputHash.slice(0,12));if(r){const checks=r.checks||[];metric('유한 독립 검사',checks.filter(c=>c.pass===true||c.ok===true||c.status==='PASS').length+' / '+checks.length);if(r.results?.extensionField)metric('유한체 점계수',r.results.extensionField.count);if(r.results?.aP!==undefined)metric('aₚ',r.results.aP);if(r.measurements?.action!==undefined){const action=numericValue(r.measurements.action);metric('Wilson 작용 S',Number.isFinite(action)?Number(action.toPrecision(7)):'미확정');}if(r.statistics?.effectiveSampleSize!==undefined)metric('유효 표본 수',r.statistics.effectiveSampleSize===null?'미확정':Math.floor(r.statistics.effectiveSampleSize));if(r.replicas)metric('독립 replica',r.replicas.length);}}
    renderObservationTable($('m2-table-head'),$('m2-table-body'),v);renderObservationDetails($('m2-observation-details'),v);$('m2-observation-details').classList.add('m2-source-details');
    text('m2-observation',[v.title,v.description,v.axisMetadata.map(a=>a.label+' ['+a.type+'; '+a.unit+']').join(' · '),v.lod.originalPoints>v.lod.displayedPoints?'화면 '+v.lod.displayedPoints+' / 원본 '+v.lod.originalPoints+'개 · 전체 구간 LOD':null,...v.lostInformation].filter(Boolean).join('\n'));
    text('m2-color-range',v.color?.range?v.color.quantity+' · '+v.color.unit+' · '+v.color.range[0]+' → '+v.color.range[1]+' · '+v.color.mode:'값은 표·레이블·서로 다른 점과 선 모양으로 함께 제공합니다.');
    const blockers=[...(r?.blockers||[]),...(r?.scopeBlockers||[])];$('m2-blockers').hidden=!blockers.length;$('m2-blockers').replaceChildren();if(blockers.length){const title=document.createElement('strong');title.textContent='이 결과에 남은 조건';$('m2-blockers').append(title);for(const b of blockers){const p=document.createElement('p');p.textContent=typeof b==='string'?b:pretty(b);$('m2-blockers').append(p);}}
    text('m2-diagnostics',r?{checks:r.checks||[],diagnostics:r.diagnostics||r.results?.diagnostics||null,scope:r.scope||r.proofBoundary||r.results?.scope||null,precisionLedger:r.precisionLedger||null,sourceLedger:r.sourceLedger||r.provenance||r.manifest||null}:{status:j?.status||'NOT_RUN',checkpoint:j?.checkpoint||null});text('m2-result-json',j||{});
  }
  async function runRequest(value,options={}){
    const callSequence=++submissionSequence,initialPresentation=presentationRevision,req=normalizeRequest(value),captured=origin(),valid=await validateDomainRequest(req);
    if(!valid.ok){if(callSequence===submissionSequence&&presentationRevision===initialPresentation){text('m2-validation',valid);$('m2-validation-panel').open=true;}throw Error('입력 계약: '+pretty(valid.errors));}
    if(options.signal?.aborted)return {ok:false,code:'CANCELLED'};
    let submittedPresentation=null;
    if(callSequence===submissionSequence&&presentationRevision===initialPresentation){if(!root.classList.contains('active'))document.querySelector('[data-view-target="research-m2"]')?.click();setDomain(req.kind.split('.')[0]);$('m2-input').value=pretty(req);text('m2-kind',req.kind);syncExample(req);clearValidation();submittedPresentation=++presentationRevision;}
    const j=await engine.submit(req);origins.set(j.id,captured);
    if(options.signal){const abort=()=>engine.cancel(j.id);if(options.signal.aborted)abort();else{options.signal.addEventListener('abort',abort,{once:true});void engine.wait(j.id).then(()=>options.signal.removeEventListener('abort',abort));}}
    let stillCurrent=false;try{stillCurrent=submittedPresentation!==null&&presentationRevision===submittedPresentation&&callSequence===submissionSequence&&canonicalStringify(request())===canonicalStringify(req);}catch{}
    if(stillCurrent){presentationRevision++;selected=j.id;panelsFor=null;renderResult();status(req.kind+' 실행 중 · '+j.id);}renderJobs();return {ok:true,jobId:j.id,status:engine.getJob(j.id).status,inputHash:j.inputHash,selected:stillCurrent};
  }
  async function saveResult(id){const j=engine.getJob(id),captured=origins.get(id);if(!captured)throw Error('이 실행의 세션 출처를 확인할 수 없습니다. 다시 실행하세요.');if(saved.has(id))return {ok:true,alreadySaved:true,jobId:id};if(id===selected&&!matches(j))throw Error('현재 입력이 달라졌습니다. 실행 기록을 선택해 원래 입력을 복원하세요.');const report=await commitM2SessionBundle(j,engine,foundation(),captured);saved.add(id);renderSession();renderJobs();status('현재 세션에 유한 계산 기록을 저장했습니다 · '+id);const {session,...summary}=report;return {ok:true,jobId:id,report:summary,formalPass:false};}
  async function replayJob(id){const captured=origin(),initialPresentation=presentationRevision,report=await engine.replay(await engine.exportBundle(id));origins.set(report.freshJobId,captured);const present=initialPresentation===presentationRevision;if(present){selectJob(report.freshJobId);text('m2-validation',report);$('m2-validation-panel').open=true;}else renderJobs();status('동일 소스 재현 검사 · '+report.status+(present?'':' · 새 결과는 실행 목록에 보관했습니다.'),report.status!=='MATCH');return {ok:true,...report,selected:present};}
  function exportData(name,data){if(exportURL)URL.revokeObjectURL(exportURL);const content=pretty(data);exportURL=URL.createObjectURL(new Blob([content],{type:'application/json;charset=utf-8'}));$('m2-download').href=exportURL;$('m2-download').download=name;$('m2-download').textContent=name;$('m2-export-content').value=content;$('m2-export-panel').hidden=false;$('m2-export-panel').open=true;}
  function renderChecklist(){
    const p=$('m2-checklist-package').value,filter=$('m2-checklist-filter').value;$('m2-checklist').replaceChildren();
    for(const c of CHECKLIST.filter(c=>(p==='all'||c.id.startsWith(p+'-'))&&(filter==='all'||c.status===filter))){const d=document.createElement('details'),s=document.createElement('summary'),badge=document.createElement('span'),title=document.createElement('strong'),original=document.createElement('p'),scope=document.createElement('p'),test=document.createElement('p');d.className='m2-check-item';d.dataset.state=c.status;badge.className='m1-tag';badge.textContent=c.status;title.textContent=c.id+' · '+c.title;s.append(badge,title);original.className='m2-criterion';original.textContent=c.criteria;scope.className='m1-muted';scope.textContent='현재 구현: '+c.implementedScope;test.className='m1-muted';test.textContent='설계도 p.'+c.sourcePage+' · '+(c.testStatus||'원문 조건별 추가 검증 진행');d.append(s,original,scope,test);$('m2-checklist').append(d);}
  }
  const counts=CHECKLIST.reduce((a,c)=>(a[c.status]=(a[c.status]||0)+1,a),{});for(const [key,label] of [['PASS','전체 조건 통과'],['PARTIAL','부분 구현 · 추가 검증'],['OPEN','미구현 · 연구 진행']]){const d=document.createElement('div');d.className='m1-metric';const a=document.createElement('strong'),b=document.createElement('small');a.textContent=String(counts[key]||0);b.textContent=label;d.append(a,b);$('m2-checklist-summary').append(d);}
  for(const b of root.querySelectorAll('[data-m2-tab]')){b.addEventListener('click',()=>setDomain(b.dataset.m2Tab));b.addEventListener('keydown',e=>{const names=['arithmetic','gauge','ns','checklist'],i=names.indexOf(domain);let j;if(e.key==='ArrowRight')j=(i+1)%4;else if(e.key==='ArrowLeft')j=(i+3)%4;else if(e.key==='Home')j=0;else if(e.key==='End')j=3;else return;e.preventDefault();setDomain(names[j],true,true);});}
  on('m2-load',loadExample);$('m2-example').addEventListener('change',loadExample);$('m2-input').addEventListener('input',()=>{presentationRevision++;clearValidation();renderResult();renderJobs();});$('m2-observation-select').addEventListener('change',renderResult);$('m2-lod').addEventListener('change',renderResult);
  on('m2-validate',async()=>{const initialPresentation=presentationRevision,v=await validateDomainRequest(request());if(presentationRevision!==initialPresentation)return;text('m2-validation',v);$('m2-validation-panel').open=true;status(v.ok?'입력 계약 통과 · 개별 수학적 검사는 실행 결과에서 확인하세요.':'입력 계약을 확인하세요.',!v.ok);});on('m2-run',()=>runRequest(request()));on('m2-cancel',()=>{if(selected)engine.cancel(selected);});on('m2-save',()=>saveResult(selected));on('m2-replay',()=>replayJob(selected));on('m2-export',async()=>{exportData('MathScope-M2-'+selected.replaceAll(':','-')+'.json',await engine.exportBundle(selected));status('입력·전체 결과·소스 해시를 포함한 JSON을 준비했습니다.');});
  on('m2-copy',async()=>{$('m2-export-content').focus();$('m2-export-content').select();try{await navigator.clipboard.writeText($('m2-export-content').value);status('전체 실행 JSON을 복사했습니다.');}catch{status('전체 JSON을 선택했습니다. Ctrl/Cmd+C로 복사하세요.');}});
  for(const b of root.querySelectorAll('[data-m2-camera]'))b.addEventListener('click',()=>scene.camera(b.dataset.m2Camera));$('m2-checklist-package').addEventListener('change',renderChecklist);$('m2-checklist-filter').addEventListener('change',renderChecklist);
  engine.subscribe(j=>{if(j.id===selected){renderResult();if(TERMINAL.has(j.status))status(j.request.kind+' · '+j.status+' · 유한 검사와 남은 조건을 결과에서 확인하세요.',['FAILED','BUDGET_EXCEEDED'].includes(j.status));}renderJobs();});
  const api=Object.freeze({version:M2_VERSION,getStatus:()=>({ok:true,version:M2_VERSION,examples:examples.map(e=>({id:e.id,label:e.label,kind:e.request.kind,domain:e.domain})),jobs:engine.listSummaries(),checklist:{total:CHECKLIST.length,counts,fullM2Complete:counts.PASS===64},environment:{hash:environment.hash,workerSha256:environment.workerSha256,execution:environment.execution},visualization:visualStatus(),session:origin(),formalPass:false}),validateRequest:validateDomainRequest,runRequest,runExample:async(id,options)=>{const e=examples.find(e=>e.id===id);if(!e)throw Error('설치된 예제 ID가 아닙니다.');setDomain(e.domain);$('m2-example').value=e.id;return runRequest(e.request,options);},getJob:id=>({ok:true,job:engine.getJob(id)}),selectJob,cancelJob:id=>({ok:true,cancelRequested:engine.cancel(id)}),saveResult,replayJob});
  window.MathScopeResearchM2=api;
  async function register(){registration=await registerM2Tools(api);const {dispose,...state}=registration;text('m2-webmcp',state);}
  const nav=document.querySelector('[data-view-target="research-m2"]');nav?.addEventListener('click',e=>{setDomain(domain,e.isTrusted);renderSession();requestAnimationFrame(()=>scene.draw());});
  for(const b of document.querySelectorAll('[data-view-target]'))b.addEventListener('click',e=>{if(e.isTrusted&&b.dataset.viewTarget!=='research-m2'&&location.hash.startsWith('#research-m2'))history.replaceState(null,'',location.pathname+location.search);});
  function route(){const m=location.hash.match(/^#research-m2(?:\/(arithmetic|gauge|ns|checklist))?$/);if(m){nav?.click();setDomain(m[1]||'arithmetic',false);}}
  window.addEventListener('hashchange',route);window.addEventListener('mathscope:session-rendered',renderSession);window.addEventListener('pagehide',e=>{registration?.dispose();if(!e.persisted){engine.dispose();scene.destroy();if(exportURL)URL.revokeObjectURL(exportURL);}});window.addEventListener('pageshow',e=>{if(e.persisted)void register();});
  text('m2-runtime','M2 '+M2_VERSION+' · '+(environment.execution==='BROWSER_WEB_WORKER'?'Browser Worker':'Local Runtime'));text('m2-environment',environment);text('m2-m1-archive',ARCHIVE);renderChecklist();setDomain('arithmetic',false);renderSession();renderJobs();root.dataset.mounted='true';root.dataset.version=M2_VERSION;installM1ResearchControls();await register();route();status('M2 준비 완료 · '+examples.length+'개 실행 예제와 원문 64개 기준을 확인할 수 있습니다.');
}
if(typeof document!=='undefined'){const start=()=>void bootM2().catch(e=>{const out=document.getElementById('m2-status');if(out){out.textContent='M2 초기화 오류: '+e.message;out.dataset.error='true';}});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();}
