// Original 16 N4/N5 criteria, preserved verbatim from the user-supplied blueprint.
export const BLUEPRINT_SOURCE = {"name": "MathScope_Research_IDE_Blueprint_v1_KO(1)(9).pdf", "sha256": "f4758ab0c6f4038ab30cd9d3d945a471a467f9ffb4d36a0e172f95320720f0ac", "pages": [58, 60]};
export const CHECKLIST = [
  {
    "id": "N4-01",
    "title": "차수와 기호 충돌 분리",
    "criteria": "λn=2nh, En,Un,Vn,Πn와 scalar φn을 구분한다. η의 Fourier 차수·radial analytic 차수·배경 차수를 서로 다른 인덱스로 둔\n다. 합격: (5.1)의 q 지수와 E_n=√(2X) φn/C를 자동 단위 검사한다. Π0의 axis trace와 전체 pressure profile을 혼동하면\n실패다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "Exact q-power arithmetic checks (5.1), 1-2D=2h, A+D=1 and the radial pressure shift. An axis-trace pressure substitution or replacement of the pinned N3 h is rejected. Background, radial and eta indices are distinct.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-recursion.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-02",
    "title": "비선형 convolution 생성",
    "criteria": "(5.3)-(5.6)의 모든 i+j=n 곱을 생성한다. i=0,n 및 n,0은 현재 미지수에 선형이고 나머지는 확정된 이전 차수다. 합격: n=1,2\n의 직접 PDE 대입 결과와 coefficient extractor가 일치한다. axial viscosity의 n −1 shift와 압력 Ωn−1/(2X)를 반드시 포함\n한다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "The original cylindrical PDE is physically differentiated as an exact BigInt rational differential polynomial. Its n=1,2 coefficients equal independently generated (5.2)-(5.6), including all ordered pairs, vector connection terms and both n-1 shifts.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-recursion.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-03",
    "title": "차수별 inner Picard 풀이",
    "criteria": "(5.7)의 6성분 선형계와 (5.8)의 convergent Picard series를 사용하고 영 axis datum을 유지한다. 합격: 선택 analytic\nstrip·Cn·Cauchy radius loss를 기록하고 Picard tail를 상계한다. 반경 interval은 차수에 따라 임의 축소하지 않으며 lemma\n의 공통 interval 조건을 검사한다.",
    "sourcePage": 58,
    "status": "PARTIAL",
    "implementedScope": "The full source six-component system, sparse A1 block identity, zero-axis inverse and a two-parity outward Picard tail are executable. The actual common radial interval is pinned; the displayed scalar tail uses explicitly declared operator bounds.",
    "testStatus": "BOUNDED_COMPONENT_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-picard.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [
      "Derive actual source C_n and the full eta-strip radius at each order.",
      "Evaluate the same-profile six-component Picard solution with those bounds on the fixed common interval."
    ],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-04",
    "title": "차수별 radial cutoff와 모멘트 복구",
    "criteria": "Lemma5.2에 따라 En,Un을 확장하고 Vn, Πn을 재구성한 뒤 (5.10)-(5.12)의 다섯 total moments를 0으로 맞춘다. 합격:\nn차수의 moment correction 완료 전 n+1 source 생성 금지. n=1과 n≥2의 다른 Tn support를 각각 검사한다.",
    "sourcePage": 58,
    "status": "PARTIAL",
    "implementedScope": "An outward-certified five-moment matrix operator uses the actual lambda and reserved Ipos. A confluent U row avoids replacing tiny lambda by zero. Five disjoint smooth bump supports, both stress support cases and a closed next-order reuse guard are recorded.",
    "testStatus": "BOUNDED_COMPONENT_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-moments.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [
      "Evaluate actual extended positive-order profiles and five total moment functions for every eta.",
      "Apply the resulting corrections, reconstruct V_n/Pi_n, and certify their derivatives before n+1 source reuse."
    ],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-05",
    "title": "유한 배경 잔차 검증",
    "criteria": "Fslow=R+div T를 직접 계산하고 (5.25)의 q^[2h(N+1) −Km] bound와 비교한다. 합격: N 증가에 따른 실제 잔차 감소를\n정밀도·격자와 독립 추적한다. CN,m와 Km이 미계산이면 검증된 tail bound로 표시하지 않는다.",
    "sourcePage": 58,
    "status": "PARTIAL",
    "implementedScope": "The full original finite physical PDE residual polynomial and source stress reconstruction (5.9) are exported. No uncomputed C_N,m, K_m, actual stress or numerical residual-decay claim is manufactured.",
    "testStatus": "BOUNDED_COMPONENT_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-residual.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [
      "Substitute actual repaired coefficients and assemble R+div(T).",
      "Measure order refinement independently of grid and precision, then certify C_N,m and K_m."
    ],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-06",
    "title": "Shrinking cutoff 스케줄",
    "criteria": "Lemma5.4에 따라 aj+1≥2aj와 (5.37)의 유한 조건을 차례로 만족시키는 cutoff를 선택한다. 합격: 0≤m≤j에서 Ĉj,m(1+|\nlogq|)^P q^(gj/2)≤2^−j를 전체 q≤1/aj에 대해 상계한다. constants 없는 경험적 aj는 미인증으로 표시한다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "The scalar schedule satisfies exact doubling and the outward (5.37) inequality for every supplied m<=j on the entire q interval. A separate ledger certifies only the conditional scalar implication and explicitly leaves actual source derivative-constant provenance unverified.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-cutoffs.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-contract-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false,
    "conditionalSourceInstantiation": "The executable conditional operator is complete. Its supplied constants, potentials or local jets are not claimed to be the full actual N3/N4 source instance; those package obligations remain with the dependent construction criteria."
  },
  {
    "id": "N4-07",
    "title": "Potential에 cutoff 후 curl",
    "criteria": "χ(cnq)Sn 또는 potential을 먼저 합친다. (5.45)의 χ′ radial correction을 포함해 velocity를 복원한다. 합격: div curl=0 및\ndirect axisymmetric swirl의 div=0 항등식이 유지된다. χun만 사용하는 구현은 negative control에서 실패해야 한다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "Exact differentiation of chi(c_n*q)*q^(1-A+lambda_n)*F_n yields the original (5.45) chi-prime radial correction. Full cylindrical divergence and direct axisymmetric swirl divergence vanish identically; omitting the correction gives a nonzero exact negative control.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-curl.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-08",
    "title": "배경 합성과 tail 계약",
    "criteria": "실 제 locally finite sum 과 유 한 formal truncation 을 구 별 하 고 (5.35), (5.39), (5.42), (5.43) 를 기 록 한 다. 합 격: q>0\ncompact domain의 active cutoff index를 정확히 계산하고 tail bound의 유효 영역 q<(2aJ)^ −1을 함께 export한다.\nuncut series 수렴은 주장하지 않는다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "Actual supplied three-component potentials are multiplied by a genuine C-infinity cutoff and summed. Exact compact-domain a_J*q_min>=1 plus the doubling continuation proves every unseen higher summand vanishes; exhausted prefixes export localSum=null. The strict q<(2*a_J)^-1 tail domain and the distinction from an uncut finite formal truncation are retained.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-cutoffs.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-contract-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false,
    "conditionalSourceInstantiation": "The executable conditional operator is complete. Its supplied constants, potentials or local jets are not claimed to be the full actual N3/N4 source instance; those package obligations remain with the dependent construction criteria."
  },
  {
    "id": "N5-01",
    "title": "Dyadic chart 생성",
    "criteria": "Q=2^−ℓ, ε=Q^h, S*=ℓ², (R,Z,T)=(r/√Q,z/Q^D, τ/Q)를 고정하고 band마다 discrete labels를 생성한다. 합격: 동일 샘\n플이 겹치는 chart에서 같은 physical quantity를 준다. 미분 중 ceil/round 주파수와 labels를 다시 선택하지 않는다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "The accepted assembly-to-core SHA chain binds actual eta-zero Phi intervals at the five recorded source Y values. Each chart independently reconstructs q=Q*T and Y=Lambda*R^2/(2*T). Exact affine-h exponent algebra proves physical swirl scaling; transformed and independently restored outward intervals agree. Axis extension and positive symbolic underflow factors are preserved.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-core-charts.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-core-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-02",
    "title": "Auxiliary torus와 chain rule",
    "criteria": "Jg=[[3,1],[1,5]], Y=vr r^dr+vt t mod Z² 및 (6.6)의 evaluated derivatives를 사용한다. 합격: Dr,Dz,t*의 chain-rule 항\n을 모두 포함한다. torus 평균 후 물리 phase 평가의 순서를 반대로 하여 pointwise 값을 평균으로 대체하지 않는다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "Exact Q(sqrt(2)) identities verify the source eigenvectors, dual coordinates and Jacobian. All slow and fast (6.6) chain-rule terms are applied with the actual source exponent and covering. Physical pointwise evaluation is explicitly distinct from normalized Haar averaging.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-torus.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-03",
    "title": "겹치는 pulse의 지지 분리",
    "criteria": "Lemma6.1의 conflict graph에 따라 overlapping slow supports에 서로소 auxiliary rectangles를 할당한다. 합격: 모든\nactive label pair의 support intersection을 검사한다. 서로 다른 labels의 곱은 실제로 0이어야 하며 same-label harmonics\n는 유지한다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "A deterministic 2,250-color palette covers the complete countable source mesh. Exact rational centers and one r0 certify every ordered covering constraint through Delta=4 and all enlarged support intersections; actual active labels are a subset. Same-label harmonics and once-per-slow-box counting are retained.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-support.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-04",
    "title": "위상·편극·주파수",
    "criteria": "k=ceil(ε^−1/2), kp는 0이 아닌 정수, (7.3)-(7.8)의 Φ,nΦ,K,AΦ,B를 생성한다. 합격: nΦ·tm=0과 nonzero denominators\n를 검사한다. 1≤ εk²≤4 및 frame determinant lower bound를 인증된 영역에서 만족한다.",
    "sourcePage": 60,
    "status": "PARTIAL",
    "implementedScope": "Full three-component source phase normal, including F_Z and G_Z, is retained. Fixed angular frequencies, tangent polarization and denominator checks execute on explicit local jets; a fixed orthogonal rotation supports the general affine normal.",
    "testStatus": "BOUNDED_COMPONENT_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-pulse-ode.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [
      "Derive the uniform source slow-domain q_star and certified frame determinant lower bounds from the actual N3 field."
    ],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-05",
    "title": "성장·감쇠 ODE 풀이",
    "criteria": "(7.13),(7.17)의 projected ODE를 풀고 P(v)=exp∫( λ−dref)를 log envelope로 저장한다. 합격: (7.22)의 amplitude\nenergy balance, n Φ·tm 제약, midpoint normalization과 양 끝 Gaussian bound를 검사한다. underflow를 pulse가 정\n확히 0인 것으로 처리하지 않는다.",
    "sourcePage": 60,
    "status": "PARTIAL",
    "implementedScope": "Parallel tangent coordinates retain the normal constraint and separate analytic scalar damping from logarithmic amplitude. The source Bs-squared definition is corrected, and the reference P envelope has a continuous Gaussian bound for explicit parameters. General affine normals and fourth-order refinement are checked against an independent original Cartesian ODE solver; the actual source growing-mode datum and uniform constants remain unlinked.",
    "testStatus": "BOUNDED_COMPONENT_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-pulse-ode.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [
      "Enclose actual pulse ODE integration error and all requested slow derivatives.",
      "Derive actual uniform Gaussian constants and two-end decay bounds."
    ],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-06",
    "title": "두 family의 positive covariance",
    "criteria": "(7.27)의 angular 1/2 및 Haar Jacobian을 포함해 Hcov를 적분하고 y=Hcov^ −1T0,*를 푼다. 합격: y±>0, det lower\nbound, C(W0)=εT0,* 및 global (7.30)을 확인한다. 같은 slow box를 ±로 두 번 합산하지 않는다.",
    "sourcePage": 60,
    "status": "PARTIAL",
    "implementedScope": "The covariance fixture now uses the source rectangle Jacobian 4-2*sqrt(2) and angular factor 1/2. The normalized covering factor is 1, because all inverse lifts are included. Historical incorrect 1/14 fixtures are explicitly excluded from acceptance.",
    "testStatus": "BOUNDED_COMPONENT_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-covariance.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [
      "Integrate the actual two source pulses, certify positive weights/determinant bounds, and assemble the once-per-box global (7.30) stress."
    ],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-07",
    "title": "정확한 curl과 remainder",
    "criteria": "Cm=i(nΦ×tm)/(km|n Φ|²), physical potential scale Q^(1/2 −A)를 사용한다. cutoff 후 curl의 rm도 유지한다. 합격:\ndiv curl 항등식, physical Cartesian divergence numerical convergence, conjugate symmetry를 확인한다. rm 누락 시\ncovariance/residual test가 실패한다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "The original Cm=i*(n cross t)/(km|n|^2) is differentiated by third-order mixed source jets, including every fast/slow and cylindrical-frame derivative in rm. Exact div-curl and physical Q exponent identities, independent Cartesian curl/divergence refinement, conjugate harmonics and omitted-rm covariance/residual negative controls pass. The numerical coefficients are explicitly an operator probe.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-pulse-curl.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/tests.tap",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-08",
    "title": "Cutoff tail의 flatness 추적",
    "criteria": "(7.40)의 (1 −ψ)fm+ψ′tm를 버리지 않고 별도 잔차로 기록한다. S*^C exp( −cS*)와 q의 관계를 상계한다. 합격: 각 고정\nm,N에 대해 −cℓ²+(M+N)ℓlog2+2Clogℓ를 써서 bound를 평가한다. machine-zero만으로 모든 차수 flatness를 인증하지\n않는다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "The full (1-psi)*f_m+psi_prime*t_m is actually evaluated from supplied complex interval derivative jets, with all Leibniz terms and resolvable input paths. Outward fixed-order log bounds and a monotone all-later-label threshold are certified conditionally on the declared Gaussian/derivative-loss envelope. Actual source envelope provenance is not inferred from finite jets.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-tail.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-contract-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false,
    "conditionalSourceInstantiation": "The executable conditional operator is complete. Its supplied constants, potentials or local jets are not claimed to be the full actual N3/N4 source instance; those package obligations remain with the dependent construction criteria."
  }
];
export function getChecklist(){return JSON.parse(JSON.stringify(CHECKLIST));}
