// Original 16 N4/N5 criteria, preserved verbatim from the user-supplied blueprint.
export const BLUEPRINT_SOURCE = {"name":"MathScope_Research_IDE_Blueprint_v1_KO(1)(9).pdf","sha256":"f4758ab0c6f4038ab30cd9d3d945a471a467f9ffb4d36a0e172f95320720f0ac","pages":[58,60]};
export const CHECKLIST = [
  {
    "id": "N4-01",
    "title": "차수와 기호 충돌 분리",
    "criteria": "λn=2nh, En,Un,Vn,Πn와 scalar φn을 구분한다. η의 Fourier 차수·radial analytic 차수·배경 차수를 서로 다른 인덱스로 둔\n다. 합격: (5.1)의 q 지수와 E_n=√(2X) φn/C를 자동 단위 검사한다. Π0의 axis trace와 전체 pressure profile을 혼동하면\n실패다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "Exact q-power arithmetic checks (5.1), 1-2D=2h, A+D=1 and the radial pressure shift. An axis-trace pressure substitution or replacement of the pinned N3 h is rejected. Background, radial and eta indices are distinct.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-recursion.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-02",
    "title": "비선형 convolution 생성",
    "criteria": "(5.3)-(5.6)의 모든 i+j=n 곱을 생성한다. i=0,n 및 n,0은 현재 미지수에 선형이고 나머지는 확정된 이전 차수다. 합격: n=1,2\n의 직접 PDE 대입 결과와 coefficient extractor가 일치한다. axial viscosity의 n −1 shift와 압력 Ωn−1/(2X)를 반드시 포함\n한다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "The original cylindrical PDE is physically differentiated as an exact BigInt rational differential polynomial. Its n=1,2 coefficients equal independently generated (5.2)-(5.6), including all ordered pairs, vector connection terms and both n-1 shifts.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-recursion.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-03",
    "title": "차수별 inner Picard 풀이",
    "criteria": "(5.7)의 6성분 선형계와 (5.8)의 convergent Picard series를 사용하고 영 axis datum을 유지한다. 합격: 선택 analytic\nstrip·Cn·Cauchy radius loss를 기록하고 Picard tail를 상계한다. 반경 interval은 차수에 따라 임의 축소하지 않으며 lemma\n의 공통 interval 조건을 검사한다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "원래 N3의 고정 차수 n=1에서 (5.7)의 6성분 계를 정확한 C 대각변환으로 연결합니다. 원래 공통 collar, 실제 source-derived C1, 양의 analytic strip과 Cauchy loss, 유한 K의 정확식 및 Picard tail을 인증합니다. 실제 축·양의 반경 관측과 독립 Laurent/Fraction 검사를 실행했습니다. 거대한 K항 수치 합산, 고차 모멘트 복구와 전체 N4 패키지는 별도 범위입니다.",
    "testStatus": "ACTUAL_FIXED_ORDER_CERTIFICATE_AND_INDEPENDENT_ALGEBRA_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-actual-picard-acceptance.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/actual-picard-acceptance.json",
    "sourceInstanceCertified": true,
    "allOrderSourceCertificate": false,
    "certifiedScope": {
      "backgroundOrders": [
        1
      ],
      "commonCollar": "original Xa*exp(t1/16)",
      "parameterDomain": "all real eta in [-1,1] and the stated complex tube",
      "finiteCriterionComplete": true,
      "numericalKTermSumExecuted": false,
      "packageCompletionGate": false
    },
    "reviewPath": "mathscope-m2/navier/research/FINITE_CRITERIA_REAUDIT_KO.md"
  },
  {
    "id": "N4-04",
    "title": "차수별 radial cutoff와 모멘트 복구",
    "criteria": "Lemma5.2에 따라 En,Un을 확장하고 Vn, Πn을 재구성한 뒤 (5.10)-(5.12)의 다섯 total moments를 0으로 맞춘다. 합격:\nn차수의 moment correction 완료 전 n+1 source 생성 금지. n=1과 n≥2의 다른 Tn support를 각각 검사한다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "같은 실제 N3의 B.22/B.26/B.34/B.8, C.12/I1, 전체 outer와 I2/heat를 수렴 함수 연산으로 구성합니다. 실제 n=1,2의 cutoff·다섯 incoming moment와 연속 Ipos inverse를 연결해 총 10개 모멘트를 정확히 복구하고 Vn/Πn을 재구성했습니다. 12개 내부 PDE 항등식, 원래 preheat (5.19)와 열 보상·네 보존형 total, T1θ의 Xb 끝점과 나머지 Xplus 끝점을 검증합니다. 실제 복구 객체만 다음 source를 허용하며 복사·변조·보정 전 입력을 차단합니다. 전역 signed 적분값의 수치 근사와 모든 차수의 구성은 별도 범위입니다.",
    "testStatus": "ACTUAL_CONVERGENT_FUNCTION_MOMENT_REPAIR_PDE_SUPPORT_AND_INDEPENDENT_CONSERVATION_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-actual-moment-restoration.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/actual-moment-restoration-executed.json",
    "sourceInstanceCertified": true,
    "allOrderSourceCertificate": false,
    "certifiedScope": {
      "backgroundOrders": [1, 2],
      "actualMomentIdentities": 10,
      "actualInnerPDEIdentities": 12,
      "actualStressSupports": 4,
      "finiteCriterionComplete": true,
      "actualPriorMomentGate": true,
      "preHeatAndHeatAngularInvariantVerified": true,
      "signedGlobalMomentValuesNumericallyEnclosed": false,
      "allOrdersConstructed": false,
      "packageCompletionGate": false
    },
    "reviewPath": "mathscope-m2/navier/research/ACTUAL_MOMENT_RESTORATION_KO.md"
  },
  {
    "id": "N4-05",
    "title": "유한 배경 잔차 검증",
    "criteria": "Fslow=R+div T를 직접 계산하고 (5.25)의 q^[2h(N+1) −Km] bound와 비교한다. 합격: N 증가에 따른 실제 잔차 감소를\n정밀도·격자와 독립 추적한다. CN,m와 Km이 미계산이면 검증된 tail bound로 표시하지 않는다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "같은 실제 N3 source에서 보존된 고정 core compact 전체에 N=0,1의 원래 PDE 잔차 R+div(T)를 계산합니다. 실제 leading 압력과 n=1 Picard 해, T0/T1의 정확한 내부 restriction을 연결하며 CNm의 양의 source 식과 공통 Km=2+m을 m≤6까지 도출합니다. 동일 q·물리 배율에서 실제 N0 norm의 양의 하한과 N1 전체 영역 상한을 비교해 감소를 인증하고, 고정 좌표의 격자·산술 정밀도 정련을 따로 실행합니다. 전체 profile·모든 N은 별도 범위입니다.",
    "testStatus": "ACTUAL_FIXED_DOMAIN_RESIDUAL_AND_INDEPENDENT_FRACTION_CERTIFICATE_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-actual-residual-order.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/actual-residual-order-independent.json",
    "sourceInstanceCertified": true,
    "allOrderSourceCertificate": false,
    "certifiedScope": {
      "backgroundOrders": [0, 1],
      "derivativeOrders": [0, 1, 2, 3, 4, 5, 6],
      "fixedSimilarityCompact": "X in [0,4*Xunit], eta in [-1,1], all theta; Xunit is a fixed positive source expression",
      "supremumDomain": "Original space-time set at fixed q; tau=q*(1-eta^2), z=q^D*eta",
      "finiteCriterionComplete": true,
      "actualCNmAndKmComputed": true,
      "wholeProfileResidualComplete": false,
      "allNResidualComplete": false,
      "packageCompletionGate": false
    },
    "reviewPath": "mathscope-m2/navier/research/ACTUAL_RESIDUAL_ORDER_KO.md"
  },
  {
    "id": "N4-06",
    "title": "Shrinking cutoff 스케줄",
    "criteria": "Lemma5.4에 따라 aj+1≥2aj와 (5.37)의 유한 조건을 차례로 만족시키는 cutoff를 선택한다. 합격: 0≤m≤j에서 Ĉj,m(1+|\nlogq|)^P q^(gj/2)≤2^−j를 전체 q≤1/aj에 대해 상계한다. constants 없는 경험적 aj는 미인증으로 표시한다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "The scalar schedule satisfies exact doubling and the outward (5.37) inequality for every supplied m<=j on the entire q interval. A separate ledger certifies only the conditional scalar implication and explicitly leaves actual source derivative-constant provenance unverified.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-cutoffs.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-contract-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false,
    "conditionalSourceInstantiation": "The executable conditional operator is complete. Its supplied constants, potentials or local jets are not claimed to be the full actual N3/N4 source instance; those package obligations remain with the dependent construction criteria."
  },
  {
    "id": "N4-07",
    "title": "Potential에 cutoff 후 curl",
    "criteria": "χ(cnq)Sn 또는 potential을 먼저 합친다. (5.45)의 χ′ radial correction을 포함해 velocity를 복원한다. 합격: div curl=0 및\ndirect axisymmetric swirl의 div=0 항등식이 유지된다. χun만 사용하는 구현은 negative control에서 실패해야 한다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "Exact differentiation of chi(c_n*q)*q^(1-A+lambda_n)*F_n yields the original (5.45) chi-prime radial correction. Full cylindrical divergence and direct axisymmetric swirl divergence vanish identically; omitting the correction gives a nonzero exact negative control.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-curl.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N4-08",
    "title": "배경 합성과 tail 계약",
    "criteria": "실 제 locally finite sum 과 유 한 formal truncation 을 구 별 하 고 (5.35), (5.39), (5.42), (5.43) 를 기 록 한 다. 합 격: q>0\ncompact domain의 active cutoff index를 정확히 계산하고 tail bound의 유효 영역 q<(2aJ)^ −1을 함께 export한다.\nuncut series 수렴은 주장하지 않는다.",
    "sourcePage": 58,
    "status": "PASS",
    "implementedScope": "Actual supplied three-component potentials are multiplied by a genuine C-infinity cutoff and summed. Exact compact-domain a_J*q_min>=1 plus the doubling continuation proves every unseen higher summand vanishes; exhausted prefixes export localSum=null. The strict q<(2*a_J)^-1 tail domain and the distinction from an uncut finite formal truncation are retained.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-cutoffs.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-contract-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false,
    "conditionalSourceInstantiation": "The executable conditional operator is complete. Its supplied constants, potentials or local jets are not claimed to be the full actual N3/N4 source instance; those package obligations remain with the dependent construction criteria."
  },
  {
    "id": "N5-01",
    "title": "Dyadic chart 생성",
    "criteria": "Q=2^−ℓ, ε=Q^h, S*=ℓ², (R,Z,T)=(r/√Q,z/Q^D, τ/Q)를 고정하고 band마다 discrete labels를 생성한다. 합격: 동일 샘\n플이 겹치는 chart에서 같은 physical quantity를 준다. 미분 중 ceil/round 주파수와 labels를 다시 선택하지 않는다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "The accepted assembly-to-core SHA chain binds actual eta-zero Phi intervals at the five recorded source Y values. Each chart independently reconstructs q=Q*T and Y=Lambda*R^2/(2*T). Exact affine-h exponent algebra proves physical swirl scaling; transformed and independently restored outward intervals agree. Axis extension and positive symbolic underflow factors are preserved.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-core-charts.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-core-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-02",
    "title": "Auxiliary torus와 chain rule",
    "criteria": "Jg=[[3,1],[1,5]], Y=vr r^dr+vt t mod Z² 및 (6.6)의 evaluated derivatives를 사용한다. 합격: Dr,Dz,t*의 chain-rule 항\n을 모두 포함한다. torus 평균 후 물리 phase 평가의 순서를 반대로 하여 pointwise 값을 평균으로 대체하지 않는다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "Exact Q(sqrt(2)) identities verify the source eigenvectors, dual coordinates and Jacobian. All slow and fast (6.6) chain-rule terms are applied with the actual source exponent and covering. Physical pointwise evaluation is explicitly distinct from normalized Haar averaging.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-torus.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-03",
    "title": "겹치는 pulse의 지지 분리",
    "criteria": "Lemma6.1의 conflict graph에 따라 overlapping slow supports에 서로소 auxiliary rectangles를 할당한다. 합격: 모든\nactive label pair의 support intersection을 검사한다. 서로 다른 labels의 곱은 실제로 0이어야 하며 same-label harmonics\n는 유지한다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "A deterministic 2,250-color palette covers the complete countable source mesh. Exact rational centers and one r0 certify every ordered covering constraint through Delta=4 and all enlarged support intersections; actual active labels are a subset. Same-label harmonics and once-per-slow-box counting are retained.",
    "testStatus": "EXACT_SOURCE_CRITERION_TESTS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-support.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-independent-checks.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-04",
    "title": "위상·편극·주파수",
    "criteria": "k=ceil(ε^−1/2), kp는 0이 아닌 정수, (7.3)-(7.8)의 Φ,nΦ,K,AΦ,B를 생성한다. 합격: nΦ·tm=0과 nonzero denominators\n를 검사한다. 1≤ εk²≤4 및 frame determinant lower bound를 인증된 영역에서 만족한다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "완성 배경과 정확히 일치하는 실제 Imean 장으로 Φ,nΦ,K,AΦ,U,J,B,B′,left inverse를 생성합니다. 실제 η=0,s=1 대표점 주변의 원래 4/Sstar³ slow 영역과 전체 v 구간에서 nonzero kp, 1≤εk²≤4, normal·frame determinant 하계를 검증합니다. 생성식의 전체 Imean 영역과 인증된 작은 이웃을 구분합니다.",
    "testStatus": "ACTUAL_SOURCE_PULSE_AND_INDEPENDENT_FRACTION_DECIMAL_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-actual-pulse-amplitude.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/actual-pulse-amplitude-independent.json",
    "sourceInstanceCertified": true,
    "allOrderSourceCertificate": false,
    "reviewPath": "mathscope-m2/navier/research/FINITE_CRITERIA_REAUDIT_KO.md",
    "certifiedScope": {
      "actualCompletedBackgroundRestriction": "Imean; equations (5.18),(5.44),(5.45)",
      "representative": {
        "eta": 0,
        "s": 1,
        "y": [
          0.25,
          4.75
        ]
      },
      "pulseInterval": "0<=v<=Ls",
      "finiteCriterionComplete": true,
      "generalForcingInverseComplete": false,
      "wholeAnnulusPulseCertified": false,
      "packageCompletionGate": false,
      "slowNeighborhood": "Source distance <=4/Sstar^3 from the fixed representative, within the original Imean."
    }
  },
  {
    "id": "N5-05",
    "title": "성장·감쇠 ODE 풀이",
    "criteria": "(7.13),(7.17)의 projected ODE를 풀고 P(v)=exp∫( λ−dref)를 log envelope로 저장한다. 합격: (7.22)의 amplitude\nenergy balance, n Φ·tm 제약, midpoint normalization과 양 끝 Gaussian bound를 검사한다. underflow를 pulse가 정\n확히 0인 것으로 처리하지 않는다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "원문 homogeneous m=1의 왼쪽 성장 초기조건으로 (7.13),(7.17)의 실제 projected ODE를 풉니다. 원래 moving normal·B′·damping을 보존한 Liouville 환원과 양의 Volterra 비교로 전체 펄스 진폭을 구간화하고 (7.22) energy, 직교 제약, P 중점 정규화와 양 끝 Gaussian을 검사합니다. 실제 중점 x/P는 약0.353553이며 unit seed로 교체하지 않습니다. 양의 극소 배율과 미계산 general forcing 범위를 보존합니다.",
    "testStatus": "ACTUAL_SOURCE_PULSE_AND_INDEPENDENT_FRACTION_DECIMAL_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-actual-pulse-amplitude.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/actual-pulse-amplitude-independent.json",
    "sourceInstanceCertified": true,
    "allOrderSourceCertificate": false,
    "reviewPath": "mathscope-m2/navier/research/FINITE_CRITERIA_REAUDIT_KO.md",
    "certifiedScope": {
      "actualCompletedBackgroundRestriction": "Imean; equations (5.18),(5.44),(5.45)",
      "representative": {
        "eta": 0,
        "s": 1,
        "y": [
          0.25,
          4.75
        ]
      },
      "pulseInterval": "0<=v<=Ls",
      "finiteCriterionComplete": true,
      "generalForcingInverseComplete": false,
      "wholeAnnulusPulseCertified": false,
      "packageCompletionGate": false
    }
  },
  {
    "id": "N5-06",
    "title": "두 family의 positive covariance",
    "criteria": "(7.27)의 angular 1/2 및 Haar Jacobian을 포함해 Hcov를 적분하고 y=Hcov^ −1T0,*를 푼다. 합격: y±>0, det lower\nbound, C(W0)=εT0,* 및 global (7.30)을 확인한다. 같은 slow box를 ±로 두 번 합산하지 않는다.",
    "sourcePage": 60,
    "status": "PARTIAL",
    "implementedScope": "실제 homogeneous pulse의 Gaussian 좌표 적분과 양의 tail, angular 1/2·원래 Haar Jacobian·χ 질량을 계산했습니다. 동일한 N3의 heat-prepared T0,*와 정확한 F 식을 대조해 양의 y± 및 determinant 하계를 계산하고, 원문에서 허용한 smooth 제곱분할의 모든 활성 항을 대표점에서 합해 C(W0)=εT0,*와 (7.30)을 확인했습니다. 전체 slow 이웃·annulus에 공통인 실제 q* 및 uniform covariance는 남아 있습니다.",
    "testStatus": "ACTUAL_COVARIANCE_STRESS_POSITIVE_INVERSE_AND_COMPLETE_POINT_SUM_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-actual-covariance-matching.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [
      "Certify actual completed-background C2 and edge-direction bounds on every enlarged slow neighborhood with a common source-derived q*.",
      "Propagate the actual integrated covariance column and positive inverse bounds uniformly over the complete active annulus and sum the resulting full family."
    ],
    "independentEvidencePath": "mathscope-m2/navier/evidence/actual-pulse-covariance-matching-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false,
    "additionalEvidencePaths": [
      "mathscope-m2/navier/evidence/actual-pulse-covariance-independent.json",
      "mathscope-m2/navier/evidence/actual-mean-stress-executed.json",
      "mathscope-m2/navier/research/ACTUAL_PULSE_COVARIANCE_MATCHING.md"
    ],
    "evidencePaths": [
      "mathscope-m2/navier/evidence/ns-m2-actual-covariance-matching.json",
      "mathscope-m2/navier/evidence/actual-pulse-covariance-matching-independent.json",
      "mathscope-m2/navier/evidence/actual-pulse-covariance-independent.json",
      "mathscope-m2/navier/evidence/actual-mean-stress-executed.json",
      "mathscope-m2/navier/research/ACTUAL_PULSE_COVARIANCE_MATCHING.md"
    ],
    "actualFiniteScope": {
      "sourceProfile": "same-profile-2026-10-10.3",
      "domain": {
        "eta": 0,
        "qOverQ": 1,
        "y": [
          0.25,
          4.75
        ]
      },
      "actualLocalCovarianceMatched": true,
      "actualCompletePointwiseActiveSumExecuted": true,
      "sourceUniformQStarCertified": false,
      "wholeAnnulusCovarianceMatched": false,
      "originalWholeCriterionComplete": false
    }
  },
  {
    "id": "N5-07",
    "title": "정확한 curl과 remainder",
    "criteria": "Cm=i(nΦ×tm)/(km|n Φ|²), physical potential scale Q^(1/2 −A)를 사용한다. cutoff 후 curl의 rm도 유지한다. 합격:\ndiv curl 항등식, physical Cartesian divergence numerical convergence, conjugate symmetry를 확인한다. rm 누락 시\ncovariance/residual test가 실패한다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "The original Cm=i*(n cross t)/(km|n|^2) is differentiated by third-order mixed source jets, including every fast/slow and cylindrical-frame derivative in rm. Exact div-curl and physical Q exponent identities, independent Cartesian curl/divergence refinement, conjugate harmonics and omitted-rm covariance/residual negative controls pass. The numerical coefficients are explicitly an operator probe.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-pulse-curl.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/tests.tap",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false
  },
  {
    "id": "N5-08",
    "title": "Cutoff tail의 flatness 추적",
    "criteria": "(7.40)의 (1 −ψ)fm+ψ′tm를 버리지 않고 별도 잔차로 기록한다. S*^C exp( −cS*)와 q의 관계를 상계한다. 합격: 각 고정\nm,N에 대해 −cℓ²+(M+N)ℓlog2+2Clogℓ를 써서 bound를 평가한다. machine-zero만으로 모든 차수 flatness를 인증하지\n않는다.",
    "sourcePage": 60,
    "status": "PASS",
    "implementedScope": "The full (1-psi)*f_m+psi_prime*t_m is actually evaluated from supplied complex interval derivative jets, with all Leibniz terms and resolvable input paths. Outward fixed-order log bounds and a monotone all-later-label threshold are certified conditionally on the declared Gaussian/derivative-loss envelope. Actual source envelope provenance is not inferred from finite jets.",
    "testStatus": "SOURCE_OPERATOR_AND_NEGATIVE_CONTROLS_PASS",
    "formalComplete": false,
    "evidencePath": "mathscope-m2/navier/evidence/ns-m2-tail.json",
    "acceptanceScope": "PASS means this original finite operator/observation acceptance criterion is met on the stated inputs. It does not certify the blueprint M2 package completion gate, actual all-order background/stress/flat-error assembly, or a new global Navier-Stokes theorem.",
    "remainingObligations": [],
    "independentEvidencePath": "mathscope-m2/navier/evidence/source-contract-independent.json",
    "sourceInstanceCertified": false,
    "allOrderSourceCertificate": false,
    "conditionalSourceInstantiation": "The executable conditional operator is complete. Its supplied constants, potentials or local jets are not claimed to be the full actual N3/N4 source instance; those package obligations remain with the dependent construction criteria."
  }
];
export function getChecklist(){return JSON.parse(JSON.stringify(CHECKLIST));}
