#!/usr/bin/env python3
from pathlib import Path
import json,hashlib,subprocess,re
BASE=Path(__file__).resolve().parent;ROOT=BASE.parents[1];repo=BASE/'sources/official-repo'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
previous=json.loads((ROOT/'mathscope-extension/ns-paper.json').read_text());pages=(ROOT/'navier-stokes.txt').read_text().split('\f')
if pages[-1].strip()=='': pages.pop()
assert len(pages)==166
attachment=ROOT/'upload/01-navier-stokes.pdf';assert sha(attachment)==previous['attachment']['sha256']
files=['lean-toolchain','lakefile.toml','lake-manifest.json','NavierStokes.lean','NavierStokes/ComparatorSolution.lean','NavierStokes/ComparatorR3Theorem.lean','NavierStokes/ComparatorTheorem.lean','NavierStokes/Flatness.lean','NavierStokes/ProblemStatement.lean','ComparatorChallenges/NavierStokes.lean','ComparatorChallenges/NavierStokes.json']
lock={'schemaVersion':1,'attachment':{'fileName':attachment.name,'pageCount':166,'sha256':sha(attachment),'title':'Finite Time Blowup for Navier–Stokes','author':'OpenAI','date':'2026-09-08'},'repository':{'url':'https://github.com/openai/NavierStokesAndEuler','commit':subprocess.check_output(['git','-C',str(repo),'rev-parse','HEAD'],text=True).strip(),'toolchain':(repo/'lean-toolchain').read_text().strip(),'files':[{'path':p,'sha256':sha(repo/p)} for p in files],'originalFullBuild':{'performed':False,'exitCode':None,'reason':'M1 performs narrow unchanged external-source component checks on local Lean/mathlib4.34.1; original rc2 full repository/Comparator build remains pending.'}},'publicStatus':[{'id':'N01','url':'https://openai.com/index/navier-stokes-solution/','publicationDate':'2026-09-08','updateDate':'2026-09-10','retrievedDate':'2026-10-09','status':'ANNOUNCEMENT','claim':'OpenAI reports an analytical and Lean proof for forced alternatives C/D. This record is an attributed publication claim.'},{'id':'N02','url':'https://www.claymath.org/news/navier-stokes-announcement/','publicationDate':'2026-09-11','retrievedDate':'2026-10-09','status':'INSTITUTIONAL_ANNOUNCEMENT','claim':'Clay describes the problem as apparently settled and explains that evaluation and attribution follow a deliberate process. No final prize adjudication is inferred.'}],'scope':'User attachment and pinned source definitions. Unforced A/B are not claimed by this module.'}
contracts={'schemaVersion':1,'paper':'N00','theorem':'Theorem1.1','references':[{'pages':[1],'statement':'Theorem1.1'},{'pages':[120,123,124,125,126],'statement':'Lemma10.3; Corollary10.6; final viscosity/periodic comparison'}],'quantifiers':[{'name':'nu','domain':'real','condition':'nu>0','quantifier':'for every'},{'name':'f','domain':'C_c^infinity(R^3 x (0,infinity);R^3)','quantifier':'there exists','divergenceFreeRequired':False,'divergenceNote':'Global cutoff force is not in general divergence free; source p118.'},{'name':'u,p','domain':'smooth on R^3 x [0,1)','quantifier':'there exist','fixedCompactSpatialSupport':True}],'initialVelocity':'u(x,0)=0','equation':'partial_t u+(u dot grad)u-nu Delta u+grad p=f; div u=0','boundedEnergy':'sup_{0<=t<1} integral_{R^3}|u(x,t)|^2 dx < infinity','blowup':'limsup_{t -> 1-} ||u(t)||_infinity = infinity','forbiddenPromotions':['f=0','smooth velocity at t=1','numerical plot proves theorem','standalone exterior has finite R3 energy','N1-N3 leading candidate is a full Navier-Stokes solution'],'formalGrade':'THEOREM_REFERENCE','mainTheoremKernelCheckedLocally':False}
coverage=[]
for i,txt in enumerate(pages,1):
 sec=[s['id'] for s in previous['sections'] if s['firstPage']<=i<=s['lastPage']]
 coverage.append({'page':i,'sections':sec,'characters':len(txt.strip()),'textSha256':hashlib.sha256(txt.encode()).hexdigest(),'namedStatements':list(dict.fromkeys(re.findall(r'(?:Theorem|Proposition|Lemma|Corollary|Definition)\s+(?:[A-C]|\d+)\.\d+',txt)))})
refs=[{'id':'N00','url':previous['sources'][0]['url'],'attachmentSha256':sha(attachment),'pages':[1,166]}]+lock['publicStatus']+[{'id':'N03','url':lock['repository']['url'],'commit':lock['repository']['commit']},{'id':'N04','url':'https://www.claymath.org/wp-content/uploads/2022/06/navierstokes.pdf'}]
mapdata={'sections':previous['sections'],'pageCoverage':coverage,'coveragePass':all(p['sections'] and p['characters'] for p in coverage),'dependencyPath':['Theorem4.6','Proposition5.5','Proposition7.5','Proposition9.6','Proposition9.9','Proposition10.1','Lemma10.3','Theorem1.1'],'claimGraph':previous['claimGraph'],'implementationMap':[{'module':'coordinates.mjs','pages':[24,25],'references':['4.1','4.2']},{'module':'profile.mjs','pages':[25,26,27,34,35,36,37],'references':['4.4','4.5','4.6','4.10','4.13','Theorem4.6']},{'module':'radial.mjs','pages':[129,130,133,139,155,156,157,161,162,163],'references':['A.5-A.13','A.21','B.35-B.40','C.12','C.17','C.18']},{'module':'axis-series.mjs','pages':[144,145,146,147,148],'references':['B.1-B.16','PropositionB.2']},{'module':'heat.mjs','pages':[138,139],'references':['LemmaA.6','A.32-A.38']}],'audit':'All166 page text and section/statement structure mapped. This is not a line-by-line independent proof audit.'}
analytic=[
 {'id':'AXIS_B_RHO','operator':'nonlinear axis fixed point and all eta derivatives','norm':'||a||_{B_rho}=sup_{alpha,beta} |a_alpha_beta|/w_alpha_beta; w=20^(-alpha)rho^(-beta) beta! binom(alpha+beta,beta)/((alpha+1)^2(beta+1)^2)','domain':'Y=Lambda X complex analytic neighborhood; eta in a common complex neighborhood Omega of [-1,1]','quantifiers':'There exist rho>0, invariant radius R, and contraction constant 0<=k<1 such that F maps the closed ball into itself and ||F(a)-F(b)||<=k||a-b|| for all a,b in the ball. Banach completeness is required.','requiredBounds':['sup_Omega |g|<=1','holomorphic coefficients and denominators separated from zero','uniform all-eta coefficient/tail and derivative bounds'],'status':'THEOREM_REFERENCE_UNINSTANTIATED','sources':['N00 pp145-148 B.11-B.16']},
 {'id':'DERIVATIVE_LIMIT_EXCHANGE','operator':'partial_eta of infinite reconstruction / derivative of uniform limit','norm':'uniform convergence of derivative on an open real set s; pointwise convergence of functions at each x in s','domain':'s subset R is open; f_n,fp_n,g,gp:s->R','quantifiers':'TendstoUniformlyOn fp gp atTop s; eventually for every x in s HasDerivAt(f_n)(fp_n x)x; for every x in s f_n x tends to g x. Then for each x in s HasDerivAt g(gp x)x.','leanTarget':'MathScope.Navier.Analytic.uniform_derivative_exchange','status':'LOCAL_ADAPTER_BUILD_STATUS_IN_LEAN_LEDGER','limitation':'No array sample establishes these universal convergence hypotheses.'},
 {'id':'HEAT_DOMINATED_DIFFERENTIATION','operator':'derivatives of H under the infinite integral','domain':'Z>=0, 0<h<.01; each fixed derivative order m>=0','norm':'L1(0,infinity) in v','quantifiers':'For each fixed m, abs(partial_Z^m integrand) <= (h)_m exp(-v)v^(h+m), an integrable majorant uniform over Z>=0. Gamma(1+h)>0.','status':'ANALYTIC_REFERENCE_PLUS_EXPLICIT_FINITE_INTERVAL_QUADRATURE','sources':['N00 p138 A.32-A.35'],'limitation':'Implemented derivative orders0..4; unbounded m cannot be inferred from finite output.'},
 {'id':'HEAT_TAYLOR','operator':'finite Taylor expansion at Z=0','domain':'Z>=0,h>0,finiteN','norm':'absolute scalar remainder <= (h)_(N+1)(1+h)_(N+1) Z^(N+1)/(N+1)!','quantifiers':'For every finite N the Taylor remainder bound follows from the derivative majorant. The infinite Taylor series has radius0 for h>0.','status':'FINITE_REMAINDER_EVALUATOR','sources':['N00 p138 A.35']},
 {'id':'BOREL_CUTOFF','operator':'background and all-order correction synthesis beyond M1','domain':'common local physical domain with cutoffs epsilon_k selected per derivative seminorm','norm':'C^m seminorms weighted by q powers; for each fixed m,sum_k norm_m(term_k)<infinity','quantifiers':'For every derivative order m choose all sufficiently late cutoff thresholds so term_k is bounded by2^-k in that seminorm; common supports and divergence-preserving construction are required.','status':'THEOREM_REFERENCE_OUT_OF_M1','sources':['N00 pp59-62 Proposition5.5','N00 pp111-116 Proposition9.9']},
 {'id':'SEMIGROUP','operator':'Fourier diffusion exp(-nu|k|^2 t)','domain':'nu>=0,t>=0,k in Z^3; L2(T3) for contraction','norm':'abs multiplier<=1; coefficient ell2 contraction','quantifiers':'For every nonnegative rate and time,exp(-rate*time)<=1. Infinite-dimensional norm estimate additionally requires Parseval and summability.','leanTarget':'MathScope.Navier.Analytic.diffusion_semigroup_bound','status':'LOCAL_ADAPTER_BUILD_STATUS_IN_LEAN_LEDGER'},
 {'id':'RESIDUAL_STABILITY','operator':'residual to solution error','domain':'specified time interval, normed PDE class, initial/boundary errors and admissible constants','norm':'||u-u_approx|| <= C_stab (||R|| + initialError + boundaryError)','quantifiers':'A stability bound with finite explicitly supplied C_stab is a separate hypothesis; if totalResidual<=epsilon and C_stab>=0 then error<=C_stab epsilon.','leanTarget':'MathScope.Navier.Analytic.stable_residual_budget','status':'LOCAL_CONDITIONAL_ADAPTER','limitation':'No global C_stab is provided for the candidate profile; residual is not reported as a solution-error bound.'},
 {'id':'SPECTRAL_CONTINUUM','operator':'Galerkin limit beyond finite FFT fixture','domain':'solenoidal Fourier fields on T3; fixednu>0,time interval before any asserted singularity','norm':'specified Hs convergence sufficient to multiply and differentiate; e.g. s>5/2 for3D product/control, with separate time regularity','quantifiers':'A uniform-in-cutoff stability/compactness argument and convergence of nonlinear terms are required; finite dealiased convolution identity supplies neither.','status':'THEOREM_REFERENCE_NO_CONTINUUM_LIMIT_CLAIM'},
 {'id':'SPECTRAL_MEASURE','operator':'general infinite-dimensional spectral interpretation','domain':'a densely defined self-adjoint nonnegative operator on a specified Hilbert space','norm':'spectral measure integral exp(-t lambda); Hilbert norm','quantifiers':'Requires self-adjointness, positivity and spectral theorem hypotheses; the scalar diffusion adapter does not certify these for arbitraryPDE operators.','status':'NOT_USED_BY_CURRENT_NS_NUMERICS'}]
grades={'THEOREM_REFERENCE':'Citation and precise statement, no local kernel proof of the full source claim.','SOURCE_FORMULA':'Direct source expression, evaluated with stated normalization and domain.','VERIFIED_NUMERICAL_ENCLOSURE':'Finite real interval quadrature/series and explicit error budget, without full PDE theorem.','FINITE_NUMERICAL_FIXTURE':'Independent finite numerical consistency checks.','FORMAL_NONLINEAR_AXIS_COEFFICIENTS':'Actual finite nonlinear recurrence coefficients; invariant ball, radius and tail are not certified.','PARTIAL_CANDIDATE_WITH_BLOCKERS':'Source axis/exterior components and explicitly unverified continuation; full theorem gate remains closed.','KERNEL_CHECKED_COMPONENTS':'Only exact named imported/local theorem types and their listed axioms pass the local unchanged kernel.','FULL_CERTIFIED_PROFILE':'Reserved; no current computation may emit this grade.'}
for name,value in [('sources.lock.json',lock),('theorem-contract.json',contracts),('paper-reference-map.json',mapdata),('analytic-contracts.json',analytic),('evidence-grades.json',grades)]: (BASE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n')
r={'sources':refs,'lock':lock,'contract':contracts,'map':mapdata,'analyticContracts':analytic,'evidenceGrades':grades};(BASE/'provenance.generated.mjs').write_text('export const provenance = '+json.dumps(r,ensure_ascii=False,indent=2)+';\n')
print('Provenance generated:166page coverage, pinned official sources, explicit analytic contracts.')

# Preserve the separately sealed original-rc2 execution receipt on regeneration.
# This does not promote the historical 4.34.1 component audit or certify a profile.
if (BASE/'official-validation/official-audit-summary.json').exists():
    import subprocess, sys
    subprocess.run([sys.executable, str(BASE/'official-validation/update-m1-evidence.py')], check=True)
