import {ComputeError,integrate,makeBudget,boundedInteger,positive} from './numerics.mjs';
import {parameters,fromSimilarity,toSimilarity} from './coordinates.mjs';
import {solveAxisCoefficients,evaluateAxis} from './axis-series.mjs';
import {buildOuterSchedule,parameterOrder,smoothStep,compactBump,solveFiveMomentRepair,coneMargins,coneModulationFixture} from './radial.mjs';
/** Executable candidate, not Theorem 4.6 certification.
 * The nonlinear axis coefficients and outer unedited schedule are source formulae.
 * The intervening C-infinity diagnostic continuation is identified as such; the
 * paper's uniformly certified B.5/C.1 coupling remains an explicit blocker. Separate component jobs implement those source operators.
 */
export function constructLeadingCandidate(input={},budget=makeBudget()){
  const o={...parameterOrder(input),...parameters(input),axisOrder:input.axisOrder??8},outer=buildOuterSchedule(o,budget),etaCount=boundedInteger(input.etaCount??7,'etaCount',3,21),radialCount=boundedInteger(input.radialCount??25,'radialCount',8,80),Ycore=Math.min(1.8,positive(input.Ycore??1.2,'Ycore')),X0=Ycore/o.Lambda,X1=1.25*X0,Xend=o.XR*Math.exp(-8),patch=[Math.exp(-6),Math.exp(-5)],cache=new Map(),sliceReports=[];
  if(!(Xend>X1))throw new ComputeError('INVALID_SUPPORT','Axis interval overlaps the restoration region; increase XR or shorten axis interval',{X1,Xend});
  function makeSlice(eta,match=true){
    const key=`${eta}:${match}`;if(cache.has(key))return cache.get(key);
    const axis=solveAxisCoefficients(eta,o,outer.pressureJet,budget),anchor=evaluateAxis(axis,X0),f=1/(1+eta*eta);
    const axisValue=X=>evaluateAxis(axis,X);
    const raw=X=>{
      if(X<=X0){const p=axisValue(X);return {E:p.E,U:p.U,F:p.F,stage:'nonlinear-axis-finite-series'};}
      const referenceE=o.PStar*f*(X/o.XR)**.1,powerE=anchor.E*(X/X0)**.1;
      if(X<X1){const c=smoothStep((X-X0)/(X1-X0)),p=axisValue(X),E=(1-c)*p.E+c*powerE;return {E,U:(1-c)*p.U+c*anchor.U,F:E/Math.sqrt(2*X),stage:'diagnostic-axis-collar'};}
      if(X<Xend){const c=smoothStep(Math.log(X/X1)/Math.log(Xend/X1)),E=Math.exp((1-c)*Math.log(Math.max(powerE,Number.MIN_VALUE))+c*Math.log(referenceE));return {E,U:(1-c)*anchor.U+c*4*eta,F:E/Math.sqrt(2*X),stage:'diagnostic-continuation'};}
      const p=outer.component(Math.log(X/o.XR),eta);return {E:p.E??0,U:p.U??0,F:(p.E??0)/Math.sqrt(2*X),stage:p.stage,underflow:p.underflow};
    };
    let repair=null,discrepancy=null;
    if(match){
      const xend=Xend/o.XR,actual=[];
      for(let k=0;k<5;k++)actual.push(integrate(logx=>{const x=Math.exp(logx),p=raw(o.XR*x),H=Math.sqrt(2*x)*p.E;return x*[p.U,H,p.U*H,p.U*p.U-p.E*p.E/2,p.E*p.E/(2*x)][k];},Math.log(X0/o.XR)-28,Math.log(xend),2e-10,budget).value);
      const I=Math.SQRT2*o.PStar*f*xend**1.6/1.6,ideal=[4*eta*xend,I,4*eta*I,16*eta*eta*xend-o.PStar**2*f*f*xend**1.2/2.4,2.5*o.PStar**2*f*f*xend**.2];discrepancy=actual.map((v,k)=>v-ideal[k]);
      try{repair=solveFiveMomentRepair({eta,PStar:o.PStar,lambda:o.lambda,patch,discrepancy},budget);}catch(e){repair={status:'REJECTED_MOMENT_MATCH',error:{code:e.code??'ERROR',message:e.message},coefficients:[0,0,0,0,0],supports:[],acceptance:{continuousFiveMomentsCertified:false}};}
    }
    const value=X=>{const p=raw(X),x=X/o.XR;if(repair?.status==='NUMERICAL_MOMENT_MATCH'&&x>patch[0]&&x<patch[1]){const width=(patch[1]-patch[0])/16,b=repair.supports.map(([l,r])=>compactBump(x,l,r)*width),c=repair.coefficients;const E=p.E+c[2]*b[2]+c[3]*b[3]+c[4]*b[4];return {...p,E,U:p.U+c[0]*b[0]+c[1]*b[1],F:E/Math.sqrt(2*X),stage:'finite-five-moment-repair'};}return p;};
    const s={eta,axis,anchor,raw,value,repair,discrepancy};cache.set(key,s);return s;
  }
  const etaValues=Array.from({length:etaCount},(_,i)=>-.9+1.8*i/(etaCount-1)),slices=etaValues.map((eta,i)=>{budget.progress({phase:'axis-and-moment-candidate',completed:i,total:etaCount});const s=makeSlice(eta);sliceReports.push({eta,axisStatus:s.axis.status,realNormalizationPass:s.axis.data.realNormalizationPass,axisAnchorPhi:s.anchor.Phi,axisAnchorResidual:s.anchor.leadingResidual,discrepancy:s.discrepancy,momentStatus:s.repair?.status,momentResidual:s.repair?.normalizedResidual,positivity:s.repair?.positive,blockers:s.axis.blockers});return s;});
  const Xmax=Math.min(o.XR*Math.exp(-4.5),input.Xmax??Math.max(2,4*X0)),Xsamples=[0,...Array.from({length:radialCount-1},(_,i)=>Math.exp(Math.log(X0/30)+(Math.log(Xmax)-Math.log(X0/30))*i/(radialCount-2)))],points=[],profiles=[];
  const derivativeEta=eta=>{const h=2e-5,sp=makeSlice(eta+h,true),sm=makeSlice(eta-h,true);return {sp,sm,h};};
  for(const s of slices){
    const ed=derivativeEta(s.eta);for(const X of Xsamples){budget.tick();const p=s.value(X),raw=s.raw(X),dx=Math.max(1e-8,X*1e-4),Ex=X===0?0:(s.value(X+dx).E-s.value(Math.max(0,X-dx)).E)/(X+dx-Math.max(0,X-dx)),Ux=X===0?s.anchor.UX:(s.value(X+dx).U-s.value(Math.max(0,X-dx)).U)/(X+dx-Math.max(0,X-dx));
      const average=(slice)=>X===0?slice.value(0).U:integrate(t=>slice.value(X*t).U,0,1,2e-8,budget).value,avgU=average(s),avgUp=average(ed.sp),avgUm=average(ed.sm),avgEta=(avgUp-avgUm)/(2*ed.h),L=1-2*o.h*s.eta*s.eta,d=1-s.eta*s.eta,VoverX=(2*s.eta*p.U-2*(.5-o.h)*s.eta*avgU-d*avgEta)/L;
      const Pi=outer.pressureJet(s.eta,0)[0]+(X===0?0:integrate(t=>{const xx=X*t;if(t===0)return s.value(0).F**2;const v=s.value(xx);return v.F*v.F;},0,1,2e-8,budget).value*X);
      profiles.push({X,eta:s.eta,E:p.E,U:p.U,F:p.F,Pi,V0:X*VoverX,radialPressureBalance:p.F*p.F,stage:p.stage,positivity:p.E>0||X===0,radialDerivativeE:Ex,radialDerivativeU:Ux,continuationGrade:p.stage.startsWith('diagnostic')?'UNVERIFIED_CONTINUATION':'SOURCE_FORMULA_OR_NUMERICAL_COMPONENT'});
      for(let k=0;k<6;k++){if(points.length>=budget.maxPoints)break;const theta=2*Math.PI*k/6,c=fromSimilarity({X,eta:s.eta,theta},o),[x,y,z]=c.position,q=c.q,rootNu=Math.sqrt(o.viscosity),x1=x/rootNu,x2=y/rootNu,v=[rootNu*(VoverX*x1/(2*q)-q**(-1-o.h)*p.F*x2),rootNu*(VoverX*x2/(2*q)+q**(-1-o.h)*p.F*x1),rootNu*q**(-.5-o.h)*p.U];
        if(![...c.position,...v].every(Number.isFinite))throw new ComputeError('PRECISION_REQUIRED','Candidate position or velocity exceeds the finite binary64 range',{X,eta:s.eta,tau:o.tau});points.push({pos:c.position,position:c.position,velocity:v,vector:v,value:Math.hypot(...v),label:`eta=${s.eta.toFixed(2)}, X=${X.toPrecision(3)}, ${p.stage}`,stage:p.stage});}
    }
  }
  const trace=Array.from({length:121},(_,i)=>outer.component(-8+(outer.terminalLogRadius+10)*i/120,0));
  const theoremClauses=[{clause:'4.6(i)',status:'PARTIAL',evidence:'Regular Cartesian axis factors and finite nonlinear series evaluated. Separate rational-datum axis bounds certify a local rectangle; they are not linked to these finite eta jets or to this global candidate.'},{clause:'4.6(ii)',status:'PARTIAL',evidence:'Pressure primitive and solenoidal radial reconstruction executed; source leading stress support and exact zero-residual axis remain unverified.'},{clause:'4.6(iii)',status:'BLOCKED',evidence:'Separate jobs compute B.5 continuation and C.1 admissible loops. This older candidate has no certified coupling to them and no all-eta all-radius kappa certificate.'},{clause:'4.6(iv)',status:'PARTIAL',evidence:'Exact flat weights and endpoint exclusion are implemented as independent operators; factorization of the actual reconstructed stress is not established.'},{clause:'4.6(v)',status:'PARTIAL',evidence:'Actual heat exterior and finite five-moment repair are available. A separate source-outer job computes A.8/A.11/A.7 repairs; uniform exact moment calibration and coupling to this candidate remain pending.'},{clause:'4.6(vi)',status:'PARTIAL',evidence:'Four disjoint source log patches generated; no complete certified profile propagated across them.'}];
  const blockers=[...o.blockers,...outer.blockers,{id:'B5_CONTROLLED_CONTINUATION',criterion:'N3-05',reason:'The displayed intermediate field uses an explicit smooth diagnostic continuation, not a verified solution of the controlled continuation and edge activation in B.5--B.7.'},{id:'C1_ADMISSIBLE_LOOP',criterion:'N3-06',reason:'The separate ns.admissible-loop operation computes actual C.1 loops for supplied states. This candidate has not been coupled to a uniformly certified source loop and its subsequent moment restoration.'},{id:'FULL_STRESS_ENDPOINT_FACTOR',criterion:'N3-07',reason:'Actual T0/|T0| collar limits and stress support require certified coupling of controlled continuation, cone realization and all outer moment repairs. Computing those separate components does not establish the coupling.'},{id:'UNIFORM_ETA_GLUE',criterion:'N3-05',reason:'Moment repairs are solved at sampled eta values; uniform analytic eta dependence, interval Newton inclusion, and the repaired field derivative must be certified before PDE use.'}];
  return {status:'PARTIAL_CANDIDATE_WITH_BLOCKERS',evidenceGrade:'NUMERICAL_COMPONENTS_AND_EXPLICIT_UNVERIFIED_CONTINUATION',model:'paper-leading-profile-candidate',parameters:{...o,ordered:undefined,blockers:undefined},parameterOrder:o.ordered,necessaryParameterChecks:o.checks,points,profiles,sliceReports,outer:{stages:outer.stages,reservedPatches:outer.reserved,logCInfinity:outer.logCInfinity,pressureAudit:outer.pressureAudit(),trace},theoremClauses,blockers,
    fullCertifiedProfile:false,fullNavierStokesSolution:false,scope:'N1--N3 candidate laboratory. N4--N8 background, pulses, full residual iteration, compact force and final construction are not implemented by this result.',
    profileDataContract:{sharedParameterHash:'The envelope parameterHash binds all profiles, derivatives, moment residuals and source version in this result.',leadingConeMargin:null,certifiedStressSupport:null,certifiedGlobalError:null,missingEvidence:'Uniform controlled continuation, all corrected moments and C.1 admissible loop must be supplied before the three missing certificates can be computed.',theoremClausesAccountedFor:theoremClauses.length===6},
    derivativeCaveat:'3D radial velocity uses a finite eta-difference of independently repaired continuation averages. A switch between accepted and rejected neighboring repairs is not a differentiable gluing. Uniform eta dependence and a rigorous derivative error remain unverified; no exact divergence-free gluing claim is made.',
    visualization:{points:points.map(({pos,label,value})=>({pos,label,value})),arrows:points.map(({pos,vector})=>({pos,vector})),lines:[],axes:['x','y','z'],description:'Computed nonlinear axis and explicitly unverified continuation samples; full outer schedule is supplied as a separate log-radius trace.',coordinateMeaning:'physical Cartesian x,y,z for tau>0, with sqrt(nu) rescaling; arrows contain physical velocity components before UI normalization',lostInformation:['Finite viewing window omits the enormous outer radius range.','The continuation is a diagnostic candidate and lacks the paper cone certificate.','Field values do not certify a singularity or global theorem.']},
    diagnostics:{pointCount:points.length,profileCount:profiles.length,finite:points.every(p=>[...p.pos,...p.vector].every(Number.isFinite)),sourceMatchedGaussian:false,maxSpeed:points.length?Math.max(...points.map(p=>p.value)):0},budget:budget.snapshot()};
}
